#  This file is distributed under the BSD 3-Clause License. See LICENSE for details.

sh_library(
    name = "tech_gens",
    srcs = [
        "verilog_json.rb",
    ],
    visibility = ["//visibility:public"],
)

