/-
Snapshot comparison for the mask-endpoint port onto master 8bea45dc2.
The old definitions come from PR endpoint 3685a977e; the new definitions
come from the endpoint adapter. Only names were changed to allow both
snapshots in one file. The final theorems establish equality for every
input, independently of the finite sampled regression oracles.
-/
import LeanSemanticPrimitives.Compiler.CompileDesign
/-
  Generated by LiveHD pass.lean from the shared CertificateIR.
  Fast executable model and legacy GraphCert are optional presentations.
-/


set_option linter.unusedVariables false

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace old_getmask_Lgraph

structure old_getmask_in where
  in_a : BitVec 8
deriving Repr, Inhabited

structure old_getmask_out where
  out_y : BitVec 8
deriving Repr, Inhabited

def old_getmask_comb (i : old_getmask_in) : old_getmask_out :=
  let n_16 : BitVec 8 := ((sem_get_mask (i.in_a) (BitVec.ofInt 8 ((-Int.ofNat 1)))) : BitVec 8)
  { out_y := ((bv_zext n_16) : BitVec 8) }

def old_getmask_nodeCerts : List NodeCert := [
  { nid := 16, op := LGraphOp.Op_GetMask, width := 8, deps := [2000000000, 1000000000] }
]

def old_getmask_sourceEnv (i : old_getmask_in) : Nat -> BV := fun n =>
  if n = 1000000000 then mk_bv 8 ((-Int.ofNat 1)) else
  if n = 2000000000 then mk_bv 8 (Int.ofNat (BitVec.toNat (i.in_a))) else
  mk_bv 0 0

def old_getmask_graphCert : GraphCert :=
  { topo := [16], sources := [1000000000, 2000000000], nodes := nodes_of_list old_getmask_nodeCerts }

def old_getmask_outputsFromCert (rho : Nat -> BV) : old_getmask_out :=
  { out_y := (bv_to_bitvec 8 (rho 16)) }

def old_getmask_comb_cert (i : old_getmask_in) : old_getmask_out :=
  old_getmask_outputsFromCert (evalGraph old_getmask_graphCert.topo old_getmask_graphCert (old_getmask_sourceEnv i))

theorem old_getmask_comb_cert_refines_cert (i : old_getmask_in) : old_getmask_comb_cert i = old_getmask_outputsFromCert (evalGraph old_getmask_graphCert.topo old_getmask_graphCert (old_getmask_sourceEnv i)) := rfl

theorem old_getmask_evalGraph_correct (i : old_getmask_in) :
    envCorrectOn old_getmask_graphCert.topo
      (evalGraph old_getmask_graphCert.topo old_getmask_graphCert (old_getmask_sourceEnv i))
      (graphDenotation old_getmask_graphCert.topo old_getmask_graphCert (old_getmask_sourceEnv i)) := by
  exact evalGraphCorrectForCert old_getmask_graphCert (old_getmask_sourceEnv i)

-- Certificate well-formedness proof skipped (cert_wf=skip).


-- Field mapping (Lean selector -> RTL name).
-- in_a -> a
-- out_y -> y
end old_getmask_Lgraph

/-
  Generated by LiveHD pass.lean from the shared CertificateIR.
  Fast executable model and legacy GraphCert are optional presentations.
-/


set_option linter.unusedVariables false

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace new_getmask_Lgraph

structure new_getmask_in where
  in_a : BitVec 8
deriving Repr, Inhabited

structure new_getmask_out where
  out_y : BitVec 8
deriving Repr, Inhabited

def new_getmask_comb (i : new_getmask_in) : new_getmask_out :=
  let n_16 : BitVec 8 := ((sem_get_mask (i.in_a) (BitVec.ofInt 8 ((Int.ofNat 255)))) : BitVec 8)
  { out_y := ((bv_zext n_16) : BitVec 8) }

def new_getmask_nodeCerts : List NodeCert := [
  { nid := 16, op := LGraphOp.Op_GetMask, width := 8, deps := [2000000000, 1000000000] }
]

def new_getmask_sourceEnv (i : new_getmask_in) : Nat -> BV := fun n =>
  if n = 1000000000 then mk_bv 8 ((Int.ofNat 255)) else
  if n = 2000000000 then mk_bv 8 (Int.ofNat (BitVec.toNat (i.in_a))) else
  mk_bv 0 0

def new_getmask_graphCert : GraphCert :=
  { topo := [16], sources := [1000000000, 2000000000], nodes := nodes_of_list new_getmask_nodeCerts }

def new_getmask_outputsFromCert (rho : Nat -> BV) : new_getmask_out :=
  { out_y := (bv_to_bitvec 8 (rho 16)) }

def new_getmask_comb_cert (i : new_getmask_in) : new_getmask_out :=
  new_getmask_outputsFromCert (evalGraph new_getmask_graphCert.topo new_getmask_graphCert (new_getmask_sourceEnv i))

theorem new_getmask_comb_cert_refines_cert (i : new_getmask_in) : new_getmask_comb_cert i = new_getmask_outputsFromCert (evalGraph new_getmask_graphCert.topo new_getmask_graphCert (new_getmask_sourceEnv i)) := rfl

theorem new_getmask_evalGraph_correct (i : new_getmask_in) :
    envCorrectOn new_getmask_graphCert.topo
      (evalGraph new_getmask_graphCert.topo new_getmask_graphCert (new_getmask_sourceEnv i))
      (graphDenotation new_getmask_graphCert.topo new_getmask_graphCert (new_getmask_sourceEnv i)) := by
  exact evalGraphCorrectForCert new_getmask_graphCert (new_getmask_sourceEnv i)

-- Certificate well-formedness proof skipped (cert_wf=skip).


-- Field mapping (Lean selector -> RTL name).
-- in_a -> a
-- out_y -> y
end new_getmask_Lgraph

-- Emitted by pass.lean in `formal.lean.mode=verified_compiler`.
-- This file contains NO semantic model and NO proof script: the compiler
-- `Compiler.compileDesign` is proved correct once, for every accepted design,
-- by `Compiler.compileDesign_correct`.  Slots are dense: sources occupy
-- 0..1 and node i occupies 2+i.

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

open Compiler

def old_getmask_designCert : DesignCert :=
  {
    sources  := #[
        SourceDesc.const 8 ((-Int.ofNat 1))
      , SourceDesc.input 0 8
      ]
    nodes    := #[
        { op := LGraphOp.Op_GetMask, width := 8, deps := #[1, 0], origin := 16 }
      ]
    outputs  := #[
        { slot := 2, width := 8 }
      ]
    flops    := #[]
    memories := #[]
  }

/-- Compile-and-run.  The model IS the verified compiler applied to this
certificate -- there is no separately emitted model to disagree with it. -/
def old_getmask_step : RuntimeInput → RuntimeState → RuntimeResult :=
  compileAndRun old_getmask_designCert

/-- The whole per-design obligation: ONE boolean check.

`native_decide`, not `.get!`: a compile failure is a BUILD failure rather
than a runtime panic with the hypothesis left undischarged.  (`decide` is
not usable -- `Array.map` is not kernel-reducible.) -/
theorem old_getmask_compiles : compilesOk old_getmask_designCert = true := by
  native_decide

/-- The theorem, by direct instantiation.  No per-design proof script. -/
theorem old_getmask_step_correct : ∀ inp st,
    old_getmask_step inp st = interpretDesign old_getmask_designCert inp st :=
  compileAndRun_correct old_getmask_designCert old_getmask_compiles

/-- For evaluation only.  Deliberately NOT mentioned in any theorem
statement -- see the comment above. -/
def old_getmask_residual : ResidualProgram :=
  match compileDesign old_getmask_designCert with
  | .ok R    => R
  | .error _ => default

#print axioms old_getmask_step_correct

-- Emitted by pass.lean in `formal.lean.mode=verified_compiler`.
-- This file contains NO semantic model and NO proof script: the compiler
-- `Compiler.compileDesign` is proved correct once, for every accepted design,
-- by `Compiler.compileDesign_correct`.  Slots are dense: sources occupy
-- 0..1 and node i occupies 2+i.

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

open Compiler

def new_getmask_designCert : DesignCert :=
  {
    sources  := #[
        SourceDesc.const 8 ((Int.ofNat 255))
      , SourceDesc.input 0 8
      ]
    nodes    := #[
        { op := LGraphOp.Op_GetMask, width := 8, deps := #[1, 0], origin := 16 }
      ]
    outputs  := #[
        { slot := 2, width := 8 }
      ]
    flops    := #[]
    memories := #[]
  }

/-- Compile-and-run.  The model IS the verified compiler applied to this
certificate -- there is no separately emitted model to disagree with it. -/
def new_getmask_step : RuntimeInput → RuntimeState → RuntimeResult :=
  compileAndRun new_getmask_designCert

/-- The whole per-design obligation: ONE boolean check.

`native_decide`, not `.get!`: a compile failure is a BUILD failure rather
than a runtime panic with the hypothesis left undischarged.  (`decide` is
not usable -- `Array.map` is not kernel-reducible.) -/
theorem new_getmask_compiles : compilesOk new_getmask_designCert = true := by
  native_decide

/-- The theorem, by direct instantiation.  No per-design proof script. -/
theorem new_getmask_step_correct : ∀ inp st,
    new_getmask_step inp st = interpretDesign new_getmask_designCert inp st :=
  compileAndRun_correct new_getmask_designCert new_getmask_compiles

/-- For evaluation only.  Deliberately NOT mentioned in any theorem
statement -- see the comment above. -/
def new_getmask_residual : ResidualProgram :=
  match compileDesign new_getmask_designCert with
  | .ok R    => R
  | .error _ => default

#print axioms new_getmask_step_correct

-- Universal input equality for the only fixture whose generated text changed.
theorem mask_fast_preserved (a : BitVec 8) :
  (old_getmask_Lgraph.old_getmask_comb ⟨a⟩).out_y =
  (new_getmask_Lgraph.new_getmask_comb ⟨a⟩).out_y := by rfl

theorem mask_source_preserved (a : BitVec 8) (n : Nat) :
  old_getmask_Lgraph.old_getmask_sourceEnv ⟨a⟩ n =
  new_getmask_Lgraph.new_getmask_sourceEnv ⟨a⟩ n := by rfl

theorem mask_interpreter_preserved (i : RuntimeInput) (s : RuntimeState) :
  interpretDesign old_getmask_designCert i s =
  interpretDesign new_getmask_designCert i s := by
  have henv : srcEnv old_getmask_designCert i s = srcEnv new_getmask_designCert i s := by
    funext k
    cases k with
    | zero => rfl
    | succ k =>
      cases k with
      | zero => rfl
      | succ k => simp [srcEnv, old_getmask_designCert, new_getmask_designCert]
  unfold interpretDesign
  rw [henv]
  rfl

#print axioms mask_fast_preserved
#print axioms mask_source_preserved
#print axioms mask_interpreter_preserved
