// This file is distributed under the BSD 3-Clause License. See LICENSE for details.

// sim.tune support tables (sim_profile.md §6.1 / §8.1): the executable color
// root's `<stem>.tune.cpp`.
//
// The profiler (drv.bin, inou/prp/prp_sim.cpp) samples consecutive-period
// PAIRS. For each pair it hashes every support source twice with
// `__tune_sources`, builds the activity mask A = OR of the buckets of the
// sources whose word changed, and counts class c as idle when
// (class_bits[c] & A) == 0 -- the GE a dirty-gated schedule could skip.
//
// Everything written here is a pure function of the design and of the plan's
// pre-fence structure (Color_plan::support() / occurrences()), never of the
// tune vector: flipping sim.tune.dirty / fence / live_words / backend leaves
// the file byte-identical, so File_output keeps its mtime and the host build
// does not recompile it.

#include <algorithm>
#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

#include "absl/strings/str_cat.h"
#include "cgen_sim.hpp"
#include "sim_color_plan.hpp"

namespace {

// Statements per cold lambda in __tune_sources. Deliberately far below the
// 2000 chunk_cold_members (cgen_sim.cpp) gives the other cold walkers: every
// statement here is a call plus a store, and the AArch64 Machine InstCombiner
// is superlinear in one function's size even under optnone. MEASURED on XS Rob
// (Verilog, 162,847 sources, Apple clang, -O2): 2000 -> 33.6 s for this TU
// (28.5 s of it that one pass), 1000 -> 15.0 s, 500 -> 7.9 s, 200 -> 5.8 s,
// 128 -> 5.3 s, 64 -> 5.1 s, of which 1.2 s is parsing Rob.hpp.
constexpr size_t kTuneSourceChunk = 128;

// Values per line in the emitted tables.
constexpr size_t kTuneValuesPerLine = 16;

std::string c_string_literal(std::string_view text) {
  std::string out = "\"";
  for (const char c : text) {
    const auto u = static_cast<unsigned char>(c);
    if (c == '"' || c == '\\') {
      out += '\\';
      out += c;
    } else if (u < 0x20 || u >= 0x7f) {
      // Octal, always three digits: a hex escape would swallow a following
      // hex-digit character.
      out += '\\';
      out += static_cast<char>('0' + ((u >> 6) & 7));
      out += static_cast<char>('0' + ((u >> 3) & 7));
      out += static_cast<char>('0' + (u & 7));
    } else {
      out += c;
    }
  }
  out += '"';
  return out;
}

// `constexpr <type> <name>[] = {...};` for a non-empty table. Returns the name
// the __lhd_tune_support initializer should use: `nullptr` for an empty table
// (a zero-length array is ill-formed).
template <class Values, class Format>
std::string append_table(File_output& out, std::string_view type, std::string_view name, const Values& values, Format format) {
  if (values.empty()) {
    return "nullptr";
  }
  out.append("constexpr ", type, " ", name, "[] = {\n");
  std::string line;
  size_t      in_line = 0;
  for (const auto& value : values) {
    if (in_line == 0) {
      line = "    ";
    }
    line += format(value);
    line += ",";
    if (++in_line == kTuneValuesPerLine) {
      line += "\n";
      out.append(line);
      in_line = 0;
    } else {
      line += " ";
    }
  }
  if (in_line != 0) {
    line.back() = '\n';
    out.append(line);
  }
  out.append("};\n");
  return std::string(name);
}

}  // namespace

void Cgen_sim::emit_tune_support(hhds::Graph* g, std::string_view fstem, std::string_view mod, const Tune_site_member& state_member,
                                 const Tune_site_member& sub_member) {
  using Plan   = livehd::sim::Color_plan;
  using Source = Plan::Support_source;

  auto out = open_out(absl::StrCat(fstem, ".tune.cpp"));

  // An unavailable support (a cyclic version DAG; the plan failed) still emits
  // a well-formed table: zero sources and classes, an empty hasher. The driver
  // then falls back to the per-def walker statistics.
  static const Plan::Support                 no_support;
  static const std::vector<Plan::Occurrence> no_occurrences;
  const bool                                 have_plan = color_plan_ != nullptr;
  const auto& support     = have_plan && color_plan_->support().available ? color_plan_->support() : no_support;
  const auto& occurrences = have_plan ? color_plan_->occurrences() : no_occurrences;
  const auto  occs        = static_cast<uint32_t>(occurrences.size());

  out->append("// Generated by inou.cgen.sim (LiveHD). Do not edit.\n");
  out->append("// sim.tune support table of `", mod, "` (sim_profile.md §6.1/§8.1): the plan's pre-fence\n");
  out->append("// single-period fan-in classes, and the hasher that writes one canonical word per\n");
  out->append("// support source. Tune-vector invariant by construction.\n");
  out->append(absl::StrCat("#include \"", fstem, ".hpp\"\n\n"));
  out->append(absl::StrCat("// words=",
                           support.words,
                           " sources=",
                           support.sources.size(),
                           " exact=",
                           support.exact ? "true" : "false",
                           " classes=",
                           support.classes.size(),
                           " occurrences=",
                           occs,
                           " total-ge=",
                           support.total_ge,
                           " total-sites=",
                           support.total_sites,
                           " total-cost=",
                           support.total_cost,
                           " total-cost-flat=",
                           support.total_cost_flat,
                           " fold-classes=",
                           support.fold_classes,
                           " fold-members=",
                           support.fold_members,
                           " fold-ge=",
                           support.fold_ge,
                           " fold-sites=",
                           support.fold_sites,
                           " fold-cost=",
                           support.fold_cost,
                           " fold-cost-flat=",
                           support.fold_cost_flat,
                           support.available ? "" : " (support unavailable)",
                           "\n"));
  // A NAMED per-module namespace, not an anonymous one: `lhd sim` batches small
  // translation units into unity TUs (lhd_kernel_sim.cpp), and two modules'
  // tables under the same anonymous-namespace names would be redefinitions
  // there. `mod` is the module's C++ class name, so it is unique per design.
  const std::string ns = absl::StrCat("__lhd_ts_", mod);
  out->append("namespace ", ns, " {\n");

  const auto hex64 = [](uint64_t value) { return absl::StrCat("0x", absl::Hex(value, absl::kZeroPad16), "ULL"); };
  const auto dec64 = [](uint64_t value) { return absl::StrCat(value, "ULL"); };
  const auto dec32 = [](uint32_t value) { return absl::StrCat(value, "u"); };

  std::vector<uint64_t> class_ge;
  std::vector<uint64_t> class_sites;
  std::vector<uint64_t> class_cost;
  std::vector<uint64_t> class_cost_flat;
  std::vector<uint32_t> class_occ;
  class_ge.reserve(support.classes.size());
  class_sites.reserve(support.classes.size());
  class_cost.reserve(support.classes.size());
  class_cost_flat.reserve(support.classes.size());
  class_occ.reserve(support.classes.size());
  for (const auto& cls : support.classes) {
    class_ge.push_back(cls.ge);
    class_sites.push_back(cls.sites);
    class_cost.push_back(cls.cost);
    class_cost_flat.push_back(cls.cost_flat);
    class_occ.push_back(cls.occurrence);
  }
  std::vector<uint32_t> source_bucket;
  std::vector<uint32_t> source_occ;
  source_bucket.reserve(support.sources.size());
  source_occ.reserve(support.sources.size());
  for (const auto& source : support.sources) {
    source_bucket.push_back(source.bucket);
    source_occ.push_back(source.occurrence);
  }
  std::vector<std::string> occ_path;
  std::vector<std::string> occ_def;
  std::vector<uint64_t>    occ_ge;
  std::vector<uint64_t>    occ_cost;
  for (const auto& occurrence : occurrences) {
    occ_path.push_back(c_string_literal(occurrence.path));
    occ_def.push_back(c_string_literal(occurrence.def));
    occ_ge.push_back(occurrence.ge);
    occ_cost.push_back(occurrence.cost);
  }
  const auto same = [](const std::string& text) { return text; };
  // The initializer below sits outside `ns`: name each table through it.
  const auto qualified = [&](std::string name) { return name == "nullptr" ? name : absl::StrCat(ns, "::", name); };

  const auto class_bits_name    = qualified(append_table(*out, "std::uint64_t", "__lhd_ts_class_bits", support.class_bits, hex64));
  const auto class_ge_name      = qualified(append_table(*out, "std::uint64_t", "__lhd_ts_class_ge", class_ge, dec64));
  const auto class_occ_name     = qualified(append_table(*out, "std::uint32_t", "__lhd_ts_class_occ", class_occ, dec32));
  const auto source_bucket_name = qualified(append_table(*out, "std::uint32_t", "__lhd_ts_source_bucket", source_bucket, dec32));
  const auto source_occ_name    = qualified(append_table(*out, "std::uint32_t", "__lhd_ts_source_occ", source_occ, dec32));
  const auto occ_path_name      = qualified(append_table(*out, "const char* const", "__lhd_ts_occ_path", occ_path, same));
  const auto occ_def_name       = qualified(append_table(*out, "const char* const", "__lhd_ts_occ_def", occ_def, same));
  const auto occ_ge_name        = qualified(append_table(*out, "std::uint64_t", "__lhd_ts_occ_ge", occ_ge, dec64));
  const auto class_sites_name     = qualified(append_table(*out, "std::uint64_t", "__lhd_ts_class_sites", class_sites, dec64));
  const auto class_cost_name      = qualified(append_table(*out, "std::uint64_t", "__lhd_ts_class_cost", class_cost, dec64));
  const auto class_cost_flat_name = qualified(append_table(*out, "std::uint64_t", "__lhd_ts_class_cost_flat", class_cost_flat, dec64));
  const auto occ_cost_name        = qualified(append_table(*out, "std::uint64_t", "__lhd_ts_occ_cost", occ_cost, dec64));

  // An opaque source (a compact loop, an opaque call) is the instance's whole
  // walked state folded into ONE word: its per-def walker (__tune_count /
  // __tune_hash, emitted for every module and loop wrapper) writes the words,
  // and any change among them marks the source active.
  const bool any_opaque = std::ranges::any_of(support.sources, [](const Source& s) { return s.kind == Source::Kind::opaque; });
  if (any_opaque) {
    out->append(
        "template <class T>\n"
        "std::uint64_t __lhd_ts_opaque(const T& __o) {\n"
        "  thread_local std::vector<std::uint64_t> __w;\n"
        "  __w.assign(__o.__tune_count(), 0);\n"
        "  std::uint64_t* __p = __w.data();\n"
        "  __o.__tune_hash(__p);\n"
        "  std::uint64_t __h = __w.size();\n"
        "  for (const std::uint64_t __x : __w) __h = __lhd_tune_fold(__h, __x);\n"
        "  return __h;\n"
        "}\n");
  }
  out->append("}  // namespace ", ns, "\n\n");

  out->append("const __lhd_tune_support& ", mod, "::__tune_support() {\n");
  out->append("  static const __lhd_tune_support __s{\n");
  out->append(absl::StrCat("      .words         = ", support.words, "u,\n"));
  out->append(absl::StrCat("      .sources       = ", support.sources.size(), "u,\n"));
  out->append(absl::StrCat("      .classes       = ", support.classes.size(), "u,\n"));
  out->append(absl::StrCat("      .occs          = ", occs, "u,\n"));
  out->append(absl::StrCat("      .exact         = ", support.exact ? "true" : "false", ",\n"));
  out->append(absl::StrCat("      .total_ge      = ", support.total_ge, "ULL,\n"));
  out->append("      .class_bits    = ", class_bits_name, ",\n");
  out->append("      .class_ge      = ", class_ge_name, ",\n");
  out->append("      .class_occ     = ", class_occ_name, ",\n");
  out->append("      .source_bucket = ", source_bucket_name, ",\n");
  out->append("      .source_occ    = ", source_occ_name, ",\n");
  out->append("      .occ_path      = ", occ_path_name, ",\n");
  out->append("      .occ_def       = ", occ_def_name, ",\n");
  out->append("      .occ_ge        = ", occ_ge_name, ",\n");
  out->append(absl::StrCat("      .total_sites     = ", support.total_sites, "ULL,\n"));
  out->append(absl::StrCat("      .total_cost      = ", support.total_cost, "ULL,\n"));
  out->append(absl::StrCat("      .total_cost_flat = ", support.total_cost_flat, "ULL,\n"));
  out->append("      .class_sites     = ", class_sites_name, ",\n");
  out->append("      .class_cost      = ", class_cost_name, ",\n");
  out->append("      .class_cost_flat = ", class_cost_flat_name, ",\n");
  out->append("      .occ_cost        = ", occ_cost_name, ",\n");
  out->append("  };\n  return __s;\n}\n\n");

  // The hasher: EXACTLY support.sources.size() words, in source order. A source
  // the root cannot name (no C++ member) writes a constant 0 -- it never reads
  // as active, and the word count, which the driver trusts, stays exact.
  const auto root_input_field = [&](uint32_t port) -> std::string {
    const auto io = g->get_io();
    if (!io) {
      return {};
    }
    for (const auto& decl : io->get_input_pin_decls()) {
      if (decl.port_id == port) {
        return cpp_port_path(decl.name);
      }
    }
    return {};
  };
  std::vector<std::string> statements;
  statements.reserve(support.sources.size());
  for (const auto& source : support.sources) {
    std::string value;
    switch (source.kind) {
      case Source::Kind::state: {
        const auto member = state_member(color_plan_->sites()[source.site]);
        if (!member.empty()) {
          value = absl::StrCat("__lhd_tune_h(", member, ")");
        }
        break;
      }
      case Source::Kind::opaque: {
        const auto member = sub_member(color_plan_->sites()[source.site]);
        if (!member.empty()) {
          value = absl::StrCat(ns, "::__lhd_ts_opaque(", member, ")");
        }
        break;
      }
      case Source::Kind::top_input: {
        const auto field = root_input_field(source.port);
        if (!field.empty()) {
          value = absl::StrCat("__lhd_tune_h(__in.", field, ")");
        }
        break;
      }
    }
    statements.push_back(value.empty() ? std::string("*__lhd_to++ = 0;  // no C++ member")
                                       : absl::StrCat("*__lhd_to++ = ", value, ";"));
  }

  out->append("LHD_SIM_COLD void ", mod, "::__tune_sources(std::uint64_t* __lhd_to) const {\n");
  if (statements.empty()) {
    out->append("  (void)__lhd_to;\n");
  } else if (statements.size() <= kTuneSourceChunk) {
    for (const auto& statement : statements) {
      out->append("  ", statement, "\n");
    }
  } else {
    for (size_t first = 0; first < statements.size(); first += kTuneSourceChunk) {
      out->append("  [&]() LHD_SIM_COLD {\n");
      const size_t last = std::min(statements.size(), first + kTuneSourceChunk);
      for (size_t i = first; i < last; ++i) {
        out->append("    ", statements[i], "\n");
      }
      out->append("  }();\n");
    }
  }
  out->append("}\n");
}
