# This file is distributed under the BSD 3-Clause License. See LICENSE for details.

filegroup(
    name = "cgen_memory_rtl",
    srcs = glob([
        "rtl/cgen_memory*.v",
    ]),
    visibility = ["//visibility:public"],
)
