/* Generated by Yosys livehd+0.9+ */

module top(out, out5);
  wire [3:0] \%out5_0 ;
  wire [4:0] \%out_0 ;
  wire [2:0] lg_0;
  wire [1:0] lg_1;
  wire [2:0] lg_2;
  wire [3:0] lg_3;
  wire [5:0] lg_4;
  wire [5:0] lg_5;
  output [4:0] out;
  output [3:0] out5;
  sum \___b_0:tmp_0:sum  (
    .\a.bar (lg_2),
    .\a.foo (lg_0),
    .b(lg_3),
    .\sout.o1.baz (lg_4),
    .sout2(lg_5)
  );
  assign \%out_0  = $signed(lg_1) + $signed(lg_4);
  assign \%out5_0  = $signed(lg_1) + $signed(lg_5);
  assign lg_0 = 3'h3;
  assign lg_1 = 2'h1;
  assign lg_2 = 3'h2;
  assign lg_3 = 4'h4;
  assign out = \%out_0 ;
  assign out5 = \%out5_0 ;
endmodule
/* Generated by Yosys livehd+0.9+ */

module sum(\a.foo , \a.bar , b, \sout.o1.baz , sout2);
  wire [5:0] \%sout2_0 ;
  wire [5:0] ___f_0;
  input [2:0] \a.bar ;
  input [1:0] \a.foo ;
  input [3:0] b;
  wire [2:0] lg_0;
  wire [3:0] lg_1;
  wire [4:0] lg_2;
  output [5:0] \sout.o1.baz ;
  output [5:0] sout2;
  assign ___f_0 = lg_0 + lg_2;
  assign \%sout2_0  = lg_1 + lg_2;
  assign \sout.o1.baz  = ___f_0;
  assign sout2 = \%sout2_0 ;
  assign lg_0 = { 1'h0, \a.foo  };
  assign lg_1 = { 1'h0, \a.bar  };
  assign lg_2 = { 1'h0, b };
endmodule
