/* Generated by Yosys livehd+0.9+ */

module top(out, out5);
  wire [2:0] lg_0;
  wire [2:0] lg_1;
  wire [3:0] lg_2;
  wire [3:0] lg_3;
  wire [3:0] lg_4;
  output [3:0] out;
  output [3:0] out5;
  sum \___b_0:tmp_0:sum  (
    .\a.bar (lg_1),
    .\a.foo (lg_0),
    .b(lg_2),
    .\sout.o1.baz (lg_4),
    .sout2(lg_3)
  );
  assign lg_0 = 3'h3;
  assign lg_1 = 3'h2;
  assign lg_2 = 4'h4;
  assign out = lg_4;
  assign out5 = lg_3;
endmodule
/* Generated by Yosys livehd+0.9+ */

module sum(\a.foo , \a.bar , b, sout2, \sout.o1.baz );
  wire [3:0] \%sout2_0 ;
  wire [3:0] ___f_0;
  input [2:0] \a.bar ;
  input [1:0] \a.foo ;
  input [3:0] b;
  wire [2:0] lg_0;
  wire [3:0] lg_1;
  wire [4:0] lg_2;
  output [5:0] \sout.o1.baz ;
  output [5:0] sout2;
  assign ___f_0 = lg_0 + lg_2;
  assign \%sout2_0  = lg_1 + lg_2;
  assign sout2 = { 2'h0, \%sout2_0  };
  assign \sout.o1.baz  = { 2'h0, ___f_0 };
  assign lg_0 = { 1'h0, \a.foo  };
  assign lg_1 = { 1'h0, \a.bar  };
  assign lg_2 = { 1'h0, b };
endmodule
