/* Generated by Yosys livehd+0.9+ */

module tuple_reg(clock, en, \out.cnt );
  reg [4:0] \#reg.cnt ;
  wire [5:0] ___f_0;
  input clock;
  input en;
  wire [1:0] lg_0;
  wire lg_1;
  wire [4:0] lg_11;
  wire [4:0] lg_2;
  wire [1:0] lg_3;
  wire [4:0] lg_4;
  wire [4:0] lg_5;
  wire lg_9;
  output [4:0] \out.cnt ;
  assign lg_9 = lg_3 & 32'd1;
  assign lg_2 = lg_9 ? lg_4 : lg_11;
  always @(posedge clock)
    \#reg.cnt  <= lg_2;
  assign ___f_0 = $signed(lg_0) + $signed(\#reg.cnt );
  assign lg_4 = $signed(___f_0) & $signed(lg_5);
  assign lg_0 = 2'h1;
  assign lg_1 = 1'h0;
  assign lg_5 = 5'h0f;
  assign \out.cnt  = \#reg.cnt ;
  assign lg_3 = { 1'h0, en };
  assign lg_11 = { lg_1, lg_1, lg_1, lg_1, lg_1 };
endmodule
