/* Generated by Yosys livehd+0.9+ */

module tuple_reg2(clock, reset, out, out2, out3, out4, out5);
  reg [6:0] \#reg.baz ;
  reg [6:0] \#reg.foo.bar ;
  input clock;
  input reset;
  wire [4:0] lg_0;
  wire [6:0] lg_1;
  wire [6:0] lg_2;
  output [4:0] out;
  output [6:0] out2;
  output [6:0] out3;
  output [6:0] out4;
  output [6:0] out5;
  always @(posedge clock) begin
    if (reset) begin
      \#reg.baz  <= 'h0;
    end else begin
    \#reg.baz  <= lg_2;
    end
  end
  always @(posedge clock) begin
    if (reset) begin
      \#reg.foo.bar  <= 'h0;
    end else begin
    \#reg.foo.bar  <= lg_1;
    end
  end
  assign lg_0 = 5'h0c;
  assign lg_1 = 7'h38;
  assign lg_2 = 7'h39;
  assign out = lg_0;
  assign out2 = \#reg.foo.bar ;
  assign out3 = \#reg.baz ;
  assign out4 = \#reg.foo.bar ;
  assign out5 = 7'd57;
endmodule
