(*  pass.isabelle shared helpers
    Generated by hand and reused by every <top>_Lgraph.thy emitted by pass.isabelle.

    Every helper here is total: no partial functions, no undefined cases.
    Every helper is explicitly typed; type variables are resolved by call-site
    annotations the pass emits (e.g. :: 64 word).
*)

theory SemanticPrimitives
  imports "HOL-Library.Word"
begin

(*--------------------------------------------------------------------*)
(* sem_udiv : total unsigned word division (b = 0 -> 0)               *)
(*--------------------------------------------------------------------*)

definition sem_udiv :: "'a::len word => 'a word => 'a word" where
  "sem_udiv a b = (if b = 0 then 0 else a div b)"

lemma sem_udiv_nonzero:
  "b ~= 0 ==> sem_udiv a b = a div b"
  by (simp add: sem_udiv_def)

(*--------------------------------------------------------------------*)
(* trunc_div_int : Verilog-style truncate-toward-zero on int          *)
(*                 distinct from Isabelle's bare int div (floor)      *)
(*--------------------------------------------------------------------*)

definition trunc_div_int :: "int => int => int" where
  "trunc_div_int a b =
     (let q = abs a div abs b
      in if (a < 0) ~= (b < 0) then - q else q)"

(*--------------------------------------------------------------------*)
(* sem_sdiv : total truncate-toward-zero signed word division         *)
(*--------------------------------------------------------------------*)

definition sem_sdiv :: "'a::len word => 'a word => 'a word" where
  "sem_sdiv a b =
     (if b = 0 then 0
      else word_of_int (trunc_div_int (sint a) (sint b)))"

lemma sem_sdiv_nonzero:
  "b ~= 0 ==>
   sem_sdiv a b = word_of_int (trunc_div_int (sint a) (sint b))"
  by (simp add: sem_sdiv_def)

(*--------------------------------------------------------------------*)
(* sem_sra : arithmetic right shift                                   *)
(*--------------------------------------------------------------------*)

definition sem_sra :: "'a::len word => 'n::len word => 'a word" where
  "sem_sra x n = word_of_int (sint x div 2 ^ unat n)"

(*--------------------------------------------------------------------*)
(* sem_ror_bool : n-ary OR-reduce; mixed input widths handled by      *)
(*   lifting each operand to bool (~= 0) before disjunction.          *)
(*--------------------------------------------------------------------*)

definition sem_ror_bool :: "bool list => 1 word" where
  "sem_ror_bool bs = (if list_ex id bs then 1 else 0)"

(*--------------------------------------------------------------------*)
(* bit_mask_at : single-bit mask at position i, materialized at the   *)
(*               caller's word type 'a; out-of-range positions yield 0*)
(*--------------------------------------------------------------------*)

definition bit_mask_at :: "nat => 'a::len word" where
  "bit_mask_at i = push_bit i (1 :: 'a word)"

(*--------------------------------------------------------------------*)
(* mask_indices : positions where bit m i is set, ascending order     *)
(*--------------------------------------------------------------------*)

definition mask_indices :: "'m::len word => nat list" where
  "mask_indices m = filter (%i. bit m i) [0..<LENGTH('m)]"

(*--------------------------------------------------------------------*)
(* pack_low : pack the bits of x at positions is into the low bits    *)
(*            of a word of width 'b; head of is becomes the highest   *)
(*            packed bit                                              *)
(*--------------------------------------------------------------------*)

primrec pack_low :: "'a::len word => nat list => 'b::len word" where
  "pack_low x [] = 0"
| "pack_low x (i # is) =
     or (push_bit (length is) (if bit x i then (1 :: 'b word) else 0))
        (pack_low x is)"

(*--------------------------------------------------------------------*)
(* sem_get_mask : extract bits selected by mask, packed into low bits *)
(*                of a word of width 'b (caller-resolved type)        *)
(*--------------------------------------------------------------------*)

definition sem_get_mask :: "'a::len word => 'm::len word => 'b::len word" where
  "sem_get_mask x m = pack_low x (rev (mask_indices m))"

(*--------------------------------------------------------------------*)
(* sem_set_mask : write bits of value into positions selected by      *)
(*                mask in a; out-of-range mask bits ignored           *)
(*--------------------------------------------------------------------*)

definition sem_set_mask
  :: "'a::len word => 'm::len word => 'v::len word => 'a word" where
  "sem_set_mask a m v =
     fold
       (%p acc.
          let j    = fst p;
              i    = snd p;
              mbit = (bit_mask_at i :: 'a word)
          in if bit v j then or acc mbit
             else and acc (not mbit))
       (zip [0..<length (mask_indices m)] (mask_indices m))
       a"

(*--------------------------------------------------------------------*)
(* sem_shl_many : reference-only n-ary multi-shift-OR                 *)
(*--------------------------------------------------------------------*)

definition sem_shl_many
  :: "'a::len word => 'b::len word list => 'a word" where
  "sem_shl_many x bs = foldr (%b acc. or (push_bit (unat b) x) acc) bs 0"

(*--------------------------------------------------------------------*)
(* flop_next : DFF positive-edge update                               *)
(*--------------------------------------------------------------------*)

definition flop_next ::
    "bool => 'w::len word => bool => 'w word => 'w word => 'w word" where
  "flop_next reset_active initial_value enable_active din current =
     (if reset_active then initial_value
      else if enable_active then din
      else current)"

(*--------------------------------------------------------------------*)
(* Function-valued memories and SRAM policy helpers                   *)
(*--------------------------------------------------------------------*)

type_synonym ('a, 'd) mem = "'a word => 'd word"

definition mem_read :: "('a::len, 'd::len) mem => 'a word => 'd word" where
  "mem_read m a = m a"

definition mem_write ::
  "('a::len, 'd::len) mem => 'a word => 'd word => ('a, 'd) mem" where
  "mem_write m a v = m(a := v)"

definition byte_mask_word :: "nat => nat => 'd::len word" where
  "byte_mask_word byte_w byte_idx =
     push_bit (byte_idx * byte_w) (((push_bit byte_w 1 - 1) :: 'd word))"

definition byte_enable_mask ::
  "'be::len word => nat => 'd::len word" where
  "byte_enable_mask be byte_w =
     fold
       (%byte_idx acc.
          if bit be byte_idx
          then or acc (byte_mask_word byte_w byte_idx :: 'd word)
          else acc)
       [0..<LENGTH('be)]
       0"

definition masked_word_update ::
  "'d::len word => 'd word => 'be::len word => nat => 'd word" where
  "masked_word_update old new be byte_w =
     (let mask = (byte_enable_mask be byte_w :: 'd word)
      in or (and old (not mask)) (and new mask))"

definition mem_write_be ::
  "('a::len, 'd::len) mem => 'a word => 'd word => 'be::len word => nat => ('a, 'd) mem" where
  "mem_write_be m a v be byte_w =
     mem_write m a (masked_word_update (mem_read m a) v be byte_w)"

definition sram_1rw_read_first ::
  "bool => 'a::len word => 'd::len word => ('a, 'd) mem => ('a, 'd) mem * 'd word" where
  "sram_1rw_read_first we addr wdata m =
     (let rdata = mem_read m addr;
          m' = (if we then mem_write m addr wdata else m)
      in (m', rdata))"

definition sram_1rw_write_first ::
  "bool => 'a::len word => 'd::len word => ('a, 'd) mem => ('a, 'd) mem * 'd word" where
  "sram_1rw_write_first we addr wdata m =
     (let m' = (if we then mem_write m addr wdata else m)
      in (m', mem_read m' addr))"

definition sram_1rw_be_read_first ::
  "bool => 'a::len word => 'd::len word => 'be::len word => nat =>
   ('a, 'd) mem => ('a, 'd) mem * 'd word" where
  "sram_1rw_be_read_first we addr wdata be byte_w m =
     (let rdata = mem_read m addr;
          m' = (if we then mem_write_be m addr wdata be byte_w else m)
      in (m', rdata))"

definition sram_1rw_be_write_first ::
  "bool => 'a::len word => 'd::len word => 'be::len word => nat =>
   ('a, 'd) mem => ('a, 'd) mem * 'd word" where
  "sram_1rw_be_write_first we addr wdata be byte_w m =
     (let m' = (if we then mem_write_be m addr wdata be byte_w else m)
      in (m', mem_read m' addr))"

definition sram_1r1w_read_first ::
  "bool => 'a::len word => 'd::len word => 'a word =>
   ('a, 'd) mem => ('a, 'd) mem * 'd word" where
  "sram_1r1w_read_first we waddr wdata raddr m =
     (let rdata = mem_read m raddr;
          m' = (if we then mem_write m waddr wdata else m)
      in (m', rdata))"

definition sram_1r1w_write_first ::
  "bool => 'a::len word => 'd::len word => 'a word =>
   ('a, 'd) mem => ('a, 'd) mem * 'd word" where
  "sram_1r1w_write_first we waddr wdata raddr m =
     (let m' = (if we then mem_write m waddr wdata else m)
      in (m', mem_read m' raddr))"

definition sram_1r1w_be_read_first ::
  "bool => 'a::len word => 'd::len word => 'be::len word => nat => 'a word =>
   ('a, 'd) mem => ('a, 'd) mem * 'd word" where
  "sram_1r1w_be_read_first we waddr wdata be byte_w raddr m =
     (let rdata = mem_read m raddr;
          m' = (if we then mem_write_be m waddr wdata be byte_w else m)
      in (m', rdata))"

definition sram_1r1w_be_write_first ::
  "bool => 'a::len word => 'd::len word => 'be::len word => nat => 'a word =>
   ('a, 'd) mem => ('a, 'd) mem * 'd word" where
  "sram_1r1w_be_write_first we waddr wdata be byte_w raddr m =
     (let m' = (if we then mem_write_be m waddr wdata be byte_w else m)
      in (m', mem_read m' raddr))"

definition sram_sync_read_reg_next ::
  "bool => 'd::len word => 'd word => 'd word" where
  "sram_sync_read_reg_next ren read_value current =
     (if ren then read_value else current)"

end
