/* Generated by Yosys livehd+0.9+ */

(* src = "./inou/yosys/tests/simple_hier_test.v:5.1-7.10" *)
module leaf1(x, y);
  (* src = "./inou/yosys/tests/simple_hier_test.v:6.15-6.25" *)
  wire _0_;
  (* src = "./inou/yosys/tests/simple_hier_test.v:5.27-5.28" *)
  input [15:0] x;
  (* src = "./inou/yosys/tests/simple_hier_test.v:5.44-5.45" *)
  output [15:0] y;
  assign _0_ = ! (* src = "./inou/yosys/tests/simple_hier_test.v:6.15-6.25" *) x;
  assign y = _0_ ? (* src = "./inou/yosys/tests/simple_hier_test.v:6.14-6.38" *) x : 16'h0003;
endmodule

(* src = "./inou/yosys/tests/simple_hier_test.v:9.1-14.10" *)
module leaf2(x, y, sum);
  (* src = "./inou/yosys/tests/simple_hier_test.v:13.16-13.21" *)
  wire [15:0] _0_;
  (* src = "./inou/yosys/tests/simple_hier_test.v:9.60-9.63" *)
  output [15:0] sum;
  (* src = "./inou/yosys/tests/simple_hier_test.v:10.15-10.17" *)
  wire [15:0] wy;
  (* src = "./inou/yosys/tests/simple_hier_test.v:9.27-9.28" *)
  input [15:0] x;
  (* src = "./inou/yosys/tests/simple_hier_test.v:9.43-9.44" *)
  input [15:0] y;
  assign _0_ = x + (* src = "./inou/yosys/tests/simple_hier_test.v:13.16-13.21" *) y;
  assign sum = _0_ + (* src = "./inou/yosys/tests/simple_hier_test.v:13.16-13.26" *) wy;
  (* module_not_derived = 32'd1 *)
  (* src = "./inou/yosys/tests/simple_hier_test.v:11.9-11.30" *)
  leaf1 sub_l1 (
    .x(x),
    .y(wy)
  );
endmodule

(* top =  1  *)
(* src = "./inou/yosys/tests/simple_hier_test.v:16.1-27.10" *)
module simple_hier_test(testi, testo);
  (* src = "./inou/yosys/tests/simple_hier_test.v:25.18-25.25" *)
  wire [15:0] _0_;
  (* src = "./inou/yosys/tests/simple_hier_test.v:16.38-16.43" *)
  input [15:0] testi;
  (* src = "./inou/yosys/tests/simple_hier_test.v:16.59-16.64" *)
  output [15:0] testo;
  (* src = "./inou/yosys/tests/simple_hier_test.v:17.15-17.17" *)
  wire [15:0] w1;
  (* src = "./inou/yosys/tests/simple_hier_test.v:18.15-18.17" *)
  wire [15:0] w2;
  (* src = "./inou/yosys/tests/simple_hier_test.v:19.15-19.17" *)
  wire [15:0] w3;
  assign _0_ = w1 | (* src = "./inou/yosys/tests/simple_hier_test.v:25.18-25.25" *) w2;
  assign testo = _0_ | (* src = "./inou/yosys/tests/simple_hier_test.v:25.18-25.30" *) w3;
  (* module_not_derived = 32'd1 *)
  (* src = "./inou/yosys/tests/simple_hier_test.v:21.9-21.30" *)
  leaf1 l1 (
    .x(testi),
    .y(w1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./inou/yosys/tests/simple_hier_test.v:22.9-22.43" *)
  leaf2 l2 (
    .sum(w2),
    .x(testi),
    .y(testi)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./inou/yosys/tests/simple_hier_test.v:23.9-23.27" *)
  leaf1 l3 (
    .x(w1),
    .y(w3)
  );
endmodule
