/-
  Generated by LiveHD pass.lean.
  Fast executable model: emitted.
  Certificate model: emitted for the supported non-memory graph subset.
-/

import LeanSemanticPrimitives.Translation.OpBridge

open OpBridge

set_option linter.unusedVariables false
set_option linter.unusedSimpArgs false

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace add2_Lgraph

structure add2_in where
  in_a : BitVec 4
  in_b : BitVec 4
deriving Repr, Inhabited

structure add2_out where
  out_y : BitVec 4
deriving Repr, Inhabited

def add2_fv28 (i : add2_in) : BitVec 5 :=
  ((sem_get_mask i.in_b (BitVec.ofInt 5 (-1))) : BitVec 5)
def add2_fv24 (i : add2_in) : BitVec 5 :=
  ((sem_get_mask i.in_a (BitVec.ofInt 5 (-1))) : BitVec 5)
def add2_fv20 (i : add2_in) : BitVec 4 :=
  (((bv_zext (add2_fv24 i)) : BitVec 4) + ((bv_zext (add2_fv28 i)) : BitVec 4))
def add2_fv16 (i : add2_in) : BitVec 4 :=
  (((bv_zext (BitVec.ofInt 4 (15))) : BitVec 4) &&& ((bv_zext (add2_fv20 i)) : BitVec 4))

def add2_comb (i : add2_in) : add2_out :=
  { out_y := ((bv_zext (add2_fv16 i)) : BitVec 4) }

def add2_nodeCerts : List NodeCert := [
  { nid := 28, op := LGraphOp.Op_GetMask, width := 5, deps := [2000000001, 1000000000] },
  { nid := 24, op := LGraphOp.Op_GetMask, width := 5, deps := [2000000000, 1000000001] },
  { nid := 20, op := LGraphOp.Op_Sum 2, width := 4, deps := [24, 28] },
  { nid := 16, op := LGraphOp.Op_And, width := 4, deps := [1000000002, 20] }
]

def add2_sourceEnv (i : add2_in) : Nat -> BV := fun n =>
  if n = 1000000000 then mk_bv 5 ((-Int.ofNat 1)) else
  if n = 1000000001 then mk_bv 5 ((-Int.ofNat 1)) else
  if n = 1000000002 then mk_bv 4 ((Int.ofNat 15)) else
  if n = 2000000000 then mk_bv 4 (Int.ofNat (BitVec.toNat i.in_a)) else
  if n = 2000000001 then mk_bv 4 (Int.ofNat (BitVec.toNat i.in_b)) else
  mk_bv 0 0

def add2_graphCert : GraphCert :=
  { topo := [28, 24, 20, 16], sources := [1000000000, 1000000001, 1000000002, 2000000000, 2000000001], nodes := nodes_of_list add2_nodeCerts }

def add2_outputsFromCert (rho : Nat -> BV) : add2_out :=
  { out_y := (bv_to_bitvec 4 (rho 16)) }

def add2_comb_cert (i : add2_in) : add2_out :=
  add2_outputsFromCert (evalGraph add2_graphCert.topo add2_graphCert (add2_sourceEnv i))

theorem add2_comb_cert_refines_cert (i : add2_in) :
    add2_comb_cert i = add2_outputsFromCert (evalGraph add2_graphCert.topo add2_graphCert (add2_sourceEnv i)) := by
  rfl

theorem add2_evalGraph_correct (i : add2_in) :
    envCorrectOn add2_graphCert.topo
      (evalGraph add2_graphCert.topo add2_graphCert (add2_sourceEnv i))
      (graphDenotation add2_graphCert.topo add2_graphCert (add2_sourceEnv i)) := by
  exact evalGraphCorrectForCert add2_graphCert (add2_sourceEnv i)

-- graphCertWf proof emission is pending full graph certificate output.

-- Step-5 fast-view bridge: fast model = certificate model.

def add2_phi (i : add2_in) : Nat → BV := fun n =>
  if n = 28 then bvenc (add2_fv28 i) else
  if n = 24 then bvenc (add2_fv24 i) else
  if n = 20 then bvenc (add2_fv20 i) else
  if n = 16 then bvenc (add2_fv16 i) else
  add2_sourceEnv i n

theorem add2_src1000000000 (i : add2_in) : add2_sourceEnv i 1000000000 = bvenc (BitVec.ofInt 5 ((-Int.ofNat 1))) := by
  simp only [add2_sourceEnv]; norm_num; exact mk_bv_ofInt _
theorem add2_src1000000001 (i : add2_in) : add2_sourceEnv i 1000000001 = bvenc (BitVec.ofInt 5 ((-Int.ofNat 1))) := by
  simp only [add2_sourceEnv]; norm_num; exact mk_bv_ofInt _
theorem add2_src1000000002 (i : add2_in) : add2_sourceEnv i 1000000002 = bvenc (BitVec.ofInt 4 ((Int.ofNat 15))) := by
  simp only [add2_sourceEnv]; norm_num; exact mk_bv_ofInt _
theorem add2_src2000000000 (i : add2_in) : add2_sourceEnv i 2000000000 = bvenc (i.in_a) := by
  simp [add2_sourceEnv, bvenc]
theorem add2_src2000000001 (i : add2_in) : add2_sourceEnv i 2000000001 = bvenc (i.in_b) := by
  simp [add2_sourceEnv, bvenc]

theorem add2_bridge_nodup : add2_graphCert.topo.Nodup := by decide
theorem add2_bridge_some : ∀ n ∈ add2_graphCert.topo, (add2_graphCert.nodes n).isSome := by decide
theorem add2_bridge_depord : GraphRefine.DepOrdered add2_graphCert add2_graphCert.topo :=
  GraphRefine.depOrdered_of_bool add2_graphCert add2_graphCert.topo (by native_decide)

theorem add2_bridge_rec (i : add2_in) : ∀ n ∈ add2_graphCert.topo, add2_phi i n = evalNode add2_graphCert (add2_phi i) n := by
  have h_28 : add2_phi i 28 = evalNode add2_graphCert (add2_phi i) 28 := by
    show bvenc (add2_fv28 i) = eval_op (LGraphOp.Op_GetMask) 5 [add2_phi i 2000000001, add2_phi i 1000000000]
    simp only [add2_phi]
    norm_num
    rw [add2_src2000000001 i, add2_src1000000000 i, getmask_bridge' _ _ (by native_decide)]
    simp only [add2_fv28, Int.ofNat_eq_natCast, Nat.cast_ofNat, Nat.cast_one]
  have h_24 : add2_phi i 24 = evalNode add2_graphCert (add2_phi i) 24 := by
    show bvenc (add2_fv24 i) = eval_op (LGraphOp.Op_GetMask) 5 [add2_phi i 2000000000, add2_phi i 1000000001]
    simp only [add2_phi]
    norm_num
    rw [add2_src2000000000 i, add2_src1000000001 i, getmask_bridge' _ _ (by native_decide)]
    simp only [add2_fv24, Int.ofNat_eq_natCast, Nat.cast_ofNat, Nat.cast_one]
  have h_20 : add2_phi i 20 = evalNode add2_graphCert (add2_phi i) 20 := by
    show bvenc (add2_fv20 i) = eval_op (LGraphOp.Op_Sum 2) 4 [add2_phi i 24, add2_phi i 28]
    simp only [add2_phi]
    norm_num
    rw [sum2_bridge]
    simp only [add2_fv20, Int.ofNat_eq_natCast, Nat.cast_ofNat, Nat.cast_one]
  have h_16 : add2_phi i 16 = evalNode add2_graphCert (add2_phi i) 16 := by
    show bvenc (add2_fv16 i) = eval_op (LGraphOp.Op_And) 4 [add2_phi i 1000000002, add2_phi i 20]
    simp only [add2_phi]
    norm_num
    rw [add2_src1000000002 i, and_bridge]
    simp only [add2_fv16, Int.ofNat_eq_natCast, Nat.cast_ofNat, Nat.cast_one]
  intro n hn
  simp only [add2_graphCert, List.mem_cons, List.not_mem_nil, or_false] at hn
  rcases hn with h | h | h | h <;> subst h
  · exact h_28
  · exact h_24
  · exact h_20
  · exact h_16

theorem add2_bridge_src (i : add2_in) : ∀ n ∈ add2_graphCert.topo, ∀ d ∈ depopts_of add2_graphCert n, d ∉ add2_graphCert.topo → add2_sourceEnv i d = add2_phi i d := by
  intro n _ d _ hd
  simp only [add2_graphCert, List.mem_cons, List.not_mem_nil, or_false, not_or] at hd
  simp only [add2_phi, if_neg hd.1, if_neg hd.2.1, if_neg hd.2.2.1, if_neg hd.2.2.2]

theorem add2_comb_refines_fast (i : add2_in) : add2_comb i = add2_comb_cert i := by
  have hb := GraphRefine.evalGraph_of_localAgree add2_graphCert (add2_phi i) (add2_sourceEnv i)
    add2_bridge_nodup add2_bridge_depord add2_bridge_some (add2_bridge_rec i) (add2_bridge_src i)
  unfold add2_comb add2_comb_cert add2_outputsFromCert
  rw [hb 16 (by decide), show add2_phi i 16 = bvenc (add2_fv16 i) from by simp [add2_phi]]
  simp only [bv_to_bitvec_bvenc, bv_zext_id]

end add2_Lgraph
