/* Generated by Yosys 0.9+3582 (git sha1 de7997837, gcc 9.3.0-15 -fPIC -Os) */

module sky130_trivial(y, a, b, c);
  wire res0;
  input a;
  input b;
  input c;
  output y;
  sky130_fd_sc_hs__nand3b_1 inst1 (
    .A_N(c),
    .B(a),
    .C(b),
    .Y(res0)
  );
  sky130_fd_sc_hs__o21a_1 inst2 (
    .A1(b),
    .A2(a),
    .B1(res0),
    .X(y)
  );
endmodule
