cc_library(
    name = "meta",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    visibility = ["//visibility:public"],
    includes = ["."],
    deps = ["//core:core",
            "@boost//:filesystem", "@boost//:program_options", # SOON TO BE GONE
            ],
)

