`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module array_selfref_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [1:0] a_0;
  reg  [1:0] a_1;
  wire [1:0] z;
  \array_selfref.top  dut(.a_0(a_0), .a_1(a_1), .z(z));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a_0 = s & 64'd3;
      s=s*A+C; a_1 = s & 64'd3;
      #1;
      if (k>=0) begin
        sig = sig*P + (z & 64'd3);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
