`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module bitrange_open_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [15:0] a;
  wire [15:0] zfull;
  wire [10:0] zoff;
  wire [0:0] zmsb;
  \bitrange_open.osel  dut(.a(a), .zfull(zfull), .zoff(zoff), .zmsb(zmsb));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd65535;
      #1;
      if (k>=0) begin
        sig = sig*P + (zfull & 64'd65535);
        sig = sig*P + (zoff & 64'd2047);
        sig = sig*P + (zmsb & 64'd1);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
