`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module bitrange_dyn_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [15:0] a;
  reg  [3:0] base;
  reg  [2:0] len;
  wire [15:0] z;
  \bitrange_dyn.rsel  dut(.a(a), .base(base), .len(len), .z(z));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd65535;
      s=s*A+C; base = s & 64'd15;
      s=s*A+C; len = s & 64'd7;
      #1;
      if (k>=0) begin
        sig = sig*P + (z & 64'd65535);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
