`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module bitset_imm_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [31:0] i;
  wire [63:0] io_sextImm;
  wire [63:0] io_zext;
  wire [12:0] io_direct;
  \bitset_imm.foo  dut(.i(i), .io_sextImm(io_sextImm), .io_zext(io_zext), .io_direct(io_direct));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; i = s & 64'd4294967295;
      #1;
      if (k>=0) begin
        sig = sig*P + (io_sextImm & ~64'd0);
        sig = sig*P + (io_zext & ~64'd0);
        sig = sig*P + (io_direct & 64'd8191);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
