`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module bitset_mut_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] a;
  reg  [7:0] b;
  wire [11:0] o_cont;
  wire [11:0] o_over;
  wire [11:0] o_rev;
  wire [11:0] o_gap;
  \bitset_mut.foo  dut(.a(a), .b(b), .o_cont(o_cont), .o_over(o_over), .o_rev(o_rev), .o_gap(o_gap));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd255;
      s=s*A+C; b = s & 64'd255;
      #1;
      if (k>=0) begin
        sig = sig*P + (o_cont & 64'd4095);
        sig = sig*P + (o_over & 64'd4095);
        sig = sig*P + (o_rev & 64'd4095);
        sig = sig*P + (o_gap & 64'd4095);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
