`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module bitset_gap_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [31:0] i;
  wire [15:0] out_gap;
  wire [15:0] out_over;
  wire [12:0] out_rev;
  \bitset_gap.foo  dut(.i(i), .out_gap(out_gap), .out_over(out_over), .out_rev(out_rev));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; i = s & 64'd4294967295;
      #1;
      if (k>=0) begin
        sig = sig*P + (out_gap & 64'd65535);
        sig = sig*P + (out_over & 64'd65535);
        sig = sig*P + (out_rev & 64'd8191);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
