`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module comb_single_out_op_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] a;
  reg  [7:0] b;
  wire [9:0] s;
  wire [8:0] c;
  wire [9:0] d;
  wire [8:0] e;
  \comb_single_out_op.csout  dut(.a(a), .b(b), .s(s), .c(c), .d(d), .e(e));
  reg [63:0] s_, sig; integer k;
  initial begin
    s_=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s_=s_*A+C; a = s_ & 64'd255;
      s_=s_*A+C; b = s_ & 64'd255;
      #1;
      if (k>=0) begin
        sig = sig*P + (s & 64'd1023);
        sig = sig*P + (c & 64'd511);
        sig = sig*P + (d & 64'd1023);
        sig = sig*P + (e & 64'd511);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
