`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module condout_mixed_arms_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [0:0] s;
  reg  [1:0] a;
  wire [1:0] o;
  \condout_mixed_arms.mixedarm  dut(.s(s), .a(a), .o(o));
  reg [63:0] s_, sig; integer k;
  initial begin
    s_=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s_=s_*A+C; s = s_ & 64'd1;
      s_=s_*A+C; a = s_ & 64'd3;
      #1;
      if (k>=0) begin
        sig = sig*P + (o & 64'd3);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
