`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module dyn_tuple_mixed_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [1:0] sel;
  reg  [7:0] a;
  reg  [7:0] c;
  reg  [7:0] d;
  wire [7:0] z;
  \dyn_tuple_mixed.selm  dut(.sel(sel), .a(a), .c(c), .d(d), .z(z));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; sel = s & 64'd3;
      s=s*A+C; a = s & 64'd255;
      s=s*A+C; c = s & 64'd255;
      s=s*A+C; d = s & 64'd255;
      #1;
      if (k>=0) begin
        sig = sig*P + (z & 64'd255);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
