`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module flop_reset_matrix_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [0:0] reset_n;
  reg  [0:0] en;
  reg clock;
  reg reset;
  wire [7:0] q_pp;
  wire [7:0] q_pn;
  wire [7:0] q_ps;
  wire [7:0] q_np;
  wire [7:0] q_nn;
  wire [7:0] q_ns;
  \flop_reset_matrix.matrix  dut(.reset_n(reset_n), .en(en), .clock(clock), .reset(reset), .q_pp(q_pp), .q_pn(q_pn), .q_ps(q_ps), .q_np(q_np), .q_nn(q_nn), .q_ns(q_ns));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; reset_n = s & 64'd1;
      s=s*A+C; en = s & 64'd1;
      reset = (k<4) ? 1'b1 : 1'b0;
      #1 clock=1; #1;
      #1 clock=0; #1;
      if (k>=4) begin
        sig = sig*P + (q_pp & 64'd255);
        sig = sig*P + (q_pn & 64'd255);
        sig = sig*P + (q_ps & 64'd255);
        sig = sig*P + (q_np & 64'd255);
        sig = sig*P + (q_nn & 64'd255);
        sig = sig*P + (q_ns & 64'd255);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
