`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module generic_mod_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] x;
  reg  [7:0] y;
  reg  [15:0] w;
  reg  [15:0] v;
  wire [7:0] s8;
  wire [15:0] s16;
  \generic_mod.top  dut(.x(x), .y(y), .w(w), .v(v), .s8(s8), .s16(s16));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; x = s & 64'd255;
      s=s*A+C; y = s & 64'd255;
      s=s*A+C; w = s & 64'd65535;
      s=s*A+C; v = s & 64'd65535;
      #1;
      if (k>=0) begin
        sig = sig*P + (s8 & 64'd255);
        sig = sig*P + (s16 & 64'd65535);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
