`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module hier_value_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [3:0] in;
  wire [2:0] cnt;
  hval_popcnt dut(.in(in), .cnt(cnt));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; in = s & 64'd15;
      #1;
      if (k>=0) begin
        sig = sig*P + (cnt & 64'd7);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
