`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module if_expr_rhs_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [0:0] c;
  reg  [0:0] d;
  reg  [7:0] a;
  reg  [7:0] b;
  wire [7:0] o;
  wire [7:0] p;
  wire [7:0] q;
  \if_expr_rhs.ifsel  dut(.c(c), .d(d), .a(a), .b(b), .o(o), .p(p), .q(q));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; c = s & 64'd1;
      s=s*A+C; d = s & 64'd1;
      s=s*A+C; a = s & 64'd255;
      s=s*A+C; b = s & 64'd255;
      #1;
      if (k>=0) begin
        sig = sig*P + (o & 64'd255);
        sig = sig*P + (p & 64'd255);
        sig = sig*P + (q & 64'd255);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
