`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module implies_cond_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [0:0] req;
  reg  [0:0] ack;
  reg  [3:0] x;
  reg  [3:0] y;
  wire [0:0] grant;
  wire [3:0] sel;
  wire [0:0] same;
  \implies_cond.top  dut(.req(req), .ack(ack), .x(x), .y(y), .grant(grant), .sel(sel), .same(same));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; req = s & 64'd1;
      s=s*A+C; ack = s & 64'd1;
      s=s*A+C; x = s & 64'd15;
      s=s*A+C; y = s & 64'd15;
      #1;
      if (k>=0) begin
        sig = sig*P + (grant & 64'd1);
        sig = sig*P + (sel & 64'd15);
        sig = sig*P + (same & 64'd1);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
