`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module implies_ops_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [0:0] a;
  reg  [0:0] b;
  reg  [0:0] c;
  reg  [3:0] x;
  reg  [3:0] y;
  wire [0:0] out1;
  wire [0:0] out2;
  wire [0:0] out3;
  wire [0:0] out4;
  \implies_ops.top  dut(.a(a), .b(b), .c(c), .x(x), .y(y), .out1(out1), .out2(out2), .out3(out3), .out4(out4));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd1;
      s=s*A+C; b = s & 64'd1;
      s=s*A+C; c = s & 64'd1;
      s=s*A+C; x = s & 64'd15;
      s=s*A+C; y = s & 64'd15;
      #1;
      if (k>=0) begin
        sig = sig*P + (out1 & 64'd1);
        sig = sig*P + (out2 & 64'd1);
        sig = sig*P + (out3 & 64'd1);
        sig = sig*P + (out4 & 64'd1);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
