`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module mem_pending_sync_init_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [1:0] raddr;
  reg clock;
  wire [3:0] q;
  \mem_pending_sync_init.syncinit  dut(.raddr(raddr), .clock(clock), .q(q));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; raddr = s & 64'd3;
      #1 clock=1; #1;
      if (k>=32) begin
        sig = sig*P + (q & 64'd15);
      end
      #1 clock=0; #1;
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
