`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module mem_whole_coexist_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [79:0] inp;
  reg  [2:0] waddr;
  reg  [9:0] wdata;
  reg  [0:0] we;
  reg  [2:0] idx;
  reg clock;
  wire [9:0] r;
  wire [79:0] allout;
  \mem_whole_coexist.coexist  dut(.inp(inp), .waddr(waddr), .wdata(wdata), .we(we), .idx(idx), .clock(clock), .r(r), .allout(allout));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; inp = s & ~64'd0;
      s=s*A+C; waddr = s & 64'd7;
      s=s*A+C; wdata = s & 64'd1023;
      s=s*A+C; we = s & 64'd1;
      s=s*A+C; idx = s & 64'd7;
      #1 clock=1; #1;
      if (k>=32) begin
        sig = sig*P + (r & 64'd1023);
        sig = sig*P + (allout & ~64'd0);
      end
      #1 clock=0; #1;
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
