`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module mem_pending_reset_restore_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [3:0] a;
  reg  [0:0] i;
  reg  [0:0] we;
  reg clock;
  reg reset;
  wire [3:0] z;
  \mem_pending_reset_restore.restore  dut(.a(a), .i(i), .we(we), .clock(clock), .reset(reset), .z(z));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd15;
      s=s*A+C; i = s & 64'd1;
      s=s*A+C; we = s & 64'd1;
      reset = (k<4) ? 1'b1 : 1'b0;
      #1 clock=1; #1;
      #1 clock=0; #1;
      if (k>=4) begin
        sig = sig*P + (z & 64'd15);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
