`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module mod_three_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [3:0] a;
  reg  [15:0] w;
  wire [1:0] r4;
  wire [1:0] r16;
  \mod_three.foo  dut(.a(a), .w(w), .r4(r4), .r16(r16));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd15;
      s=s*A+C; w = s & 64'd65535;
      #1;
      if (k>=0) begin
        sig = sig*P + (r4 & 64'd3);
        sig = sig*P + (r16 & 64'd3);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
