`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module mod_call_pipe_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [15:0] in1;
  reg  [15:0] in2;
  reg clock;
  wire [31:0] out;
  \mod_call_pipe.top  dut(.in1(in1), .in2(in2), .clock(clock), .out(out));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; in1 = s & 64'd65535;
      s=s*A+C; in2 = s & 64'd65535;
      #1 clock=1; #1;
      if (k>=32) begin
        sig = sig*P + (out & 64'd4294967295);
      end
      #1 clock=0; #1;
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
