`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module mod_lower_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] a;
  reg  [2:0] c;
  wire [2:0] rp2;
  wire [5:0] rp2b;
  wire [2:0] rfit;
  wire [7:0] rfit_big;
  wire [0:0] rone;
  \mod_lower.foo  dut(.a(a), .c(c), .rp2(rp2), .rp2b(rp2b), .rfit(rfit), .rfit_big(rfit_big), .rone(rone));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd255;
      s=s*A+C; c = s & 64'd7;
      #1;
      if (k>=0) begin
        sig = sig*P + (rp2 & 64'd7);
        sig = sig*P + (rp2b & 64'd63);
        sig = sig*P + (rfit & 64'd7);
        sig = sig*P + (rfit_big & 64'd255);
        sig = sig*P + (rone & 64'd1);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
