`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module mod_comp_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] a;
  reg  [7:0] b;
  wire [3:0] rp2;
  wire [1:0] r3;
  \mod_comp.foo  dut(.a(a), .b(b), .rp2(rp2), .r3(r3));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd255;
      s=s*A+C; b = s & 64'd255;
      #1;
      if (k>=0) begin
        sig = sig*P + (rp2 & 64'd15);
        sig = sig*P + (r3 & 64'd3);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
