`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module mod_mux_aligned_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [0:0] sel;
  reg  [7:0] a;
  reg  [7:0] b;
  reg clock;
  wire [8:0] out;
  \mod_mux_aligned.pick  dut(.sel(sel), .a(a), .b(b), .clock(clock), .out(out));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; sel = s & 64'd1;
      s=s*A+C; a = s & 64'd255;
      s=s*A+C; b = s & 64'd255;
      #1 clock=1; #1;
      #1 clock=0; #1;
      if (k>=32) begin
        sig = sig*P + (out & 64'd511);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
