`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module overload_dispatch_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] x;
  reg  [7:0] y;
  reg  [7:0] z;
  wire [8:0] s2;
  wire [9:0] s3;
  \overload_dispatch.ovdispatch  dut(.x(x), .y(y), .z(z), .s2(s2), .s3(s3));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; x = s & 64'd255;
      s=s*A+C; y = s & 64'd255;
      s=s*A+C; z = s & 64'd255;
      #1;
      if (k>=0) begin
        sig = sig*P + (s2 & 64'd511);
        sig = sig*P + (s3 & 64'd1023);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
