`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module pipe2_two_out_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [3:0] a;
  reg  [3:0] b;
  reg clock;
  wire [7:0] x;
  wire [7:0] y;
  \pipe2_two_out.two  dut(.a(a), .b(b), .clock(clock), .x(x), .y(y));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd15;
      s=s*A+C; b = s & 64'd15;
      #1 clock=1; #1;
      if (k>=32) begin
        sig = sig*P + (x & 64'd255);
        sig = sig*P + (y & 64'd255);
      end
      #1 clock=0; #1;
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
