`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module reduce_or_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] a;
  reg  [7:0] b;
  wire [0:0] or_ur;
  wire [0:0] or_sr;
  wire [0:0] or_uf;
  wire [0:0] or_sf;
  \reduce_or.foo  dut(.a(a), .b(b), .or_ur(or_ur), .or_sr(or_sr), .or_uf(or_uf), .or_sf(or_sf));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd255;
      s=s*A+C; b = s & 64'd255;
      #1;
      if (k>=0) begin
        sig = sig*P + (or_ur & 64'd1);
        sig = sig*P + (or_sr & 64'd1);
        sig = sig*P + (or_uf & 64'd1);
        sig = sig*P + (or_sf & 64'd1);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
