`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module reduce_xor_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [15:0] a;
  reg  [15:0] b;
  wire [0:0] x2;
  wire [0:0] x4;
  wire [0:0] x3;
  wire [0:0] x5;
  wire [0:0] x7;
  wire [0:0] xf;
  wire [0:0] xs;
  wire [0:0] x1;
  \reduce_xor.foo  dut(.a(a), .b(b), .x2(x2), .x4(x4), .x3(x3), .x5(x5), .x7(x7), .xf(xf), .xs(xs), .x1(x1));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd65535;
      s=s*A+C; b = s & 64'd65535;
      #1;
      if (k>=0) begin
        sig = sig*P + (x2 & 64'd1);
        sig = sig*P + (x4 & 64'd1);
        sig = sig*P + (x3 & 64'd1);
        sig = sig*P + (x5 & 64'd1);
        sig = sig*P + (x7 & 64'd1);
        sig = sig*P + (xf & 64'd1);
        sig = sig*P + (xs & 64'd1);
        sig = sig*P + (x1 & 64'd1);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
