`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module reduce_popcount_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [15:0] a;
  reg  [15:0] b;
  wire [1:0] p2;
  wire [2:0] p4;
  wire [1:0] p3;
  wire [2:0] p5;
  wire [2:0] p7;
  wire [4:0] pf;
  wire [3:0] ps;
  wire [0:0] p1;
  \reduce_popcount.foo  dut(.a(a), .b(b), .p2(p2), .p4(p4), .p3(p3), .p5(p5), .p7(p7), .pf(pf), .ps(ps), .p1(p1));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd65535;
      s=s*A+C; b = s & 64'd65535;
      #1;
      if (k>=0) begin
        sig = sig*P + (p2 & 64'd3);
        sig = sig*P + (p4 & 64'd7);
        sig = sig*P + (p3 & 64'd3);
        sig = sig*P + (p5 & 64'd7);
        sig = sig*P + (p7 & 64'd7);
        sig = sig*P + (pf & 64'd31);
        sig = sig*P + (ps & 64'd15);
        sig = sig*P + (p1 & 64'd1);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
