`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module reg_hold_empty_elif_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [0:0] taken;
  reg  [0:0] stall;
  reg  [7:0] tgt;
  reg  [7:0] nx;
  reg clock;
  reg reset;
  wire [7:0] pc;
  \reg_hold_empty_elif.pcunit  dut(.taken(taken), .stall(stall), .tgt(tgt), .nx(nx), .clock(clock), .reset(reset), .pc(pc));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; taken = s & 64'd1;
      s=s*A+C; stall = s & 64'd1;
      s=s*A+C; tgt = s & 64'd255;
      s=s*A+C; nx = s & 64'd255;
      reset = (k<4) ? 1'b1 : 1'b0;
      #1 clock=1; #1;
      #1 clock=0; #1;
      if (k>=4) begin
        sig = sig*P + (pc & 64'd255);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
