`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module reg_hold_match_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [1:0] sel;
  reg  [7:0] a;
  reg  [7:0] b;
  reg clock;
  reg reset;
  wire [7:0] q;
  \reg_hold_match.selreg  dut(.sel(sel), .a(a), .b(b), .clock(clock), .reset(reset), .q(q));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; sel = s & 64'd3;
      s=s*A+C; a = s & 64'd255;
      s=s*A+C; b = s & 64'd255;
      reset = (k<4) ? 1'b1 : 1'b0;
      #1 clock=1; #1;
      if (k>=4) begin
        sig = sig*P + (q & 64'd255);
      end
      #1 clock=0; #1;
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
