`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module rt_bool_cast_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] a;
  reg  [7:0] b;
  wire [0:0] zb;
  wire [3:0] zc;
  \rt_bool_cast.rt_bool_cast  dut(.a(a), .b(b), .zb(zb), .zc(zc));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd255;
      s=s*A+C; b = s & 64'd255;
      #1;
      if (k>=0) begin
        sig = sig*P + (zb & 64'd1);
        sig = sig*P + (zc & 64'd15);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
