`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module rt_int_output_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [3:0] a;
  reg  [3:0] c;
  wire [5:0] zi;
  wire [5:0] zu;
  wire [4:0] zc;
  wire [9:0] zk;
  wire [8:0] zn;
  \rt_int_output.rt_int_output  dut(.a(a), .c(c), .zi(zi), .zu(zu), .zc(zc), .zk(zk), .zn(zn));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd15;
      s=s*A+C; c = s & 64'd15;
      #1;
      if (k>=0) begin
        sig = sig*P + (zi & 64'd63);
        sig = sig*P + (zu & 64'd63);
        sig = sig*P + (zc & 64'd31);
        sig = sig*P + (zk & 64'd1023);
        sig = sig*P + (zn & 64'd511);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
