`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module rt_typecast_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] a;
  reg  [7:0] b;
  reg  [3:0] c;
  wire [3:0] zi;
  wire [3:0] zu;
  wire [3:0] zs;
  wire [7:0] zc;
  wire [7:0] zd;
  \rt_typecast.rt_typecast  dut(.a(a), .b(b), .c(c), .zi(zi), .zu(zu), .zs(zs), .zc(zc), .zd(zd));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd255;
      s=s*A+C; b = s & 64'd255;
      s=s*A+C; c = s & 64'd15;
      #1;
      if (k>=0) begin
        sig = sig*P + (zi & 64'd15);
        sig = sig*P + (zu & 64'd15);
        sig = sig*P + (zs & 64'd15);
        sig = sig*P + (zc & 64'd255);
        sig = sig*P + (zd & 64'd255);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
