`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module rt_wrap_reassign_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [31:0] x;
  reg  [31:0] y;
  wire [31:0] o;
  \rt_wrap_reassign.rt_wrap_reassign  dut(.x(x), .y(y), .o(o));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; x = s & 64'd4294967295;
      s=s*A+C; y = s & 64'd4294967295;
      #1;
      if (k>=0) begin
        sig = sig*P + (o & 64'd4294967295);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
