`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module sim_sub_mealy_feedback_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [0:0] go;
  reg  [0:0] flush;
  reg  [3:0] d;
  reg clock;
  reg reset;
  wire [0:0] ready_o;
  wire [3:0] echo_o;
  sim_sub_mealy_feedback_top dut(.go(go), .flush(flush), .d(d), .clock(clock), .reset(reset), .ready_o(ready_o), .echo_o(echo_o));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; go = s & 64'd1;
      s=s*A+C; flush = s & 64'd1;
      s=s*A+C; d = s & 64'd15;
      reset = (k<4) ? 1'b1 : 1'b0;
      #1 clock=1; #1;
      #1 clock=0; #1;
      if (k>=4) begin
        sig = sig*P + (ready_o & 64'd1);
        sig = sig*P + (echo_o & 64'd15);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
