`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module splice_merge_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] in1;
  reg  [7:0] in2;
  wire [15:0] out;
  \splice_merge.spl  dut(.in1(in1), .in2(in2), .out(out));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; in1 = s & 64'd255;
      s=s*A+C; in2 = s & 64'd255;
      #1;
      if (k>=0) begin
        sig = sig*P + (out & 64'd65535);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
