`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module trivial_if_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [2:0] a;
  reg  [6:0] b;
  reg  [0:0] cond;
  wire [3:0] res;
  \trivial_if.fun3  dut(.a(a), .b(b), .cond(cond), .res(res));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd7;
      s=s*A+C; b = s & 64'd127;
      s=s*A+C; cond = s & 64'd1;
      #1;
      if (k>=0) begin
        sig = sig*P + (res & 64'd15);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
