`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module wire_reg_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] a;
  reg clock;
  reg reset;
  wire [8:0] o;
  \wire_reg.wreg  dut(.a(a), .clock(clock), .reset(reset), .o(o));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0; clock=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd255;
      reset = (k<4) ? 1'b1 : 1'b0;
      #1 clock=1; #1;
      if (k>=4) begin
        sig = sig*P + (o & 64'd511);
      end
      #1 clock=0; #1;
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
