`timescale 1ns/1ps
// AUTO-GENERATED by gen_equiv_tb.py -- differential sim golden driver.
module wire_typed_tb;
  localparam [63:0] A=64'd6364136223846793005, C=64'd1442695040888963407, P=64'd1099511628211;
  localparam [63:0] SEED=64'h1234567890ABCDEF, MASK=64'h3FFFFFFFFFFFFFFF;
  localparam integer NCYC=1000;
  reg  [7:0] a;
  wire [3:0] o1;
  wire [3:0] o2;
  \wire_typed.wt  dut(.a(a), .o1(o1), .o2(o2));
  reg [63:0] s, sig; integer k;
  initial begin
    s=SEED; sig=0;
    for (k=0;k<NCYC;k=k+1) begin
      s=s*A+C; a = s & 64'd255;
      #1;
      if (k>=0) begin
        sig = sig*P + (o1 & 64'd15);
        sig = sig*P + (o2 & 64'd15);
      end
    end
    $display("SIG %0d", sig & MASK);
    $finish;
  end
endmodule
