// Generated by CIRCT firtool-1.114.1
module ALU(
  input  [4:0]  io_operation,
  input  [63:0] io_inputx,
                io_inputy,
  output [63:0] io_result
);

  reg  [63:0]  casez_tmp;
  wire [126:0] _io_result_T_50 = {63'h0, io_inputx} << io_inputy[5:0];
  wire [31:0]  _io_result_T_36 = io_inputx[31:0] >> io_inputy[4:0];
  wire [31:0]  _io_result_T_20 = $signed($signed(io_inputx[31:0]) >>> io_inputy[4:0]);
  wire [31:0]  _io_result_T_10 = io_inputx[31:0] - io_inputy[31:0];
  wire [31:0]  _io_result_T_2 = io_inputx[31:0] + io_inputy[31:0];
  wire [62:0]  _io_result_T_44 = {31'h0, io_inputx[31:0]} << io_inputy[4:0];
  always_comb begin
    casez (io_operation[3:0])
      4'b0000:
        casez_tmp = io_inputx ^ io_inputy;
      4'b0001:
        casez_tmp = {63'h0, io_inputx < io_inputy};
      4'b0010:
        casez_tmp =
          io_operation[4]
            ? {{32{_io_result_T_36[31]}}, _io_result_T_36}
            : io_inputx >> io_inputy[5:0];
      4'b0011:
        casez_tmp =
          io_operation[4]
            ? {{32{_io_result_T_20[31]}}, _io_result_T_20}
            : $signed($signed(io_inputx) >>> io_inputy[5:0]);
      4'b0100:
        casez_tmp =
          io_operation[4]
            ? {{32{_io_result_T_10[31]}}, _io_result_T_10}
            : io_inputx - io_inputy;
      4'b0101:
        casez_tmp = io_inputx | io_inputy;
      4'b0110:
        casez_tmp = io_inputx & io_inputy;
      4'b0111:
        casez_tmp =
          io_operation[4]
            ? {{32{_io_result_T_2[31]}}, _io_result_T_2}
            : io_inputx + io_inputy;
      4'b1000:
        casez_tmp =
          io_operation[4]
            ? {{32{_io_result_T_44[31]}}, _io_result_T_44[31:0]}
            : _io_result_T_50[63:0];
      4'b1001:
        casez_tmp = {63'h0, $signed(io_inputx) < $signed(io_inputy)};
      4'b1010:
        casez_tmp = ~(io_inputx | io_inputy);
      4'b1011:
        casez_tmp = {63'h0, $signed(io_inputx) >= $signed(io_inputy)};
      4'b1100:
        casez_tmp = {63'h0, io_inputx >= io_inputy};
      4'b1101:
        casez_tmp = {63'h0, io_inputx == io_inputy};
      4'b1110:
        casez_tmp = {63'h0, io_inputx != io_inputy};
      default:
        casez_tmp = 64'h0;
    endcase
  end // always_comb
  assign io_result = casez_tmp;
endmodule

