// Generated by CIRCT firtool-1.114.1
module ALUControl(
  input        io_aluop,
               io_itype,
  input  [6:0] io_funct7,
  input  [2:0] io_funct3,
  input        io_wordinst,
  output [4:0] io_operation
);

  reg [4:0] casez_tmp;
  always_comb begin
    casez (io_funct3)
      3'b000:
        casez_tmp =
          io_itype | io_funct7 == 7'h0
            ? {io_wordinst, 4'h7}
            : io_funct7 == 7'h20 ? {io_wordinst, 4'h4} : 5'h1F;
      3'b001:
        casez_tmp = {io_wordinst, 4'h8};
      3'b010:
        casez_tmp = 5'h9;
      3'b011:
        casez_tmp = 5'h1;
      3'b100:
        casez_tmp = 5'h0;
      3'b101:
        casez_tmp =
          io_funct7[6:1] == 6'h0
            ? {io_wordinst, 4'h2}
            : io_funct7[6:1] == 6'h10 ? {io_wordinst, 4'h3} : 5'h1F;
      3'b110:
        casez_tmp = 5'h5;
      default:
        casez_tmp = 5'h6;
    endcase
  end // always_comb
  assign io_operation = io_aluop ? casez_tmp : 5'h7;
endmodule

