// Generated by CIRCT firtool-1.114.1
module Control(
  input  [6:0] io_opcode,
  output       io_itype,
               io_aluop,
               io_src1,
  output [1:0] io_src2,
  output       io_branch,
  output [1:0] io_jumptype,
  output       io_resultselect,
  output [1:0] io_memop,
  output       io_toreg,
               io_regwrite,
               io_wordinst
);

  wire _signals_T_1 = io_opcode == 7'h33;
  wire _signals_T_3 = io_opcode == 7'h13;
  wire _signals_T_110 = io_opcode == 7'h3;
  wire _signals_T_7 = io_opcode == 7'h23;
  wire _signals_T_68 = io_opcode == 7'h63;
  wire _signals_T_87 = io_opcode == 7'h37;
  wire _signals_T_13 = io_opcode == 7'h17;
  wire _signals_T_15 = io_opcode == 7'h6F;
  wire _signals_T_44 = io_opcode == 7'h67;
  wire _signals_T_53 = io_opcode == 7'h1B;
  wire _signals_T_132 = io_opcode == 7'h3B;
  wire _GEN = _signals_T_15 | _signals_T_44;
  wire _GEN_0 =
    _signals_T_110 | _signals_T_7 | _signals_T_68 | _signals_T_87 | _signals_T_13 | _GEN;
  wire _GEN_1 = _signals_T_1 | _signals_T_3;
  wire _GEN_2 = _signals_T_68 | _signals_T_87;
  wire _GEN_3 = _signals_T_3 | _signals_T_110 | _signals_T_7;
  wire _GEN_4 = _signals_T_7 | _signals_T_68;
  assign io_itype = ~_signals_T_1 & (_signals_T_3 | ~_GEN_0 & _signals_T_53);
  assign io_aluop = _GEN_1 | ~_GEN_0 & (_signals_T_53 | _signals_T_132);
  assign io_src1 =
    ~(_signals_T_1 | _signals_T_3 | _signals_T_110 | _signals_T_7 | _GEN_2)
    & (_signals_T_13 | _signals_T_15 | _signals_T_44);
  assign io_src2 =
    _signals_T_1
      ? 2'h0
      : _GEN_3
          ? 2'h1
          : _GEN_2 ? 2'h0 : _signals_T_13 ? 2'h1 : _GEN ? 2'h2 : {1'h0, _signals_T_53};
  assign io_branch = ~(_signals_T_1 | _GEN_3) & _signals_T_68;
  assign io_jumptype =
    _signals_T_1 | _signals_T_3 | _signals_T_110 | _signals_T_7 | _signals_T_68
    | _signals_T_87 | _signals_T_13
      ? 2'h0
      : _signals_T_15 ? 2'h2 : {2{_signals_T_44}};
  assign io_resultselect =
    ~(_signals_T_1 | _signals_T_3 | _signals_T_110 | _GEN_4) & _signals_T_87;
  assign io_memop = _GEN_1 ? 2'h0 : _signals_T_110 ? 2'h2 : {2{_signals_T_7}};
  assign io_toreg = ~_GEN_1 & _signals_T_110;
  assign io_regwrite =
    _signals_T_1 | _signals_T_3 | _signals_T_110 | ~_GEN_4
    & (_signals_T_87 | _signals_T_13 | _signals_T_15 | _signals_T_44 | _signals_T_53
       | _signals_T_132);
  assign io_wordinst =
    ~(_signals_T_1 | _signals_T_3 | _GEN_0) & (_signals_T_53 | _signals_T_132);
endmodule

