// Generated by CIRCT firtool-1.114.1
module DualIssueRegisterFile(
  input         clock,
  input  [4:0]  io_pipeA_readreg1,
                io_pipeA_readreg2,
                io_pipeA_writereg,
  input  [63:0] io_pipeA_writedata,
  input         io_pipeA_wen,
  input  [4:0]  io_pipeB_readreg1,
                io_pipeB_readreg2,
                io_pipeB_writereg,
  input  [63:0] io_pipeB_writedata,
  input         io_pipeB_wen,
  output [63:0] io_pipeA_readdata1,
                io_pipeA_readdata2,
                io_pipeB_readdata1,
                io_pipeB_readdata2
);

  reg  [63:0] regs_0;
  reg  [63:0] regs_1;
  reg  [63:0] regs_2;
  reg  [63:0] regs_3;
  reg  [63:0] regs_4;
  reg  [63:0] regs_5;
  reg  [63:0] regs_6;
  reg  [63:0] regs_7;
  reg  [63:0] regs_8;
  reg  [63:0] regs_9;
  reg  [63:0] regs_10;
  reg  [63:0] regs_11;
  reg  [63:0] regs_12;
  reg  [63:0] regs_13;
  reg  [63:0] regs_14;
  reg  [63:0] regs_15;
  reg  [63:0] regs_16;
  reg  [63:0] regs_17;
  reg  [63:0] regs_18;
  reg  [63:0] regs_19;
  reg  [63:0] regs_20;
  reg  [63:0] regs_21;
  reg  [63:0] regs_22;
  reg  [63:0] regs_23;
  reg  [63:0] regs_24;
  reg  [63:0] regs_25;
  reg  [63:0] regs_26;
  reg  [63:0] regs_27;
  reg  [63:0] regs_28;
  reg  [63:0] regs_29;
  reg  [63:0] regs_30;
  reg  [63:0] regs_31;
  reg  [63:0] casez_tmp;
  always_comb begin
    casez (io_pipeA_readreg1)
      5'b00000:
        casez_tmp = regs_0;
      5'b00001:
        casez_tmp = regs_1;
      5'b00010:
        casez_tmp = regs_2;
      5'b00011:
        casez_tmp = regs_3;
      5'b00100:
        casez_tmp = regs_4;
      5'b00101:
        casez_tmp = regs_5;
      5'b00110:
        casez_tmp = regs_6;
      5'b00111:
        casez_tmp = regs_7;
      5'b01000:
        casez_tmp = regs_8;
      5'b01001:
        casez_tmp = regs_9;
      5'b01010:
        casez_tmp = regs_10;
      5'b01011:
        casez_tmp = regs_11;
      5'b01100:
        casez_tmp = regs_12;
      5'b01101:
        casez_tmp = regs_13;
      5'b01110:
        casez_tmp = regs_14;
      5'b01111:
        casez_tmp = regs_15;
      5'b10000:
        casez_tmp = regs_16;
      5'b10001:
        casez_tmp = regs_17;
      5'b10010:
        casez_tmp = regs_18;
      5'b10011:
        casez_tmp = regs_19;
      5'b10100:
        casez_tmp = regs_20;
      5'b10101:
        casez_tmp = regs_21;
      5'b10110:
        casez_tmp = regs_22;
      5'b10111:
        casez_tmp = regs_23;
      5'b11000:
        casez_tmp = regs_24;
      5'b11001:
        casez_tmp = regs_25;
      5'b11010:
        casez_tmp = regs_26;
      5'b11011:
        casez_tmp = regs_27;
      5'b11100:
        casez_tmp = regs_28;
      5'b11101:
        casez_tmp = regs_29;
      5'b11110:
        casez_tmp = regs_30;
      default:
        casez_tmp = regs_31;
    endcase
  end // always_comb
  reg  [63:0] casez_tmp_0;
  always_comb begin
    casez (io_pipeA_readreg2)
      5'b00000:
        casez_tmp_0 = regs_0;
      5'b00001:
        casez_tmp_0 = regs_1;
      5'b00010:
        casez_tmp_0 = regs_2;
      5'b00011:
        casez_tmp_0 = regs_3;
      5'b00100:
        casez_tmp_0 = regs_4;
      5'b00101:
        casez_tmp_0 = regs_5;
      5'b00110:
        casez_tmp_0 = regs_6;
      5'b00111:
        casez_tmp_0 = regs_7;
      5'b01000:
        casez_tmp_0 = regs_8;
      5'b01001:
        casez_tmp_0 = regs_9;
      5'b01010:
        casez_tmp_0 = regs_10;
      5'b01011:
        casez_tmp_0 = regs_11;
      5'b01100:
        casez_tmp_0 = regs_12;
      5'b01101:
        casez_tmp_0 = regs_13;
      5'b01110:
        casez_tmp_0 = regs_14;
      5'b01111:
        casez_tmp_0 = regs_15;
      5'b10000:
        casez_tmp_0 = regs_16;
      5'b10001:
        casez_tmp_0 = regs_17;
      5'b10010:
        casez_tmp_0 = regs_18;
      5'b10011:
        casez_tmp_0 = regs_19;
      5'b10100:
        casez_tmp_0 = regs_20;
      5'b10101:
        casez_tmp_0 = regs_21;
      5'b10110:
        casez_tmp_0 = regs_22;
      5'b10111:
        casez_tmp_0 = regs_23;
      5'b11000:
        casez_tmp_0 = regs_24;
      5'b11001:
        casez_tmp_0 = regs_25;
      5'b11010:
        casez_tmp_0 = regs_26;
      5'b11011:
        casez_tmp_0 = regs_27;
      5'b11100:
        casez_tmp_0 = regs_28;
      5'b11101:
        casez_tmp_0 = regs_29;
      5'b11110:
        casez_tmp_0 = regs_30;
      default:
        casez_tmp_0 = regs_31;
    endcase
  end // always_comb
  reg  [63:0] casez_tmp_1;
  always_comb begin
    casez (io_pipeB_readreg1)
      5'b00000:
        casez_tmp_1 = regs_0;
      5'b00001:
        casez_tmp_1 = regs_1;
      5'b00010:
        casez_tmp_1 = regs_2;
      5'b00011:
        casez_tmp_1 = regs_3;
      5'b00100:
        casez_tmp_1 = regs_4;
      5'b00101:
        casez_tmp_1 = regs_5;
      5'b00110:
        casez_tmp_1 = regs_6;
      5'b00111:
        casez_tmp_1 = regs_7;
      5'b01000:
        casez_tmp_1 = regs_8;
      5'b01001:
        casez_tmp_1 = regs_9;
      5'b01010:
        casez_tmp_1 = regs_10;
      5'b01011:
        casez_tmp_1 = regs_11;
      5'b01100:
        casez_tmp_1 = regs_12;
      5'b01101:
        casez_tmp_1 = regs_13;
      5'b01110:
        casez_tmp_1 = regs_14;
      5'b01111:
        casez_tmp_1 = regs_15;
      5'b10000:
        casez_tmp_1 = regs_16;
      5'b10001:
        casez_tmp_1 = regs_17;
      5'b10010:
        casez_tmp_1 = regs_18;
      5'b10011:
        casez_tmp_1 = regs_19;
      5'b10100:
        casez_tmp_1 = regs_20;
      5'b10101:
        casez_tmp_1 = regs_21;
      5'b10110:
        casez_tmp_1 = regs_22;
      5'b10111:
        casez_tmp_1 = regs_23;
      5'b11000:
        casez_tmp_1 = regs_24;
      5'b11001:
        casez_tmp_1 = regs_25;
      5'b11010:
        casez_tmp_1 = regs_26;
      5'b11011:
        casez_tmp_1 = regs_27;
      5'b11100:
        casez_tmp_1 = regs_28;
      5'b11101:
        casez_tmp_1 = regs_29;
      5'b11110:
        casez_tmp_1 = regs_30;
      default:
        casez_tmp_1 = regs_31;
    endcase
  end // always_comb
  reg  [63:0] casez_tmp_2;
  always_comb begin
    casez (io_pipeB_readreg2)
      5'b00000:
        casez_tmp_2 = regs_0;
      5'b00001:
        casez_tmp_2 = regs_1;
      5'b00010:
        casez_tmp_2 = regs_2;
      5'b00011:
        casez_tmp_2 = regs_3;
      5'b00100:
        casez_tmp_2 = regs_4;
      5'b00101:
        casez_tmp_2 = regs_5;
      5'b00110:
        casez_tmp_2 = regs_6;
      5'b00111:
        casez_tmp_2 = regs_7;
      5'b01000:
        casez_tmp_2 = regs_8;
      5'b01001:
        casez_tmp_2 = regs_9;
      5'b01010:
        casez_tmp_2 = regs_10;
      5'b01011:
        casez_tmp_2 = regs_11;
      5'b01100:
        casez_tmp_2 = regs_12;
      5'b01101:
        casez_tmp_2 = regs_13;
      5'b01110:
        casez_tmp_2 = regs_14;
      5'b01111:
        casez_tmp_2 = regs_15;
      5'b10000:
        casez_tmp_2 = regs_16;
      5'b10001:
        casez_tmp_2 = regs_17;
      5'b10010:
        casez_tmp_2 = regs_18;
      5'b10011:
        casez_tmp_2 = regs_19;
      5'b10100:
        casez_tmp_2 = regs_20;
      5'b10101:
        casez_tmp_2 = regs_21;
      5'b10110:
        casez_tmp_2 = regs_22;
      5'b10111:
        casez_tmp_2 = regs_23;
      5'b11000:
        casez_tmp_2 = regs_24;
      5'b11001:
        casez_tmp_2 = regs_25;
      5'b11010:
        casez_tmp_2 = regs_26;
      5'b11011:
        casez_tmp_2 = regs_27;
      5'b11100:
        casez_tmp_2 = regs_28;
      5'b11101:
        casez_tmp_2 = regs_29;
      5'b11110:
        casez_tmp_2 = regs_30;
      default:
        casez_tmp_2 = regs_31;
    endcase
  end // always_comb
  wire        _GEN = io_pipeB_writereg == 5'h0;
  wire        _GEN_0 = io_pipeB_writereg == 5'h1;
  wire        _GEN_1 = io_pipeB_writereg == 5'h2;
  wire        _GEN_2 = io_pipeB_writereg == 5'h3;
  wire        _GEN_3 = io_pipeB_writereg == 5'h4;
  wire        _GEN_4 = io_pipeB_writereg == 5'h5;
  wire        _GEN_5 = io_pipeB_writereg == 5'h6;
  wire        _GEN_6 = io_pipeB_writereg == 5'h7;
  wire        _GEN_7 = io_pipeB_writereg == 5'h8;
  wire        _GEN_8 = io_pipeB_writereg == 5'h9;
  wire        _GEN_9 = io_pipeB_writereg == 5'hA;
  wire        _GEN_10 = io_pipeB_writereg == 5'hB;
  wire        _GEN_11 = io_pipeB_writereg == 5'hC;
  wire        _GEN_12 = io_pipeB_writereg == 5'hD;
  wire        _GEN_13 = io_pipeB_writereg == 5'hE;
  wire        _GEN_14 = io_pipeB_writereg == 5'hF;
  wire        _GEN_15 = io_pipeB_writereg == 5'h10;
  wire        _GEN_16 = io_pipeB_writereg == 5'h11;
  wire        _GEN_17 = io_pipeB_writereg == 5'h12;
  wire        _GEN_18 = io_pipeB_writereg == 5'h13;
  wire        _GEN_19 = io_pipeB_writereg == 5'h14;
  wire        _GEN_20 = io_pipeB_writereg == 5'h15;
  wire        _GEN_21 = io_pipeB_writereg == 5'h16;
  wire        _GEN_22 = io_pipeB_writereg == 5'h17;
  wire        _GEN_23 = io_pipeB_writereg == 5'h18;
  wire        _GEN_24 = io_pipeB_writereg == 5'h19;
  wire        _GEN_25 = io_pipeB_writereg == 5'h1A;
  wire        _GEN_26 = io_pipeB_writereg == 5'h1B;
  wire        _GEN_27 = io_pipeB_writereg == 5'h1C;
  wire        _GEN_28 = io_pipeB_writereg == 5'h1D;
  wire        _GEN_29 = io_pipeB_writereg == 5'h1E;
  always @(posedge clock) begin
    if (io_pipeA_wen & io_pipeB_wen & io_pipeA_writereg == io_pipeB_writereg) begin
      if (_GEN)
        regs_0 <= io_pipeB_writedata;
      if (_GEN_0)
        regs_1 <= io_pipeB_writedata;
      if (_GEN_1)
        regs_2 <= io_pipeB_writedata;
      if (_GEN_2)
        regs_3 <= io_pipeB_writedata;
      if (_GEN_3)
        regs_4 <= io_pipeB_writedata;
      if (_GEN_4)
        regs_5 <= io_pipeB_writedata;
      if (_GEN_5)
        regs_6 <= io_pipeB_writedata;
      if (_GEN_6)
        regs_7 <= io_pipeB_writedata;
      if (_GEN_7)
        regs_8 <= io_pipeB_writedata;
      if (_GEN_8)
        regs_9 <= io_pipeB_writedata;
      if (_GEN_9)
        regs_10 <= io_pipeB_writedata;
      if (_GEN_10)
        regs_11 <= io_pipeB_writedata;
      if (_GEN_11)
        regs_12 <= io_pipeB_writedata;
      if (_GEN_12)
        regs_13 <= io_pipeB_writedata;
      if (_GEN_13)
        regs_14 <= io_pipeB_writedata;
      if (_GEN_14)
        regs_15 <= io_pipeB_writedata;
      if (_GEN_15)
        regs_16 <= io_pipeB_writedata;
      if (_GEN_16)
        regs_17 <= io_pipeB_writedata;
      if (_GEN_17)
        regs_18 <= io_pipeB_writedata;
      if (_GEN_18)
        regs_19 <= io_pipeB_writedata;
      if (_GEN_19)
        regs_20 <= io_pipeB_writedata;
      if (_GEN_20)
        regs_21 <= io_pipeB_writedata;
      if (_GEN_21)
        regs_22 <= io_pipeB_writedata;
      if (_GEN_22)
        regs_23 <= io_pipeB_writedata;
      if (_GEN_23)
        regs_24 <= io_pipeB_writedata;
      if (_GEN_24)
        regs_25 <= io_pipeB_writedata;
      if (_GEN_25)
        regs_26 <= io_pipeB_writedata;
      if (_GEN_26)
        regs_27 <= io_pipeB_writedata;
      if (_GEN_27)
        regs_28 <= io_pipeB_writedata;
      if (_GEN_28)
        regs_29 <= io_pipeB_writedata;
      if (_GEN_29)
        regs_30 <= io_pipeB_writedata;
      if (&io_pipeB_writereg)
        regs_31 <= io_pipeB_writedata;
    end
    else begin
      if (io_pipeB_wen & _GEN)
        regs_0 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h0)
        regs_0 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_0)
        regs_1 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h1)
        regs_1 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_1)
        regs_2 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h2)
        regs_2 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_2)
        regs_3 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h3)
        regs_3 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_3)
        regs_4 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h4)
        regs_4 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_4)
        regs_5 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h5)
        regs_5 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_5)
        regs_6 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h6)
        regs_6 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_6)
        regs_7 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h7)
        regs_7 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_7)
        regs_8 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h8)
        regs_8 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_8)
        regs_9 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h9)
        regs_9 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_9)
        regs_10 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'hA)
        regs_10 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_10)
        regs_11 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'hB)
        regs_11 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_11)
        regs_12 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'hC)
        regs_12 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_12)
        regs_13 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'hD)
        regs_13 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_13)
        regs_14 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'hE)
        regs_14 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_14)
        regs_15 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'hF)
        regs_15 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_15)
        regs_16 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h10)
        regs_16 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_16)
        regs_17 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h11)
        regs_17 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_17)
        regs_18 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h12)
        regs_18 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_18)
        regs_19 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h13)
        regs_19 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_19)
        regs_20 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h14)
        regs_20 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_20)
        regs_21 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h15)
        regs_21 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_21)
        regs_22 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h16)
        regs_22 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_22)
        regs_23 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h17)
        regs_23 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_23)
        regs_24 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h18)
        regs_24 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_24)
        regs_25 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h19)
        regs_25 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_25)
        regs_26 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h1A)
        regs_26 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_26)
        regs_27 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h1B)
        regs_27 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_27)
        regs_28 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h1C)
        regs_28 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_28)
        regs_29 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h1D)
        regs_29 <= io_pipeA_writedata;
      if (io_pipeB_wen & _GEN_29)
        regs_30 <= io_pipeB_writedata;
      else if (io_pipeA_wen & io_pipeA_writereg == 5'h1E)
        regs_30 <= io_pipeA_writedata;
      if (io_pipeB_wen & (&io_pipeB_writereg))
        regs_31 <= io_pipeB_writedata;
      else if (io_pipeA_wen & (&io_pipeA_writereg))
        regs_31 <= io_pipeA_writedata;
    end
  end // always @(posedge)
  assign io_pipeA_readdata1 = casez_tmp;
  assign io_pipeA_readdata2 = casez_tmp_0;
  assign io_pipeB_readdata1 = casez_tmp_1;
  assign io_pipeB_readdata2 = casez_tmp_2;
endmodule

