// Generated by CIRCT firtool-1.114.1
module DualIssueForwardingUnit(
  input  [4:0] io_ex_pipeA_rs1,
               io_ex_pipeA_rs2,
               io_ex_pipeB_rs1,
               io_ex_pipeB_rs2,
               io_mem_pipeA_rd,
  input        io_mem_pipeA_rw,
  input  [4:0] io_mem_pipeB_rd,
  input        io_mem_pipeB_rw,
  input  [4:0] io_wb_pipeA_rd,
  input        io_wb_pipeA_rw,
  input  [4:0] io_wb_pipeB_rd,
  input        io_wb_pipeB_rw,
  output [2:0] io_pipeA_forward1,
               io_pipeA_forward2,
               io_pipeB_forward1,
               io_pipeB_forward2
);

  assign io_pipeA_forward1 =
    io_mem_pipeB_rw & io_mem_pipeB_rd == io_ex_pipeA_rs1 & (|io_ex_pipeA_rs1)
      ? 3'h2
      : io_mem_pipeA_rw & io_mem_pipeA_rd == io_ex_pipeA_rs1 & (|io_ex_pipeA_rs1)
          ? 3'h1
          : io_wb_pipeB_rw & io_wb_pipeB_rd == io_ex_pipeA_rs1 & (|io_ex_pipeA_rs1)
              ? 3'h4
              : io_wb_pipeA_rw & io_wb_pipeA_rd == io_ex_pipeA_rs1 & (|io_ex_pipeA_rs1)
                  ? 3'h3
                  : 3'h0;
  assign io_pipeA_forward2 =
    io_mem_pipeB_rw & io_mem_pipeB_rd == io_ex_pipeA_rs2 & (|io_ex_pipeA_rs2)
      ? 3'h2
      : io_mem_pipeA_rw & io_mem_pipeA_rd == io_ex_pipeA_rs2 & (|io_ex_pipeA_rs2)
          ? 3'h1
          : io_wb_pipeB_rw & io_wb_pipeB_rd == io_ex_pipeA_rs2 & (|io_ex_pipeA_rs2)
              ? 3'h4
              : io_wb_pipeA_rw & io_wb_pipeA_rd == io_ex_pipeA_rs2 & (|io_ex_pipeA_rs2)
                  ? 3'h3
                  : 3'h0;
  assign io_pipeB_forward1 =
    io_mem_pipeB_rw & io_mem_pipeB_rd == io_ex_pipeB_rs1 & (|io_ex_pipeB_rs1)
      ? 3'h3
      : io_mem_pipeA_rw & io_mem_pipeA_rd == io_ex_pipeB_rs1 & (|io_ex_pipeB_rs1)
          ? 3'h2
          : io_wb_pipeB_rw & io_wb_pipeB_rd == io_ex_pipeB_rs1 & (|io_ex_pipeB_rs1)
              ? 3'h5
              : {io_wb_pipeA_rw & io_wb_pipeA_rd == io_ex_pipeB_rs1 & (|io_ex_pipeB_rs1),
                 2'h0};
  assign io_pipeB_forward2 =
    io_mem_pipeB_rw & io_mem_pipeB_rd == io_ex_pipeB_rs2 & (|io_ex_pipeB_rs2)
      ? 3'h3
      : io_mem_pipeA_rw & io_mem_pipeA_rd == io_ex_pipeB_rs2 & (|io_ex_pipeB_rs2)
          ? 3'h2
          : io_wb_pipeB_rw & io_wb_pipeB_rd == io_ex_pipeB_rs2 & (|io_ex_pipeB_rs2)
              ? 3'h5
              : {io_wb_pipeA_rw & io_wb_pipeA_rd == io_ex_pipeB_rs2 & (|io_ex_pipeB_rs2),
                 2'h0};
endmodule

