// Generated by CIRCT firtool-1.114.1
module DualIssueNextPC(
  input         io_branch,
  input  [1:0]  io_jumptype,
  input  [63:0] io_inputx,
                io_inputy,
  input  [2:0]  io_funct3,
  input  [63:0] io_pc,
                io_imm,
  input         io_pipeB_valid,
  output [63:0] io_nextpc,
  output        io_taken
);

  wire _GEN =
    io_funct3 == 3'h0 & io_inputx == io_inputy | io_funct3 == 3'h1
    & io_inputx != io_inputy | io_funct3 == 3'h4 & $signed(io_inputx) < $signed(io_inputy)
    | io_funct3 == 3'h5 & $signed(io_inputx) >= $signed(io_inputy) | io_funct3 == 3'h6
    & io_inputx < io_inputy | (&io_funct3) & io_inputx >= io_inputy;
  assign io_nextpc =
    io_branch
      ? (_GEN ? io_pc + io_imm : io_pipeB_valid ? io_pc + 64'h8 : io_pc + 64'h4)
      : (|io_jumptype)
          ? (io_jumptype[0] ? io_inputx + io_imm : io_pc + io_imm)
          : io_pipeB_valid ? io_pc + 64'h8 : io_pc + 64'h4;
  assign io_taken = io_branch ? _GEN : (|io_jumptype);
endmodule

