// Generated by CIRCT firtool-1.114.1
module DualIssueHazardUnit(
  input  [4:0] io_id_pipeA_rs1,
               io_id_pipeA_rs2,
               io_id_pipeB_rs1,
               io_id_pipeB_rs2,
  input        io_pipeA_idex_memread,
  input  [4:0] io_pipeA_idex_rd,
  input        io_pipeA_exmem_taken,
               io_pipeB_idex_memread,
  input  [4:0] io_pipeB_idex_rd,
  input        io_pipeB_exmem_taken,
  output       io_pcfromtaken,
               io_pcstall,
               io_if_id_stall,
               io_id_ex_flush,
               io_ex_mem_flush,
               io_if_id_flush
);

  wire io_pcfromtaken_0 = io_pipeA_exmem_taken | io_pipeB_exmem_taken;
  wire _GEN =
    io_pipeB_idex_memread
    & (io_pipeB_idex_rd == io_id_pipeA_rs1 | io_pipeB_idex_rd == io_id_pipeA_rs2
       | io_pipeB_idex_rd == io_id_pipeB_rs1 | io_pipeB_idex_rd == io_id_pipeB_rs2)
    | io_pipeA_idex_memread
    & (io_pipeA_idex_rd == io_id_pipeA_rs1 | io_pipeA_idex_rd == io_id_pipeA_rs2
       | io_pipeA_idex_rd == io_id_pipeB_rs1 | io_pipeA_idex_rd == io_id_pipeB_rs2);
  wire io_pcstall_0 = ~io_pcfromtaken_0 & _GEN;
  assign io_pcfromtaken = io_pcfromtaken_0;
  assign io_pcstall = io_pcstall_0;
  assign io_if_id_stall = io_pcstall_0;
  assign io_id_ex_flush = io_pcfromtaken_0 | _GEN;
  assign io_ex_mem_flush = io_pcfromtaken_0;
  assign io_if_id_flush = io_pcfromtaken_0;
endmodule

