// Generated by CIRCT firtool-1.114.1
module PipelinedDualIssueCPU(
  input         clock,
                reset,
  output [63:0] io_imem_address,
  output        io_imem_valid,
  input         io_imem_good,
  input  [63:0] io_imem_instruction,
  input         io_imem_ready,
  output [63:0] io_dmem_address,
  output        io_dmem_valid,
  input         io_dmem_good,
  output [63:0] io_dmem_writedata,
  output        io_dmem_memread,
                io_dmem_memwrite,
  output [1:0]  io_dmem_maskmode,
  output        io_dmem_sext,
  input  [63:0] io_dmem_readdata
);

  wire [63:0] pipeB_wb_writedata;
  wire [63:0] pipeA_wb_writedata;
  wire        _pipeB_mem_wb_ctrl_io_data_wb_ctrl_toreg;
  wire        _pipeB_mem_wb_ctrl_io_data_wb_ctrl_regwrite;
  wire        _pipeA_mem_wb_ctrl_io_data_wb_ctrl_toreg;
  wire        _pipeA_mem_wb_ctrl_io_data_wb_ctrl_regwrite;
  wire [63:0] _pipeB_mem_wb_io_data_readdata;
  wire [63:0] _pipeB_mem_wb_io_data_ex_result;
  wire [63:0] _pipeB_mem_wb_io_data_instruction;
  wire [63:0] _pipeA_mem_wb_io_data_readdata;
  wire [63:0] _pipeA_mem_wb_io_data_ex_result;
  wire [63:0] _pipeA_mem_wb_io_data_instruction;
  wire [1:0]  _pipeB_ex_mem_ctrl_io_data_mem_ctrl_memop;
  wire        _pipeB_ex_mem_ctrl_io_data_wb_ctrl_toreg;
  wire        _pipeB_ex_mem_ctrl_io_data_wb_ctrl_regwrite;
  wire [1:0]  _pipeA_ex_mem_ctrl_io_data_mem_ctrl_memop;
  wire        _pipeA_ex_mem_ctrl_io_data_wb_ctrl_toreg;
  wire        _pipeA_ex_mem_ctrl_io_data_wb_ctrl_regwrite;
  wire [63:0] _pipeB_ex_mem_io_data_ex_result;
  wire [63:0] _pipeB_ex_mem_io_data_mem_writedata;
  wire [63:0] _pipeB_ex_mem_io_data_nextpc;
  wire        _pipeB_ex_mem_io_data_taken;
  wire [63:0] _pipeB_ex_mem_io_data_instruction;
  wire        _pipeB_ex_mem_io_data_isValid;
  wire [63:0] _pipeA_ex_mem_io_data_ex_result;
  wire [63:0] _pipeA_ex_mem_io_data_mem_writedata;
  wire [63:0] _pipeA_ex_mem_io_data_nextpc;
  wire        _pipeA_ex_mem_io_data_taken;
  wire [63:0] _pipeA_ex_mem_io_data_instruction;
  wire        _pipeB_id_ex_ctrl_io_data_ex_ctrl_itype;
  wire        _pipeB_id_ex_ctrl_io_data_ex_ctrl_aluop;
  wire        _pipeB_id_ex_ctrl_io_data_ex_ctrl_src1;
  wire [1:0]  _pipeB_id_ex_ctrl_io_data_ex_ctrl_src2;
  wire        _pipeB_id_ex_ctrl_io_data_ex_ctrl_branch;
  wire [1:0]  _pipeB_id_ex_ctrl_io_data_ex_ctrl_jumptype;
  wire        _pipeB_id_ex_ctrl_io_data_ex_ctrl_resultselect;
  wire        _pipeB_id_ex_ctrl_io_data_ex_ctrl_wordinst;
  wire [1:0]  _pipeB_id_ex_ctrl_io_data_mem_ctrl_memop;
  wire        _pipeB_id_ex_ctrl_io_data_wb_ctrl_toreg;
  wire        _pipeB_id_ex_ctrl_io_data_wb_ctrl_regwrite;
  wire        _pipeA_id_ex_ctrl_io_data_ex_ctrl_itype;
  wire        _pipeA_id_ex_ctrl_io_data_ex_ctrl_aluop;
  wire        _pipeA_id_ex_ctrl_io_data_ex_ctrl_src1;
  wire [1:0]  _pipeA_id_ex_ctrl_io_data_ex_ctrl_src2;
  wire        _pipeA_id_ex_ctrl_io_data_ex_ctrl_branch;
  wire [1:0]  _pipeA_id_ex_ctrl_io_data_ex_ctrl_jumptype;
  wire        _pipeA_id_ex_ctrl_io_data_ex_ctrl_resultselect;
  wire        _pipeA_id_ex_ctrl_io_data_ex_ctrl_wordinst;
  wire [1:0]  _pipeA_id_ex_ctrl_io_data_mem_ctrl_memop;
  wire        _pipeA_id_ex_ctrl_io_data_wb_ctrl_toreg;
  wire        _pipeA_id_ex_ctrl_io_data_wb_ctrl_regwrite;
  wire [63:0] _pipeB_id_ex_io_data_pc;
  wire [63:0] _pipeB_id_ex_io_data_instruction;
  wire [63:0] _pipeB_id_ex_io_data_sextImm;
  wire [63:0] _pipeB_id_ex_io_data_readdata1;
  wire [63:0] _pipeB_id_ex_io_data_readdata2;
  wire        _pipeB_id_ex_io_data_isValid;
  wire [63:0] _pipeA_id_ex_io_data_pc;
  wire [63:0] _pipeA_id_ex_io_data_instruction;
  wire [63:0] _pipeA_id_ex_io_data_sextImm;
  wire [63:0] _pipeA_id_ex_io_data_readdata1;
  wire [63:0] _pipeA_id_ex_io_data_readdata2;
  wire        _pipeA_id_ex_io_data_isValid;
  wire [31:0] _pipeB_if_id_io_data_instruction;
  wire [63:0] _pipeB_if_id_io_data_pc;
  wire        _pipeB_if_id_io_data_isValid;
  wire [31:0] _pipeA_if_id_io_data_instruction;
  wire [63:0] _pipeA_if_id_io_data_pc;
  wire        _pipeA_if_id_io_data_isValid;
  wire        _hazard_io_pcfromtaken;
  wire        _hazard_io_pcstall;
  wire        _hazard_io_if_id_stall;
  wire        _hazard_io_id_ex_flush;
  wire        _hazard_io_ex_mem_flush;
  wire        _hazard_io_if_id_flush;
  wire [2:0]  _forwarding_io_pipeA_forward1;
  wire [2:0]  _forwarding_io_pipeA_forward2;
  wire [2:0]  _forwarding_io_pipeB_forward1;
  wire [2:0]  _forwarding_io_pipeB_forward2;
  wire [63:0] _nextPCmod_io_nextpc;
  wire        _nextPCmod_io_taken;
  wire [63:0] _pipeB_alu_io_result;
  wire [63:0] _pipeA_alu_io_result;
  wire [4:0]  _pipeB_aluControl_io_operation;
  wire [4:0]  _pipeA_aluControl_io_operation;
  wire [63:0] _pipeB_immGen_io_sextImm;
  wire [63:0] _pipeA_immGen_io_sextImm;
  wire        _pipeB_control_io_itype;
  wire        _pipeB_control_io_aluop;
  wire        _pipeB_control_io_src1;
  wire [1:0]  _pipeB_control_io_src2;
  wire        _pipeB_control_io_branch;
  wire [1:0]  _pipeB_control_io_jumptype;
  wire        _pipeB_control_io_resultselect;
  wire [1:0]  _pipeB_control_io_memop;
  wire        _pipeB_control_io_toreg;
  wire        _pipeB_control_io_regwrite;
  wire        _pipeB_control_io_wordinst;
  wire        _pipeA_control_io_itype;
  wire        _pipeA_control_io_aluop;
  wire        _pipeA_control_io_src1;
  wire [1:0]  _pipeA_control_io_src2;
  wire        _pipeA_control_io_branch;
  wire [1:0]  _pipeA_control_io_jumptype;
  wire        _pipeA_control_io_resultselect;
  wire [1:0]  _pipeA_control_io_memop;
  wire        _pipeA_control_io_toreg;
  wire        _pipeA_control_io_regwrite;
  wire        _pipeA_control_io_wordinst;
  wire [63:0] _registers_io_pipeA_readdata1;
  wire [63:0] _registers_io_pipeA_readdata2;
  wire [63:0] _registers_io_pipeB_readdata1;
  wire [63:0] _registers_io_pipeB_readdata2;
  wire [63:0] _issueUnit_io_nextpc;
  wire [31:0] _issueUnit_io_pipeA_inst;
  wire [31:0] _issueUnit_io_pipeB_inst;
  wire        _issueUnit_io_pipeB_valid;
  reg  [63:0] pc;
  wire [63:0] pipeA_immGen_io_instruction = {32'h0, _pipeA_if_id_io_data_instruction};
  wire [63:0] pipeB_immGen_io_instruction = {32'h0, _pipeB_if_id_io_data_instruction};
  reg  [63:0] casez_tmp;
  always_comb begin
    casez (_forwarding_io_pipeA_forward1)
      3'b000:
        casez_tmp = _pipeA_id_ex_io_data_readdata1;
      3'b001:
        casez_tmp = _pipeA_ex_mem_io_data_ex_result;
      3'b010:
        casez_tmp = _pipeB_ex_mem_io_data_ex_result;
      3'b011:
        casez_tmp = pipeA_wb_writedata;
      3'b100:
        casez_tmp = pipeB_wb_writedata;
      3'b101:
        casez_tmp = 64'h0;
      3'b110:
        casez_tmp = 64'h0;
      default:
        casez_tmp = 64'h0;
    endcase
  end // always_comb
  reg  [63:0] casez_tmp_0;
  always_comb begin
    casez (_forwarding_io_pipeA_forward2)
      3'b000:
        casez_tmp_0 = _pipeA_id_ex_io_data_readdata2;
      3'b001:
        casez_tmp_0 = _pipeA_ex_mem_io_data_ex_result;
      3'b010:
        casez_tmp_0 = _pipeB_ex_mem_io_data_ex_result;
      3'b011:
        casez_tmp_0 = pipeA_wb_writedata;
      3'b100:
        casez_tmp_0 = pipeB_wb_writedata;
      3'b101:
        casez_tmp_0 = 64'h0;
      3'b110:
        casez_tmp_0 = 64'h0;
      default:
        casez_tmp_0 = 64'h0;
    endcase
  end // always_comb
  reg  [63:0] casez_tmp_1;
  always_comb begin
    casez (_forwarding_io_pipeB_forward1)
      3'b000:
        casez_tmp_1 = _pipeB_id_ex_io_data_readdata1;
      3'b001:
        casez_tmp_1 = 64'h0;
      3'b010:
        casez_tmp_1 = _pipeA_ex_mem_io_data_ex_result;
      3'b011:
        casez_tmp_1 = _pipeB_ex_mem_io_data_ex_result;
      3'b100:
        casez_tmp_1 = pipeA_wb_writedata;
      3'b101:
        casez_tmp_1 = pipeB_wb_writedata;
      3'b110:
        casez_tmp_1 = 64'h0;
      default:
        casez_tmp_1 = 64'h0;
    endcase
  end // always_comb
  reg  [63:0] casez_tmp_2;
  always_comb begin
    casez (_forwarding_io_pipeB_forward2)
      3'b000:
        casez_tmp_2 = _pipeB_id_ex_io_data_readdata2;
      3'b001:
        casez_tmp_2 = 64'h0;
      3'b010:
        casez_tmp_2 = _pipeA_ex_mem_io_data_ex_result;
      3'b011:
        casez_tmp_2 = _pipeB_ex_mem_io_data_ex_result;
      3'b100:
        casez_tmp_2 = pipeA_wb_writedata;
      3'b101:
        casez_tmp_2 = pipeB_wb_writedata;
      3'b110:
        casez_tmp_2 = 64'h0;
      default:
        casez_tmp_2 = 64'h0;
    endcase
  end // always_comb
  assign pipeA_wb_writedata =
    _pipeA_mem_wb_ctrl_io_data_wb_ctrl_toreg
      ? _pipeA_mem_wb_io_data_readdata
      : _pipeA_mem_wb_io_data_ex_result;
  assign pipeB_wb_writedata =
    _pipeB_mem_wb_ctrl_io_data_wb_ctrl_toreg
      ? _pipeB_mem_wb_io_data_readdata
      : _pipeB_mem_wb_io_data_ex_result;
  always @(posedge clock) begin
    if (reset)
      pc <= 64'h0;
    else if (_hazard_io_pcfromtaken)
      pc <=
        _pipeB_ex_mem_io_data_isValid
          ? _pipeB_ex_mem_io_data_nextpc
          : _pipeA_ex_mem_io_data_nextpc;
    else if (_hazard_io_pcstall) begin
    end
    else
      pc <= _issueUnit_io_nextpc;
  end // always @(posedge)
  DualIssueIssueUnit issueUnit (
    .clock          (clock),
    .reset          (reset),
    .io_pc          (pc),
    .io_inst        (io_imem_instruction),
    .io_nextpc      (_issueUnit_io_nextpc),
    .io_pipeA_inst  (_issueUnit_io_pipeA_inst),
    .io_pipeB_inst  (_issueUnit_io_pipeB_inst),
    .io_pipeB_valid (_issueUnit_io_pipeB_valid)
  );
  DualIssueRegisterFile registers (
    .clock              (clock),
    .io_pipeA_readreg1  (_pipeA_if_id_io_data_instruction[19:15]),
    .io_pipeA_readreg2  (_pipeA_if_id_io_data_instruction[24:20]),
    .io_pipeA_writereg  (_pipeA_mem_wb_io_data_instruction[11:7]),
    .io_pipeA_writedata (pipeA_wb_writedata),
    .io_pipeA_wen
      ((|(_pipeA_mem_wb_io_data_instruction[11:7]))
       & _pipeA_mem_wb_ctrl_io_data_wb_ctrl_regwrite),
    .io_pipeB_readreg1  (_pipeB_if_id_io_data_instruction[19:15]),
    .io_pipeB_readreg2  (_pipeB_if_id_io_data_instruction[24:20]),
    .io_pipeB_writereg  (_pipeB_mem_wb_io_data_instruction[11:7]),
    .io_pipeB_writedata (pipeB_wb_writedata),
    .io_pipeB_wen
      ((|(_pipeB_mem_wb_io_data_instruction[11:7]))
       & _pipeB_mem_wb_ctrl_io_data_wb_ctrl_regwrite),
    .io_pipeA_readdata1 (_registers_io_pipeA_readdata1),
    .io_pipeA_readdata2 (_registers_io_pipeA_readdata2),
    .io_pipeB_readdata1 (_registers_io_pipeB_readdata1),
    .io_pipeB_readdata2 (_registers_io_pipeB_readdata2)
  );
  Control pipeA_control (
    .io_opcode       (_pipeA_if_id_io_data_instruction[6:0]),
    .io_itype        (_pipeA_control_io_itype),
    .io_aluop        (_pipeA_control_io_aluop),
    .io_src1         (_pipeA_control_io_src1),
    .io_src2         (_pipeA_control_io_src2),
    .io_branch       (_pipeA_control_io_branch),
    .io_jumptype     (_pipeA_control_io_jumptype),
    .io_resultselect (_pipeA_control_io_resultselect),
    .io_memop        (_pipeA_control_io_memop),
    .io_toreg        (_pipeA_control_io_toreg),
    .io_regwrite     (_pipeA_control_io_regwrite),
    .io_wordinst     (_pipeA_control_io_wordinst)
  );
  Control pipeB_control (
    .io_opcode       (_pipeB_if_id_io_data_instruction[6:0]),
    .io_itype        (_pipeB_control_io_itype),
    .io_aluop        (_pipeB_control_io_aluop),
    .io_src1         (_pipeB_control_io_src1),
    .io_src2         (_pipeB_control_io_src2),
    .io_branch       (_pipeB_control_io_branch),
    .io_jumptype     (_pipeB_control_io_jumptype),
    .io_resultselect (_pipeB_control_io_resultselect),
    .io_memop        (_pipeB_control_io_memop),
    .io_toreg        (_pipeB_control_io_toreg),
    .io_regwrite     (_pipeB_control_io_regwrite),
    .io_wordinst     (_pipeB_control_io_wordinst)
  );
  ImmediateGenerator pipeA_immGen (
    .io_instruction (pipeA_immGen_io_instruction),
    .io_sextImm     (_pipeA_immGen_io_sextImm)
  );
  ImmediateGenerator pipeB_immGen (
    .io_instruction (pipeB_immGen_io_instruction),
    .io_sextImm     (_pipeB_immGen_io_sextImm)
  );
  ALUControl pipeA_aluControl (
    .io_aluop     (_pipeA_id_ex_ctrl_io_data_ex_ctrl_aluop),
    .io_itype     (_pipeA_id_ex_ctrl_io_data_ex_ctrl_itype),
    .io_funct7    (_pipeA_id_ex_io_data_instruction[31:25]),
    .io_funct3    (_pipeA_id_ex_io_data_instruction[14:12]),
    .io_wordinst  (_pipeA_id_ex_ctrl_io_data_ex_ctrl_wordinst),
    .io_operation (_pipeA_aluControl_io_operation)
  );
  ALUControl pipeB_aluControl (
    .io_aluop     (_pipeB_id_ex_ctrl_io_data_ex_ctrl_aluop),
    .io_itype     (_pipeB_id_ex_ctrl_io_data_ex_ctrl_itype),
    .io_funct7    (_pipeB_id_ex_io_data_instruction[31:25]),
    .io_funct3    (_pipeB_id_ex_io_data_instruction[14:12]),
    .io_wordinst  (_pipeB_id_ex_ctrl_io_data_ex_ctrl_wordinst),
    .io_operation (_pipeB_aluControl_io_operation)
  );
  ALU pipeA_alu (
    .io_operation (_pipeA_aluControl_io_operation),
    .io_inputx
      (_pipeA_id_ex_ctrl_io_data_ex_ctrl_src1 ? _pipeA_id_ex_io_data_pc : casez_tmp),
    .io_inputy
      (_pipeA_id_ex_ctrl_io_data_ex_ctrl_src2 == 2'h0
         ? casez_tmp_0
         : _pipeA_id_ex_ctrl_io_data_ex_ctrl_src2 == 2'h1
             ? _pipeA_id_ex_io_data_sextImm
             : {61'h0, _pipeA_id_ex_ctrl_io_data_ex_ctrl_src2 == 2'h2, 2'h0}),
    .io_result    (_pipeA_alu_io_result)
  );
  ALU pipeB_alu (
    .io_operation (_pipeB_aluControl_io_operation),
    .io_inputx
      (_pipeB_id_ex_ctrl_io_data_ex_ctrl_src1 ? _pipeB_id_ex_io_data_pc : casez_tmp_1),
    .io_inputy
      (_pipeB_id_ex_ctrl_io_data_ex_ctrl_src2 == 2'h0
         ? casez_tmp_2
         : _pipeB_id_ex_ctrl_io_data_ex_ctrl_src2 == 2'h1
             ? _pipeB_id_ex_io_data_sextImm
             : {61'h0, _pipeB_id_ex_ctrl_io_data_ex_ctrl_src2 == 2'h2, 2'h0}),
    .io_result    (_pipeB_alu_io_result)
  );
  DualIssueNextPC nextPCmod (
    .io_branch
      (_pipeB_id_ex_io_data_isValid
         ? _pipeB_id_ex_ctrl_io_data_ex_ctrl_branch
         : _pipeA_id_ex_ctrl_io_data_ex_ctrl_branch),
    .io_jumptype
      (_pipeB_id_ex_io_data_isValid
         ? _pipeB_id_ex_ctrl_io_data_ex_ctrl_jumptype
         : _pipeA_id_ex_ctrl_io_data_ex_ctrl_jumptype),
    .io_inputx      (_pipeB_id_ex_io_data_isValid ? casez_tmp_1 : casez_tmp),
    .io_inputy      (_pipeB_id_ex_io_data_isValid ? casez_tmp_2 : casez_tmp_0),
    .io_funct3
      (_pipeB_id_ex_io_data_isValid
         ? _pipeB_id_ex_io_data_instruction[14:12]
         : _pipeA_id_ex_io_data_instruction[14:12]),
    .io_pc
      (_pipeB_id_ex_io_data_isValid ? _pipeB_id_ex_io_data_pc : _pipeA_id_ex_io_data_pc),
    .io_imm
      (_pipeB_id_ex_io_data_isValid
         ? _pipeB_id_ex_io_data_sextImm
         : _pipeA_id_ex_io_data_sextImm),
    .io_pipeB_valid (_pipeB_id_ex_io_data_isValid),
    .io_nextpc      (_nextPCmod_io_nextpc),
    .io_taken       (_nextPCmod_io_taken)
  );
  DualIssueForwardingUnit forwarding (
    .io_ex_pipeA_rs1   (_pipeA_id_ex_io_data_instruction[19:15]),
    .io_ex_pipeA_rs2   (_pipeA_id_ex_io_data_instruction[24:20]),
    .io_ex_pipeB_rs1   (_pipeB_id_ex_io_data_instruction[19:15]),
    .io_ex_pipeB_rs2   (_pipeB_id_ex_io_data_instruction[24:20]),
    .io_mem_pipeA_rd   (_pipeA_ex_mem_io_data_instruction[11:7]),
    .io_mem_pipeA_rw   (_pipeA_ex_mem_ctrl_io_data_wb_ctrl_regwrite),
    .io_mem_pipeB_rd   (_pipeB_ex_mem_io_data_instruction[11:7]),
    .io_mem_pipeB_rw   (_pipeB_ex_mem_ctrl_io_data_wb_ctrl_regwrite),
    .io_wb_pipeA_rd    (_pipeA_mem_wb_io_data_instruction[11:7]),
    .io_wb_pipeA_rw    (_pipeA_mem_wb_ctrl_io_data_wb_ctrl_regwrite),
    .io_wb_pipeB_rd    (_pipeB_mem_wb_io_data_instruction[11:7]),
    .io_wb_pipeB_rw    (_pipeB_mem_wb_ctrl_io_data_wb_ctrl_regwrite),
    .io_pipeA_forward1 (_forwarding_io_pipeA_forward1),
    .io_pipeA_forward2 (_forwarding_io_pipeA_forward2),
    .io_pipeB_forward1 (_forwarding_io_pipeB_forward1),
    .io_pipeB_forward2 (_forwarding_io_pipeB_forward2)
  );
  DualIssueHazardUnit hazard (
    .io_id_pipeA_rs1       (_pipeA_if_id_io_data_instruction[19:15]),
    .io_id_pipeA_rs2       (_pipeA_if_id_io_data_instruction[24:20]),
    .io_id_pipeB_rs1       (_pipeB_if_id_io_data_instruction[19:15]),
    .io_id_pipeB_rs2       (_pipeB_if_id_io_data_instruction[24:20]),
    .io_pipeA_idex_memread (_pipeA_id_ex_ctrl_io_data_mem_ctrl_memop == 2'h2),
    .io_pipeA_idex_rd      (_pipeA_id_ex_io_data_instruction[11:7]),
    .io_pipeA_exmem_taken  (_pipeA_ex_mem_io_data_taken),
    .io_pipeB_idex_memread (_pipeB_id_ex_ctrl_io_data_mem_ctrl_memop == 2'h2),
    .io_pipeB_idex_rd      (_pipeB_id_ex_io_data_instruction[11:7]),
    .io_pipeB_exmem_taken  (_pipeB_ex_mem_io_data_taken),
    .io_pcfromtaken        (_hazard_io_pcfromtaken),
    .io_pcstall            (_hazard_io_pcstall),
    .io_if_id_stall        (_hazard_io_if_id_stall),
    .io_id_ex_flush        (_hazard_io_id_ex_flush),
    .io_ex_mem_flush       (_hazard_io_ex_mem_flush),
    .io_if_id_flush        (_hazard_io_if_id_flush)
  );
  StageReg pipeA_if_id (
    .clock               (clock),
    .reset               (reset),
    .io_in_instruction   (_issueUnit_io_pipeA_inst),
    .io_in_pc            (pc),
    .io_in_isValid       (1'h1),
    .io_flush            (_hazard_io_if_id_flush),
    .io_valid            (~_hazard_io_if_id_stall),
    .io_data_instruction (_pipeA_if_id_io_data_instruction),
    .io_data_pc          (_pipeA_if_id_io_data_pc),
    .io_data_isValid     (_pipeA_if_id_io_data_isValid)
  );
  StageReg pipeB_if_id (
    .clock               (clock),
    .reset               (reset),
    .io_in_instruction   (_issueUnit_io_pipeB_inst),
    .io_in_pc            (pc + 64'h4),
    .io_in_isValid       (_issueUnit_io_pipeB_valid),
    .io_flush            (_hazard_io_if_id_flush),
    .io_valid            (~_hazard_io_if_id_stall),
    .io_data_instruction (_pipeB_if_id_io_data_instruction),
    .io_data_pc          (_pipeB_if_id_io_data_pc),
    .io_data_isValid     (_pipeB_if_id_io_data_isValid)
  );
  StageReg_2 pipeA_id_ex (
    .clock               (clock),
    .reset               (reset),
    .io_in_pc            (_pipeA_if_id_io_data_pc),
    .io_in_instruction   (pipeA_immGen_io_instruction),
    .io_in_sextImm       (_pipeA_immGen_io_sextImm),
    .io_in_readdata1     (_registers_io_pipeA_readdata1),
    .io_in_readdata2     (_registers_io_pipeA_readdata2),
    .io_in_isValid       (_pipeA_if_id_io_data_isValid),
    .io_flush            (_hazard_io_id_ex_flush),
    .io_data_pc          (_pipeA_id_ex_io_data_pc),
    .io_data_instruction (_pipeA_id_ex_io_data_instruction),
    .io_data_sextImm     (_pipeA_id_ex_io_data_sextImm),
    .io_data_readdata1   (_pipeA_id_ex_io_data_readdata1),
    .io_data_readdata2   (_pipeA_id_ex_io_data_readdata2),
    .io_data_isValid     (_pipeA_id_ex_io_data_isValid)
  );
  StageReg_2 pipeB_id_ex (
    .clock               (clock),
    .reset               (reset),
    .io_in_pc            (_pipeB_if_id_io_data_pc),
    .io_in_instruction   (pipeB_immGen_io_instruction),
    .io_in_sextImm       (_pipeB_immGen_io_sextImm),
    .io_in_readdata1     (_registers_io_pipeB_readdata1),
    .io_in_readdata2     (_registers_io_pipeB_readdata2),
    .io_in_isValid       (_pipeB_if_id_io_data_isValid),
    .io_flush            (_hazard_io_id_ex_flush),
    .io_data_pc          (_pipeB_id_ex_io_data_pc),
    .io_data_instruction (_pipeB_id_ex_io_data_instruction),
    .io_data_sextImm     (_pipeB_id_ex_io_data_sextImm),
    .io_data_readdata1   (_pipeB_id_ex_io_data_readdata1),
    .io_data_readdata2   (_pipeB_id_ex_io_data_readdata2),
    .io_data_isValid     (_pipeB_id_ex_io_data_isValid)
  );
  StageReg_4 pipeA_id_ex_ctrl (
    .clock                        (clock),
    .reset                        (reset),
    .io_in_ex_ctrl_itype          (_pipeA_control_io_itype),
    .io_in_ex_ctrl_aluop          (_pipeA_control_io_aluop),
    .io_in_ex_ctrl_src1           (_pipeA_control_io_src1),
    .io_in_ex_ctrl_src2           (_pipeA_control_io_src2),
    .io_in_ex_ctrl_branch         (_pipeA_control_io_branch),
    .io_in_ex_ctrl_jumptype       (_pipeA_control_io_jumptype),
    .io_in_ex_ctrl_resultselect   (_pipeA_control_io_resultselect),
    .io_in_ex_ctrl_wordinst       (_pipeA_control_io_wordinst),
    .io_in_mem_ctrl_memop         (_pipeA_control_io_memop),
    .io_in_wb_ctrl_toreg          (_pipeA_control_io_toreg),
    .io_in_wb_ctrl_regwrite       (_pipeA_control_io_regwrite),
    .io_flush                     (_hazard_io_id_ex_flush),
    .io_data_ex_ctrl_itype        (_pipeA_id_ex_ctrl_io_data_ex_ctrl_itype),
    .io_data_ex_ctrl_aluop        (_pipeA_id_ex_ctrl_io_data_ex_ctrl_aluop),
    .io_data_ex_ctrl_src1         (_pipeA_id_ex_ctrl_io_data_ex_ctrl_src1),
    .io_data_ex_ctrl_src2         (_pipeA_id_ex_ctrl_io_data_ex_ctrl_src2),
    .io_data_ex_ctrl_branch       (_pipeA_id_ex_ctrl_io_data_ex_ctrl_branch),
    .io_data_ex_ctrl_jumptype     (_pipeA_id_ex_ctrl_io_data_ex_ctrl_jumptype),
    .io_data_ex_ctrl_resultselect (_pipeA_id_ex_ctrl_io_data_ex_ctrl_resultselect),
    .io_data_ex_ctrl_wordinst     (_pipeA_id_ex_ctrl_io_data_ex_ctrl_wordinst),
    .io_data_mem_ctrl_memop       (_pipeA_id_ex_ctrl_io_data_mem_ctrl_memop),
    .io_data_wb_ctrl_toreg        (_pipeA_id_ex_ctrl_io_data_wb_ctrl_toreg),
    .io_data_wb_ctrl_regwrite     (_pipeA_id_ex_ctrl_io_data_wb_ctrl_regwrite)
  );
  StageReg_4 pipeB_id_ex_ctrl (
    .clock                        (clock),
    .reset                        (reset),
    .io_in_ex_ctrl_itype          (_pipeB_control_io_itype),
    .io_in_ex_ctrl_aluop          (_pipeB_control_io_aluop),
    .io_in_ex_ctrl_src1           (_pipeB_control_io_src1),
    .io_in_ex_ctrl_src2           (_pipeB_control_io_src2),
    .io_in_ex_ctrl_branch         (_pipeB_control_io_branch),
    .io_in_ex_ctrl_jumptype       (_pipeB_control_io_jumptype),
    .io_in_ex_ctrl_resultselect   (_pipeB_control_io_resultselect),
    .io_in_ex_ctrl_wordinst       (_pipeB_control_io_wordinst),
    .io_in_mem_ctrl_memop         (_pipeB_control_io_memop),
    .io_in_wb_ctrl_toreg          (_pipeB_control_io_toreg),
    .io_in_wb_ctrl_regwrite       (_pipeB_control_io_regwrite),
    .io_flush                     (_hazard_io_id_ex_flush),
    .io_data_ex_ctrl_itype        (_pipeB_id_ex_ctrl_io_data_ex_ctrl_itype),
    .io_data_ex_ctrl_aluop        (_pipeB_id_ex_ctrl_io_data_ex_ctrl_aluop),
    .io_data_ex_ctrl_src1         (_pipeB_id_ex_ctrl_io_data_ex_ctrl_src1),
    .io_data_ex_ctrl_src2         (_pipeB_id_ex_ctrl_io_data_ex_ctrl_src2),
    .io_data_ex_ctrl_branch       (_pipeB_id_ex_ctrl_io_data_ex_ctrl_branch),
    .io_data_ex_ctrl_jumptype     (_pipeB_id_ex_ctrl_io_data_ex_ctrl_jumptype),
    .io_data_ex_ctrl_resultselect (_pipeB_id_ex_ctrl_io_data_ex_ctrl_resultselect),
    .io_data_ex_ctrl_wordinst     (_pipeB_id_ex_ctrl_io_data_ex_ctrl_wordinst),
    .io_data_mem_ctrl_memop       (_pipeB_id_ex_ctrl_io_data_mem_ctrl_memop),
    .io_data_wb_ctrl_toreg        (_pipeB_id_ex_ctrl_io_data_wb_ctrl_toreg),
    .io_data_wb_ctrl_regwrite     (_pipeB_id_ex_ctrl_io_data_wb_ctrl_regwrite)
  );
  StageReg_6 pipeA_ex_mem (
    .clock                 (clock),
    .reset                 (reset),
    .io_in_ex_result
      (_pipeA_id_ex_ctrl_io_data_ex_ctrl_resultselect
         ? _pipeA_id_ex_io_data_sextImm
         : _pipeA_alu_io_result),
    .io_in_mem_writedata   (casez_tmp_0),
    .io_in_nextpc          (_pipeB_id_ex_io_data_isValid ? 64'h0 : _nextPCmod_io_nextpc),
    .io_in_taken           (~_pipeB_id_ex_io_data_isValid & _nextPCmod_io_taken),
    .io_in_instruction     (_pipeA_id_ex_io_data_instruction),
    .io_in_isValid         (_pipeA_id_ex_io_data_isValid),
    .io_flush              (_hazard_io_ex_mem_flush),
    .io_data_ex_result     (_pipeA_ex_mem_io_data_ex_result),
    .io_data_mem_writedata (_pipeA_ex_mem_io_data_mem_writedata),
    .io_data_nextpc        (_pipeA_ex_mem_io_data_nextpc),
    .io_data_taken         (_pipeA_ex_mem_io_data_taken),
    .io_data_instruction   (_pipeA_ex_mem_io_data_instruction),
    .io_data_isValid       (/* unused */)
  );
  StageReg_6 pipeB_ex_mem (
    .clock                 (clock),
    .reset                 (reset),
    .io_in_ex_result
      (_pipeB_id_ex_ctrl_io_data_ex_ctrl_resultselect
         ? _pipeB_id_ex_io_data_sextImm
         : _pipeB_alu_io_result),
    .io_in_mem_writedata   (casez_tmp_2),
    .io_in_nextpc          (_pipeB_id_ex_io_data_isValid ? _nextPCmod_io_nextpc : 64'h0),
    .io_in_taken           (_pipeB_id_ex_io_data_isValid & _nextPCmod_io_taken),
    .io_in_instruction     (_pipeB_id_ex_io_data_instruction),
    .io_in_isValid         (_pipeB_id_ex_io_data_isValid),
    .io_flush              (_hazard_io_ex_mem_flush),
    .io_data_ex_result     (_pipeB_ex_mem_io_data_ex_result),
    .io_data_mem_writedata (_pipeB_ex_mem_io_data_mem_writedata),
    .io_data_nextpc        (_pipeB_ex_mem_io_data_nextpc),
    .io_data_taken         (_pipeB_ex_mem_io_data_taken),
    .io_data_instruction   (_pipeB_ex_mem_io_data_instruction),
    .io_data_isValid       (_pipeB_ex_mem_io_data_isValid)
  );
  StageReg_8 pipeA_ex_mem_ctrl (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_mem_ctrl_memop     (_pipeA_id_ex_ctrl_io_data_mem_ctrl_memop),
    .io_in_wb_ctrl_toreg      (_pipeA_id_ex_ctrl_io_data_wb_ctrl_toreg),
    .io_in_wb_ctrl_regwrite   (_pipeA_id_ex_ctrl_io_data_wb_ctrl_regwrite),
    .io_flush                 (_hazard_io_ex_mem_flush),
    .io_data_mem_ctrl_memop   (_pipeA_ex_mem_ctrl_io_data_mem_ctrl_memop),
    .io_data_wb_ctrl_toreg    (_pipeA_ex_mem_ctrl_io_data_wb_ctrl_toreg),
    .io_data_wb_ctrl_regwrite (_pipeA_ex_mem_ctrl_io_data_wb_ctrl_regwrite)
  );
  StageReg_8 pipeB_ex_mem_ctrl (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_mem_ctrl_memop     (_pipeB_id_ex_ctrl_io_data_mem_ctrl_memop),
    .io_in_wb_ctrl_toreg      (_pipeB_id_ex_ctrl_io_data_wb_ctrl_toreg),
    .io_in_wb_ctrl_regwrite   (_pipeB_id_ex_ctrl_io_data_wb_ctrl_regwrite),
    .io_flush                 (_hazard_io_ex_mem_flush),
    .io_data_mem_ctrl_memop   (_pipeB_ex_mem_ctrl_io_data_mem_ctrl_memop),
    .io_data_wb_ctrl_toreg    (_pipeB_ex_mem_ctrl_io_data_wb_ctrl_toreg),
    .io_data_wb_ctrl_regwrite (_pipeB_ex_mem_ctrl_io_data_wb_ctrl_regwrite)
  );
  StageReg_10 pipeA_mem_wb (
    .clock               (clock),
    .reset               (reset),
    .io_in_readdata      (io_dmem_readdata),
    .io_in_ex_result     (_pipeA_ex_mem_io_data_ex_result),
    .io_in_instruction   (_pipeA_ex_mem_io_data_instruction),
    .io_data_readdata    (_pipeA_mem_wb_io_data_readdata),
    .io_data_ex_result   (_pipeA_mem_wb_io_data_ex_result),
    .io_data_instruction (_pipeA_mem_wb_io_data_instruction)
  );
  StageReg_10 pipeB_mem_wb (
    .clock               (clock),
    .reset               (reset),
    .io_in_readdata      (io_dmem_readdata),
    .io_in_ex_result     (_pipeB_ex_mem_io_data_ex_result),
    .io_in_instruction   (_pipeB_ex_mem_io_data_instruction),
    .io_data_readdata    (_pipeB_mem_wb_io_data_readdata),
    .io_data_ex_result   (_pipeB_mem_wb_io_data_ex_result),
    .io_data_instruction (_pipeB_mem_wb_io_data_instruction)
  );
  StageReg_12 pipeA_mem_wb_ctrl (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_wb_ctrl_toreg      (_pipeA_ex_mem_ctrl_io_data_wb_ctrl_toreg),
    .io_in_wb_ctrl_regwrite   (_pipeA_ex_mem_ctrl_io_data_wb_ctrl_regwrite),
    .io_data_wb_ctrl_toreg    (_pipeA_mem_wb_ctrl_io_data_wb_ctrl_toreg),
    .io_data_wb_ctrl_regwrite (_pipeA_mem_wb_ctrl_io_data_wb_ctrl_regwrite)
  );
  StageReg_12 pipeB_mem_wb_ctrl (
    .clock                    (clock),
    .reset                    (reset),
    .io_in_wb_ctrl_toreg      (_pipeB_ex_mem_ctrl_io_data_wb_ctrl_toreg),
    .io_in_wb_ctrl_regwrite   (_pipeB_ex_mem_ctrl_io_data_wb_ctrl_regwrite),
    .io_data_wb_ctrl_toreg    (_pipeB_mem_wb_ctrl_io_data_wb_ctrl_toreg),
    .io_data_wb_ctrl_regwrite (_pipeB_mem_wb_ctrl_io_data_wb_ctrl_regwrite)
  );
  assign io_imem_address = pc;
  assign io_imem_valid = 1'h1;
  assign io_dmem_address =
    _pipeB_ex_mem_io_data_isValid
      ? _pipeB_ex_mem_io_data_ex_result
      : _pipeA_ex_mem_io_data_ex_result;
  assign io_dmem_valid =
    _pipeB_ex_mem_io_data_isValid
      ? _pipeB_ex_mem_ctrl_io_data_mem_ctrl_memop[1]
      : _pipeA_ex_mem_ctrl_io_data_mem_ctrl_memop[1];
  assign io_dmem_writedata =
    _pipeB_ex_mem_io_data_isValid
      ? _pipeB_ex_mem_io_data_mem_writedata
      : _pipeA_ex_mem_io_data_mem_writedata;
  assign io_dmem_memread =
    _pipeB_ex_mem_io_data_isValid
      ? ~(_pipeB_ex_mem_ctrl_io_data_mem_ctrl_memop[0])
      : ~(_pipeA_ex_mem_ctrl_io_data_mem_ctrl_memop[0]);
  assign io_dmem_memwrite =
    _pipeB_ex_mem_io_data_isValid
      ? _pipeB_ex_mem_ctrl_io_data_mem_ctrl_memop[0]
      : _pipeA_ex_mem_ctrl_io_data_mem_ctrl_memop[0];
  assign io_dmem_maskmode =
    _pipeB_ex_mem_io_data_isValid
      ? _pipeB_ex_mem_io_data_instruction[13:12]
      : _pipeA_ex_mem_io_data_instruction[13:12];
  assign io_dmem_sext =
    _pipeB_ex_mem_io_data_isValid
      ? ~(_pipeB_ex_mem_io_data_instruction[14])
      : ~(_pipeA_ex_mem_io_data_instruction[14]);
endmodule

