// Generated by CIRCT firtool-1.114.1
module StageReg_10(
  input         clock,
                reset,
  input  [63:0] io_in_readdata,
                io_in_ex_result,
                io_in_instruction,
  output [63:0] io_data_readdata,
                io_data_ex_result,
                io_data_instruction
);

  reg [63:0] reg_readdata;
  reg [63:0] reg_ex_result;
  reg [63:0] reg_instruction;
  always @(posedge clock) begin
    if (reset) begin
      reg_readdata <= 64'h0;
      reg_ex_result <= 64'h0;
      reg_instruction <= 64'h0;
    end
    else begin
      reg_readdata <= io_in_readdata;
      reg_ex_result <= io_in_ex_result;
      reg_instruction <= io_in_instruction;
    end
  end // always @(posedge)
  assign io_data_readdata = reg_readdata;
  assign io_data_ex_result = reg_ex_result;
  assign io_data_instruction = reg_instruction;
endmodule

