// Generated by CIRCT firtool-1.114.1
module StageReg_4(
  input        clock,
               reset,
               io_in_ex_ctrl_itype,
               io_in_ex_ctrl_aluop,
               io_in_ex_ctrl_src1,
  input  [1:0] io_in_ex_ctrl_src2,
  input        io_in_ex_ctrl_branch,
  input  [1:0] io_in_ex_ctrl_jumptype,
  input        io_in_ex_ctrl_resultselect,
               io_in_ex_ctrl_wordinst,
  input  [1:0] io_in_mem_ctrl_memop,
  input        io_in_wb_ctrl_toreg,
               io_in_wb_ctrl_regwrite,
               io_flush,
  output       io_data_ex_ctrl_itype,
               io_data_ex_ctrl_aluop,
               io_data_ex_ctrl_src1,
  output [1:0] io_data_ex_ctrl_src2,
  output       io_data_ex_ctrl_branch,
  output [1:0] io_data_ex_ctrl_jumptype,
  output       io_data_ex_ctrl_resultselect,
               io_data_ex_ctrl_wordinst,
  output [1:0] io_data_mem_ctrl_memop,
  output       io_data_wb_ctrl_toreg,
               io_data_wb_ctrl_regwrite
);

  reg       reg_ex_ctrl_itype;
  reg       reg_ex_ctrl_aluop;
  reg       reg_ex_ctrl_src1;
  reg [1:0] reg_ex_ctrl_src2;
  reg       reg_ex_ctrl_branch;
  reg [1:0] reg_ex_ctrl_jumptype;
  reg       reg_ex_ctrl_resultselect;
  reg       reg_ex_ctrl_wordinst;
  reg [1:0] reg_mem_ctrl_memop;
  reg       reg_wb_ctrl_toreg;
  reg       reg_wb_ctrl_regwrite;
  always @(posedge clock) begin
    if (reset) begin
      reg_ex_ctrl_itype <= 1'h0;
      reg_ex_ctrl_aluop <= 1'h0;
      reg_ex_ctrl_src1 <= 1'h0;
      reg_ex_ctrl_src2 <= 2'h0;
      reg_ex_ctrl_branch <= 1'h0;
      reg_ex_ctrl_jumptype <= 2'h0;
      reg_ex_ctrl_resultselect <= 1'h0;
      reg_ex_ctrl_wordinst <= 1'h0;
      reg_mem_ctrl_memop <= 2'h0;
      reg_wb_ctrl_toreg <= 1'h0;
      reg_wb_ctrl_regwrite <= 1'h0;
    end
    else begin
      reg_ex_ctrl_itype <= ~io_flush & io_in_ex_ctrl_itype;
      reg_ex_ctrl_aluop <= ~io_flush & io_in_ex_ctrl_aluop;
      reg_ex_ctrl_src1 <= ~io_flush & io_in_ex_ctrl_src1;
      reg_ex_ctrl_src2 <= io_flush ? 2'h0 : io_in_ex_ctrl_src2;
      reg_ex_ctrl_branch <= ~io_flush & io_in_ex_ctrl_branch;
      reg_ex_ctrl_jumptype <= io_flush ? 2'h0 : io_in_ex_ctrl_jumptype;
      reg_ex_ctrl_resultselect <= ~io_flush & io_in_ex_ctrl_resultselect;
      reg_ex_ctrl_wordinst <= ~io_flush & io_in_ex_ctrl_wordinst;
      reg_mem_ctrl_memop <= io_flush ? 2'h0 : io_in_mem_ctrl_memop;
      reg_wb_ctrl_toreg <= ~io_flush & io_in_wb_ctrl_toreg;
      reg_wb_ctrl_regwrite <= ~io_flush & io_in_wb_ctrl_regwrite;
    end
  end // always @(posedge)
  assign io_data_ex_ctrl_itype = reg_ex_ctrl_itype;
  assign io_data_ex_ctrl_aluop = reg_ex_ctrl_aluop;
  assign io_data_ex_ctrl_src1 = reg_ex_ctrl_src1;
  assign io_data_ex_ctrl_src2 = reg_ex_ctrl_src2;
  assign io_data_ex_ctrl_branch = reg_ex_ctrl_branch;
  assign io_data_ex_ctrl_jumptype = reg_ex_ctrl_jumptype;
  assign io_data_ex_ctrl_resultselect = reg_ex_ctrl_resultselect;
  assign io_data_ex_ctrl_wordinst = reg_ex_ctrl_wordinst;
  assign io_data_mem_ctrl_memop = reg_mem_ctrl_memop;
  assign io_data_wb_ctrl_toreg = reg_wb_ctrl_toreg;
  assign io_data_wb_ctrl_regwrite = reg_wb_ctrl_regwrite;
endmodule

