// This file is distributed under the BSD 3-Clause License. See LICENSE for details.
#include "legacy_model.hpp"

#include <stdexcept>

#include "emit_legacy_cert_wf.hpp"
#include "emit_legacy_fast_bridge.hpp"
#include "emit_legacy_fast_model.hpp"
#include "emit_legacy_graph_cert.hpp"
#include "emit_legacy_schema.hpp"
namespace lean_export {
void emit_legacy_model(const DesignScan& design, const CertificateIR& cert, const LegacyEmitOptions& options, std::ostream& out) {
  if (options.emit_fast_bridge && !options.emit_cert) {
    throw std::invalid_argument("emit_fast_bridge requires emit_cert=true");
  }
  const auto names       = legacy_names(design, options.top);
  const bool wf          = options.emit_cert && options.cert_wf != LeanCertWFMode::Skip;
  const bool lookup_tree = options.emit_fast_bridge || wf;
  out << "/-\n  Generated by LiveHD pass.lean from the shared CertificateIR.\n"
         "  Fast executable model and legacy GraphCert are optional presentations.\n-/\n\n";
  if (options.emit_fast_bridge && needs_nary_bridge(cert)) {
    out << "import LeanSemanticPrimitives.Translation.NaryBridge\n";
  }
  if (wf) {
    out << "import LeanSemanticPrimitives.Translation.LegacyCertWF\n\nopen OpBridge\n\n";
  } else if (names.memory_values || options.emit_fast_bridge) {
    out << "import LeanSemanticPrimitives.Translation.OpBridge\n\nopen OpBridge\n\n";
  } else {
    out << "import LeanSemanticPrimitives\n\n";
  }
  out << "set_option linter.unusedVariables false\n";
  if (options.emit_fast_bridge) {
    out << "set_option linter.unusedSimpArgs false\nset_option linter.unreachableTactic false\nset_option linter.unusedTactic "
           "false\n";
  }
  out << "\nset_option maxRecDepth 1000000\nset_option maxHeartbeats 0\n\nnamespace " << names.base << "_Lgraph\n\n";
  emit_legacy_schema(design, names, out);
  emit_legacy_fast_model(design, cert, names, options.emit_fast_bridge, out);
  if (options.emit_cert) {
    emit_legacy_graph_cert(design, cert, names, lookup_tree, out);
    emit_legacy_cert_wf(cert, names, options, out);
    if (options.emit_fast_bridge) {
      emit_legacy_fast_bridge(design, cert, names, out);
    }
  } else {
    out << "-- Certificate emission disabled by lean.emit_cert=false.\n";
  }
  emit_legacy_field_mapping(design, names, out);
  out << "end " << names.base << "_Lgraph\n";
}
}  // namespace lean_export
