# This file is distributed under the BSD 3-Clause License. See LICENSE for details.

# load("@rules_cc//cc:defs.bzl", "cc_library")

# cc_library(
#     name = "pass_opentimer",
#     srcs = glob(
#         ["*.cpp"],
#         exclude = ["*test*.cpp"],
#     ),
#     hdrs = glob(["*.hpp"]),
#     includes = ["."],
#     visibility = ["//visibility:public"],
#     deps = [
#         "//core",
#         "@opentimer",
#     ],
# )
