cc_library(
    name = "inou_rand",
    srcs = ["inou_rand.cpp"],
    hdrs = glob(["*.hpp"]),
    visibility = ["//visibility:public"],
    includes = ["."],
    deps = [
        "//meta:meta",
        "//pyth:py_base",
    ],
)

