// Generated by CIRCT firtool-1.114.1

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module DualIssueIssueUnit(
  input         clock,
                reset,
  input  [63:0] io_pc,
                io_inst,
  output [63:0] io_nextpc,
  output [31:0] io_pipeA_inst,
                io_pipeB_inst,
  output        io_pipeB_valid
);

  wire [63:0] _oddPC_T = {61'h0, io_pc[2:0]};
  wire        _inst2_regs_T_1 = io_inst[38:32] == 7'h33;
  wire        _inst2_regs_T_3 = io_inst[38:32] == 7'h13;
  wire        _inst2_regs_T_5 = io_inst[38:32] == 7'h3;
  wire        _inst2_regs_T_11 = io_inst[38:32] == 7'h37;
  wire        _inst2_regs_T_13 = io_inst[38:32] == 7'h17;
  wire        _inst2_regs_T_15 = io_inst[38:32] == 7'h6F;
  wire        _inst2_regs_T_42 = io_inst[38:32] == 7'h3B;
  wire        _GEN = io_inst[38:32] == 7'h67 | io_inst[38:32] == 7'h1B;
  wire        _GEN_0 = io_inst[38:32] == 7'h23 | io_inst[38:32] == 7'h63;
  wire        will_issue_inst1 = _oddPC_T[3:0] != 4'h4;
  wire        will_issue_inst2 =
    _oddPC_T[3:0] == 4'h4
    | ~(io_inst[6:0] == 7'h3 | io_inst[6:0] == 7'h23 | io_inst[6:0] == 7'h63
        | io_inst[6:0] == 7'h6F | io_inst[6:0] == 7'h67)
    & (~((io_inst[6:0] == 7'h33 | io_inst[6:0] == 7'h13 | io_inst[6:0] == 7'h3
          | ~(io_inst[6:0] == 7'h23 | io_inst[6:0] == 7'h63)
          & (io_inst[6:0] == 7'h37 | io_inst[6:0] == 7'h17 | io_inst[6:0] == 7'h6F
             | io_inst[6:0] == 7'h67 | io_inst[6:0] == 7'h1B | io_inst[6:0] == 7'h3B))
         & (|(io_inst[11:7])))
       | ~((_inst2_regs_T_1 | _inst2_regs_T_3 | _inst2_regs_T_5 | _GEN_0
            | ~(_inst2_regs_T_11 | _inst2_regs_T_13 | _inst2_regs_T_15)
            & (_GEN | _inst2_regs_T_42)) & io_inst[11:7] == io_inst[51:47]
           | (_inst2_regs_T_1 | ~(_inst2_regs_T_3 | _inst2_regs_T_5)
              & (_GEN_0 | ~(_inst2_regs_T_11 | _inst2_regs_T_13 | _inst2_regs_T_15 | _GEN)
                 & _inst2_regs_T_42)) & io_inst[11:7] == io_inst[56:52]));
  `ifndef SYNTHESIS
    always @(posedge clock) begin
      if (~reset & ~(will_issue_inst1 | will_issue_inst2)) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed at issue.scala:106\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign io_nextpc =
    will_issue_inst1 ? (will_issue_inst2 ? io_pc + 64'h8 : io_pc + 64'h4) : io_pc + 64'h4;
  assign io_pipeA_inst = will_issue_inst1 ? io_inst[31:0] : io_inst[63:32];
  assign io_pipeB_inst = will_issue_inst1 & will_issue_inst2 ? io_inst[63:32] : 32'h13;
  assign io_pipeB_valid = will_issue_inst1 & will_issue_inst2;
endmodule

