// Generated by CIRCT firtool-1.114.1
module ImmediateGenerator(
  input  [63:0] io_instruction,
  output [63:0] io_sextImm
);

  assign io_sextImm =
    io_instruction[6:0] == 7'h37
      ? {{32{io_instruction[31]}}, io_instruction[31:12], 12'h0}
      : io_instruction[6:0] == 7'h17
          ? {{32{io_instruction[31]}}, io_instruction[31:12], 12'h0}
          : io_instruction[6:0] == 7'h6F
              ? {{44{io_instruction[31]}},
                 io_instruction[19:12],
                 io_instruction[20],
                 io_instruction[30:21],
                 1'h0}
              : io_instruction[6:0] == 7'h67
                  ? {{52{io_instruction[31]}}, io_instruction[31:20]}
                  : io_instruction[6:0] == 7'h63
                      ? {{52{io_instruction[31]}},
                         io_instruction[7],
                         io_instruction[30:25],
                         io_instruction[11:8],
                         1'h0}
                      : io_instruction[6:0] == 7'h3
                          ? {{52{io_instruction[31]}}, io_instruction[31:20]}
                          : io_instruction[6:0] == 7'h23
                              ? {{52{io_instruction[31]}},
                                 io_instruction[31:25],
                                 io_instruction[11:7]}
                              : io_instruction[6:0] == 7'h13
                                  ? {{52{io_instruction[31]}}, io_instruction[31:20]}
                                  : io_instruction[6:0] == 7'h1B
                                      ? {{52{io_instruction[31]}}, io_instruction[31:20]}
                                      : io_instruction[6:0] == 7'h73
                                          ? {59'h0, io_instruction[19:15]}
                                          : 64'h0;
endmodule

