// Generated by CIRCT firtool-1.114.1
module StageReg_2(
  input         clock,
                reset,
  input  [63:0] io_in_pc,
                io_in_instruction,
                io_in_sextImm,
                io_in_readdata1,
                io_in_readdata2,
  input         io_in_isValid,
                io_flush,
  output [63:0] io_data_pc,
                io_data_instruction,
                io_data_sextImm,
                io_data_readdata1,
                io_data_readdata2,
  output        io_data_isValid
);

  reg [63:0] reg_pc;
  reg [63:0] reg_instruction;
  reg [63:0] reg_sextImm;
  reg [63:0] reg_readdata1;
  reg [63:0] reg_readdata2;
  reg        reg_isValid;
  always @(posedge clock) begin
    if (reset) begin
      reg_pc <= 64'h0;
      reg_instruction <= 64'h0;
      reg_sextImm <= 64'h0;
      reg_readdata1 <= 64'h0;
      reg_readdata2 <= 64'h0;
      reg_isValid <= 1'h0;
    end
    else begin
      reg_pc <= io_flush ? 64'h0 : io_in_pc;
      reg_instruction <= io_flush ? 64'h0 : io_in_instruction;
      reg_sextImm <= io_flush ? 64'h0 : io_in_sextImm;
      reg_readdata1 <= io_flush ? 64'h0 : io_in_readdata1;
      reg_readdata2 <= io_flush ? 64'h0 : io_in_readdata2;
      reg_isValid <= ~io_flush & io_in_isValid;
    end
  end // always @(posedge)
  assign io_data_pc = reg_pc;
  assign io_data_instruction = reg_instruction;
  assign io_data_sextImm = reg_sextImm;
  assign io_data_readdata1 = reg_readdata1;
  assign io_data_readdata2 = reg_readdata2;
  assign io_data_isValid = reg_isValid;
endmodule

