// Generated by CIRCT firtool-1.114.1
module StageReg(
  input         clock,
                reset,
  input  [31:0] io_in_instruction,
  input  [63:0] io_in_pc,
  input         io_in_isValid,
                io_flush,
                io_valid,
  output [31:0] io_data_instruction,
  output [63:0] io_data_pc,
  output        io_data_isValid
);

  reg [31:0] reg_instruction;
  reg [63:0] reg_pc;
  reg        reg_isValid;
  always @(posedge clock) begin
    if (reset) begin
      reg_instruction <= 32'h0;
      reg_pc <= 64'h0;
      reg_isValid <= 1'h0;
    end
    else begin
      if (io_flush) begin
        reg_instruction <= 32'h0;
        reg_pc <= 64'h0;
      end
      else if (io_valid) begin
        reg_instruction <= io_in_instruction;
        reg_pc <= io_in_pc;
      end
      reg_isValid <= ~io_flush & (io_valid ? io_in_isValid : reg_isValid);
    end
  end // always @(posedge)
  assign io_data_instruction = reg_instruction;
  assign io_data_pc = reg_pc;
  assign io_data_isValid = reg_isValid;
endmodule

