// Generated by CIRCT firtool-1.114.1
module StageReg_8(
  input        clock,
               reset,
  input  [1:0] io_in_mem_ctrl_memop,
  input        io_in_wb_ctrl_toreg,
               io_in_wb_ctrl_regwrite,
               io_flush,
  output [1:0] io_data_mem_ctrl_memop,
  output       io_data_wb_ctrl_toreg,
               io_data_wb_ctrl_regwrite
);

  reg [1:0] reg_mem_ctrl_memop;
  reg       reg_wb_ctrl_toreg;
  reg       reg_wb_ctrl_regwrite;
  always @(posedge clock) begin
    if (reset) begin
      reg_mem_ctrl_memop <= 2'h0;
      reg_wb_ctrl_toreg <= 1'h0;
      reg_wb_ctrl_regwrite <= 1'h0;
    end
    else begin
      reg_mem_ctrl_memop <= io_flush ? 2'h0 : io_in_mem_ctrl_memop;
      reg_wb_ctrl_toreg <= ~io_flush & io_in_wb_ctrl_toreg;
      reg_wb_ctrl_regwrite <= ~io_flush & io_in_wb_ctrl_regwrite;
    end
  end // always @(posedge)
  assign io_data_mem_ctrl_memop = reg_mem_ctrl_memop;
  assign io_data_wb_ctrl_toreg = reg_wb_ctrl_toreg;
  assign io_data_wb_ctrl_regwrite = reg_wb_ctrl_regwrite;
endmodule

