// Generated by CIRCT firtool-1.114.1
module StageReg_6(
  input         clock,
                reset,
  input  [63:0] io_in_ex_result,
                io_in_mem_writedata,
                io_in_nextpc,
  input         io_in_taken,
  input  [63:0] io_in_instruction,
  input         io_in_isValid,
                io_flush,
  output [63:0] io_data_ex_result,
                io_data_mem_writedata,
                io_data_nextpc,
  output        io_data_taken,
  output [63:0] io_data_instruction,
  output        io_data_isValid
);

  reg [63:0] reg_ex_result;
  reg [63:0] reg_mem_writedata;
  reg [63:0] reg_nextpc;
  reg        reg_taken;
  reg [63:0] reg_instruction;
  reg        reg_isValid;
  always @(posedge clock) begin
    if (reset) begin
      reg_ex_result <= 64'h0;
      reg_mem_writedata <= 64'h0;
      reg_nextpc <= 64'h0;
      reg_taken <= 1'h0;
      reg_instruction <= 64'h0;
      reg_isValid <= 1'h0;
    end
    else begin
      reg_ex_result <= io_flush ? 64'h0 : io_in_ex_result;
      reg_mem_writedata <= io_flush ? 64'h0 : io_in_mem_writedata;
      reg_nextpc <= io_flush ? 64'h0 : io_in_nextpc;
      reg_taken <= ~io_flush & io_in_taken;
      reg_instruction <= io_flush ? 64'h0 : io_in_instruction;
      reg_isValid <= ~io_flush & io_in_isValid;
    end
  end // always @(posedge)
  assign io_data_ex_result = reg_ex_result;
  assign io_data_mem_writedata = reg_mem_writedata;
  assign io_data_nextpc = reg_nextpc;
  assign io_data_taken = reg_taken;
  assign io_data_instruction = reg_instruction;
  assign io_data_isValid = reg_isValid;
endmodule

