#  This file is distributed under the BSD 3-Clause License. See LICENSE for details.
#cc_library(
#    name = "inou_lef",
#    srcs = ["inou_lef.cpp"],
#    hdrs = ["inou_lef.hpp"],
#    includes = ["."], # needed because other passes depend on this pass
#    visibility = ["//visibility:public"],
#    deps = [
#        "//third_party/misc/lef/lef:lef",
#        "//core:core"
#    ],
#)

#deprecated
#cc_binary(
#    name = "lglef",
#    srcs = ["lglef.cpp"],
#    linkopts = ['-lpthread'],
#    deps = [
#        ":inou_lef",
#        "//inou/json:inou_json",
#        "@boost//:filesystem", "@boost//:program_options",
#    ],
#)
