#!/usr/bin/env python3
"""Generate an `lgraph-sim` launcher for a generated `<Top>_Lgraph.lean`.

Direction 2's executable is a GENERIC simulator over `DesignCert`; a launcher
packages one certificate as data and calls `Compiler.Direct.simMain`.  It emits
no semantic code and no proof script, so running it is still direct
interpretation of the certificate -- which is why a per-design launcher does not
make the deliverable "generated semantic code".

Two outputs are produced under `formal/lean/Sims/`:

  Sims/<Top>_Cert.lean   the certificate, with its import redirected from
                         `Compiler.CompileDesign` to `Compiler.DirectTrace` and
                         the residual half removed -- the direct path does not
                         need the verified compiler, or Mathlib, to exist
  Sims/<Top>_Main.lean   the launcher

and a `[[lean_exe]]` stanza is appended to `lakefile.toml` unless it is already
there.  Build with

    lake build Sim<Top>          ->  .lake/build/bin/lgraph-sim-<Top>

or, to skip the native link, run it in the interpreter:

    lake env lean --run Sims/<Top>_Main.lean -- <args>

Usage:  make_sim_launcher.py CERT.lean [CERT.lean ...] [--keep-compiler]
"""

import argparse
import os
import re
import sys

LEAN_DIR = os.path.realpath(
    os.path.join(os.path.dirname(__file__), "..", "..", "..", "formal", "lean"))
SIMS = os.path.join(LEAN_DIR, "Sims")

CERT_RE = re.compile(r"^def\s+(\w+)_designCert\s*:\s*DesignCert", re.M)

MAIN = """\
/-
Launcher for `{base}`, generated by pass/lean/scripts/make_sim_launcher.py.
It packages one certificate as DATA and calls the generic simulator; no
semantic model and no proof script is emitted here.
-/
import LeanSemanticPrimitives.Compiler.DirectSim
import Sims.{base}_Cert

def main (args : List String) : IO UInt32 :=
  Compiler.Direct.simMain [("{base}", {base}_designCert)] args
"""

EXE = """
[[lean_exe]]
name = "Sim{base}"
root = "Sims.{base}_Main"
exeName = "lgraph-sim-{base}"
"""

BENCH = """\
/-
Phase-6 measurement and differential harness for `{base}`, generated by
pass/lean/scripts/make_sim_launcher.py.  Unlike the plain launcher this DOES
pull in the verified compiler: it exists to compare the two implementations and
to time them on the same inputs and the same initial state.
-/
import LeanSemanticPrimitives.Compiler.DirectBench
import Sims.{base}_Cert

def main (args : List String) : IO UInt32 :=
  Compiler.Direct.benchMain "{base}" {base}_designCert args
"""

BENCH_EXE = """
[[lean_exe]]
name = "Bench{base}"
root = "Sims.{base}_Bench"
exeName = "lgraph-bench-{base}"
"""


def make_one(path, keep_compiler, bench):
    text = open(path, encoding="utf-8", errors="replace").read()
    m = CERT_RE.search(text)
    if not m:
        print(f"{path}: no `_designCert` definition", file=sys.stderr)
        return None
    base = m.group(1)
    if not keep_compiler:
        text = text.replace("import LeanSemanticPrimitives.Compiler.CompileDesign",
                            "import LeanSemanticPrimitives.Compiler.DirectTrace")
        cut = text.find("/-- Compile-and-run.")
        if cut < 0:
            m2 = re.search(r"^def\s+\w+_step\s*:", text, re.M)
            cut = m2.start() if m2 else len(text)
        text = text[:cut]
    os.makedirs(SIMS, exist_ok=True)
    cert_out = os.path.join(SIMS, f"{base}_Cert.lean")
    main_out = os.path.join(SIMS, f"{base}_Main.lean")
    with open(cert_out, "w", encoding="utf-8") as f:
        f.write(text)
    with open(main_out, "w", encoding="utf-8") as f:
        f.write(MAIN.format(base=base))
    lakefile = os.path.join(LEAN_DIR, "lakefile.toml")
    lk = open(lakefile, encoding="utf-8").read()
    if 'name = "Sims"' not in lk:
        print("lakefile.toml has no `Sims` lean_lib; add one before generating launchers",
              file=sys.stderr)
        return None
    if f'name = "Sim{base}"' not in lk:
        with open(lakefile, "a", encoding="utf-8") as f:
            f.write(EXE.format(base=base))
    print(f"{base}: {cert_out}\n{base}: {main_out}\n"
          f"{base}: lake build Sim{base}  ->  .lake/build/bin/lgraph-sim-{base}")
    if bench:
        bench_out = os.path.join(SIMS, f"{base}_Bench.lean")
        with open(bench_out, "w", encoding="utf-8") as f:
            f.write(BENCH.format(base=base))
        lk = open(lakefile, encoding="utf-8").read()
        if f'name = "Bench{base}"' not in lk:
            with open(lakefile, "a", encoding="utf-8") as f:
                f.write(BENCH_EXE.format(base=base))
        print(f"{base}: {bench_out}\n"
              f"{base}: lake build Bench{base}  ->  .lake/build/bin/lgraph-bench-{base}")
    return base


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("certs", nargs="+")
    ap.add_argument("--keep-compiler", action="store_true",
                    help="keep the `CompileDesign` import in the certificate module")
    ap.add_argument("--bench", action="store_true",
                    help="also emit the phase-6 measurement/differential harness")
    args = ap.parse_args()
    ok = [make_one(p, args.keep_compiler, args.bench) for p in args.certs]
    return 0 if all(ok) else 1


if __name__ == "__main__":
    sys.exit(main())
