#  This file is distributed under the BSD 3-Clause License. See LICENSE for details.
cc_library(
    name = "inou_ramgen",
    srcs = ["inou_ramgen.cpp"],
    hdrs = ["inou_ramgen.hpp"],
    visibility = ["//visibility:public"],
    includes = ["."],
    deps = [
        "//meta:meta",
    ],
)

