/* Generated by Yosys 0.9+3582 (git sha1 de7997837, gcc 9.3.0-15 -fPIC -Os) */

module NotAnd_NL(io_a, io_b, io_x);
  input [3:0] io_a;
  input [3:0] io_b;
  output [4:0] io_x;
  sky130_fd_sc_hs__nor2b_1 _0_ (
    .A(io_a[0]),
    .B_N(io_b[0]),
    .Y(io_x[0])
  );
  sky130_fd_sc_hs__nor2b_1 _1_ (
    .A(io_a[1]),
    .B_N(io_b[1]),
    .Y(io_x[1])
  );
  sky130_fd_sc_hs__nor2b_1 _2_ (
    .A(io_a[2]),
    .B_N(io_b[2]),
    .Y(io_x[2])
  );
  sky130_fd_sc_hs__nor2b_1 _3_ (
    .A(io_a[3]),
    .B_N(io_b[3]),
    .Y(io_x[3])
  );
  assign io_x[4] = 1'b0;
endmodule
