/* Generated by Yosys 0.7+627 (git sha1 e275692e, gcc 8.1.1 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -fPIC -Os) */

module pt_simple_add_dfg(a, b, s);
  input a;
  input b;
  output s;
  wire tmp0;
  assign tmp0 = a + b;
  assign s = tmp0;
endmodule
