/* Generated by Yosys 0.7+627 (git sha1 e275692e, gcc 8.1.1 -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -fPIC -Os) */

module trivial_add(a, b, c);
  input a;
  input b;
  output c;
  wire lgraph_cell_4;
  assign lgraph_cell_4 = a + b;
  assign c = lgraph_cell_4;
endmodule
