#  This file is distributed under the BSD 3-Clause License. See LICENSE for details.

load("//tools:copt_default.bzl", "COPTS")

cc_library(
    name = "headers",
    hdrs = glob(["include/*.hpp"]),
    copts = COPTS,
    visibility = ["//visibility:public"],
    includes = ["include"],
)

