/* Generated by Yosys livehd+0.9+ */

module hier_tuple_nested_if3(en, \foo.a );
  wire [4:0] \_._tg_out_%foo_a_4 ;
  wire [4:0] \_._tg_out_%foo_a_6 ;
  wire ___c_0;
  wire ___d_0;
  input [1:0] en;
  output [4:0] \foo.a ;
  wire lg_0;
  wire [1:0] lg_1;
  wire [4:0] lg_2;
  wire [4:0] lg_3;
  wire [4:0] lg_4;
  wire [2:0] lg_5;
  wire [3:0] lg_6;
  wire [3:0] lg_8;
  assign \_._tg_out_%foo_a_4  = ___d_0 ? 5'h0b : 5'h0c;
  assign \_._tg_out_%foo_a_6  = ___c_0 ? 5'h0a : \_._tg_out_%foo_a_4 ;
  assign ___c_0 = ! $signed({ 2'h0, en });
  assign ___d_0 = $signed(2'h1) == $signed(en);
  assign lg_8 = { 2'h0, en };
  assign lg_6 = { 2'h0, en };
  assign lg_5 = { 1'h0, en };
  assign lg_4 = 5'h0c;
  assign lg_3 = 5'h0b;
  assign lg_2 = 5'h0a;
  assign lg_1 = 2'h1;
  assign lg_0 = 1'h0;
  assign \foo.a  = \_._tg_out_%foo_a_6 ;
endmodule
