/* Generated by Yosys 0.7+605 (git sha1 d412b172, clang 6.0.0 -fPIC -Os) */

module constant(c, d, out);
  input [1:0] c;
  input d;
  output [5:0] out;
  wire [4:0] tmp2;
  assign tmp2 = 4'h7 + c;
  assign out = tmp2 + d;
endmodule
