/* Generated by Yosys 0.7+605 (git sha1 d412b172, clang 6.0.0 -fPIC -Os) */

module nested_if_1(a, out);
  input [7:0]a;
  wire [7:0] lgraph_cell_14;
  wire [7:0] lgraph_cell_23;
  output [7:0] out;
  wire tmp0;
  wire [7:0] tmp1;
  wire tmp2;
  wire [7:0] tmp3;
  wire tmp4;
  wire [7:0] tmp5;
  assign tmp0 = $signed(a) > $signed(8'h80);
  assign tmp1 = a & b;
  assign tmp2 = a == 8'hfe;
  assign tmp3 = a | b;
  assign lgraph_cell_14 = tmp2 ? tmp3 : tmp1;
  assign tmp4 = a == 8'h80;
  assign tmp5 = a ^ b;
  assign lgraph_cell_23 = tmp4 ? tmp5 : 8'h00;
  assign out4 = tmp0 ? lgraph_cell_14 : lgraph_cell_23;
endmodule
