/* Generated by Yosys 0.7+605 (git sha1 d412b172, clang 6.0.0 -fPIC -Os) */

module nested_if_0(a, out1);
  input a;
  wire [1:0] lgraph_cell_12;
  output [1:0] out1;
  wire tmp0;
  wire tmp1;
  wire [1:0] tmp2;
  assign tmp0 = $signed(a) >= $signed(8'h80);
  assign tmp1 = a == 8'hff;
  assign tmp2 = a + 1'h1;
  assign lgraph_cell_12 = tmp1 ? tmp2 : 2'h0;
  assign out1 = tmp0 ? lgraph_cell_12 : 2'h0;
endmodule
