/* Generated by Yosys 0.7+605 (git sha1 d412b172, clang 6.0.0 -fPIC -Os) */

module nested_if_3(a, b, out);
  input     [7:0] a;
  input     [7:0] b;
  output    [7:0] out;
  wire      [7:0] lgraph_cell_12;
  wire tmp0;
  wire tmp1;
  wire      [7:0] tmp2;
  assign tmp0 = $signed(a) >= $signed(8'h80);
  assign tmp1 = a == 8'hff;
  assign tmp2 = a & b;
  assign lgraph_cell_12 = tmp1 ? a : tmp2;
  assign out = tmp0 ? lgraph_cell_12 : 8'h0;
endmodule
