/* Generated by Yosys 0.7+605 (git sha1 d412b172, clang 6.0.0 -fPIC -Os) */

module nested_if_1(a, out4);
  input a;
  wire [5:0] lgraph_cell_14;
  wire [5:0] lgraph_cell_23;
  output [5:0] out4;
  wire tmp0;
  wire [5:0] tmp1;
  wire tmp2;
  wire [5:0] tmp3;
  wire tmp4;
  wire [5:0] tmp5;
  assign tmp0 = $signed(a) >= $signed(8'h80);
  assign tmp1 = a + 6'h10;
  assign tmp2 = a == 8'hff;
  assign tmp3 = a + 6'h0f;
  assign lgraph_cell_14 = tmp2 ? tmp3 : tmp1;
  assign tmp4 = a == 7'h7f;
  assign tmp5 = a + 6'h0e;
  assign lgraph_cell_23 = tmp4 ? tmp5 : 6'h00;
  assign out4 = tmp0 ? lgraph_cell_14 : lgraph_cell_23;
endmodule
