/* Generated by Yosys 0.7+605 (git sha1 d412b172, clang 6.0.0 -fPIC -Os) */

module nested_if_2(a, out1, out2, out3);
  input  [7:0] a;
  output [7:0] out1;
  output [7:0] out2;
  output [7:0] out3;
  wire   [7:0] lgraph_cell_16;
  wire   [7:0] lgraph_cell_20;
  wire   [7:0] lgraph_cell_34;
  wire   [7:0] lgraph_cell_38;
  wire         tmp0;
  wire         tmp1;
  wire   [7:0] tmp2;
  wire   [7:0] tmp3;
  wire         tmp4;
  wire   [7:0] tmp5;
  wire   [7:0] tmp6;
  assign tmp0 = $signed(a) > $signed(8'hc8);
  assign tmp1 = a == 8'hc9;
  assign lgraph_cell_38 = tmp4 ? 8'h00 : tmp6;
  assign tmp2 = a + 8'h0a;
  assign tmp3 = a + 8'h0b;
  assign lgraph_cell_16 = tmp1 ? tmp2 : 8'h00;
  assign lgraph_cell_20 = tmp1 ? 8'h00 : tmp3;
  assign tmp4 = a == 8'h80;
  assign tmp5 = a + 8'h0c;
  assign tmp6 = a + 8'h01;
  assign lgraph_cell_34 = tmp4 ? tmp5 : 8'h00;
  assign out1 = tmp0 ? lgraph_cell_16 : lgraph_cell_38;
  assign out2 = tmp0 ? lgraph_cell_20 : 8'h00;
  assign out3 = tmp0 ? 8'h00 : lgraph_cell_34;
endmodule
