/* Generated by Yosys 0.7+605 (git sha1 d412b172, clang 6.0.0 -fPIC -Os) */

module nested_if_2(a, out1, out2, out3);
  input a;
  wire [4:0] lgraph_cell_16;
  wire [4:0] lgraph_cell_20;
  wire [4:0] lgraph_cell_34;
  wire [4:0] lgraph_cell_38;
  output [4:0] out1;
  output [4:0] out2;
  output [4:0] out3;
  wire tmp0;
  wire tmp1;
  wire [4:0] tmp2;
  wire [4:0] tmp3;
  wire tmp4;
  wire [4:0] tmp5;
  wire [4:0] tmp6;
  assign tmp0 = $signed(a) >= $signed(8'h80);
  assign tmp1 = a == 8'hff;
  assign lgraph_cell_38 = tmp4 ? 5'h00 : tmp6;
  assign out2 = tmp0 ? lgraph_cell_20 : 5'h00;
  assign out1 = tmp0 ? lgraph_cell_16 : lgraph_cell_38;
  assign out3 = tmp0 ? 5'h00 : lgraph_cell_34;
  assign tmp2 = a + 5'h0a;
  assign tmp3 = a + 5'h0b;
  assign lgraph_cell_16 = tmp1 ? tmp2 : 5'h00;
  assign lgraph_cell_20 = tmp1 ? 5'h00 : tmp3;
  assign tmp4 = $signed(a) <= $signed(7'h7f);
  assign tmp5 = a + 5'h0c;
  assign tmp6 = a + 5'h0d;
  assign lgraph_cell_34 = tmp4 ? tmp5 : 5'h00;
endmodule
