/* Generated by Yosys 0.7+605 (git sha1 d412b172, clang 6.0.0 -fPIC -Os) */

module sp_if_0(a, out1, out3, out5, out2, out4);
  input  [4:0] a;
  output [4:0] out1;
  output [4:0] out2;
  output [4:0] out3;
  output [4:0] out4;
  output [4:0] out5;
  wire tmp3;
  assign tmp3 = a == 5'hf;
  assign out1 = tmp3 ? 5'd19 : 5'd16;
  assign out2 = tmp3 ? 5'd20 : 5'd0;
  assign out3 = tmp3 ? 5'd17 : 5'd22;
  assign out4 = tmp3 ? 5'd0  : 5'd23;
  assign out5 = tmp3 ? 5'd21 : 5'd24;
endmodule
