/* Generated by Yosys 0.7+605 (git sha1 d412b172, clang 6.0.0 -fPIC -Os) */

module sp_if_0(a, out1, out3, out5, out2, out4);
  input a;
  output [4:0] out1;
  output [2:0] out2;
  output [4:0] out3;
  output [3:0] out4;
  output [3:0] out5;
  wire [4:0] tmp0;
  wire [4:0] tmp1;
  wire tmp3;
  wire [4:0] tmp4;
  wire [2:0] tmp5;
  wire [3:0] tmp6;
  wire [4:0] tmp7;
  wire [3:0] tmp8;
  wire [3:0] tmp9;
  assign tmp0 = a + 4'ha;
  assign tmp1 = a + 4'hb;
  assign out5 = tmp3 ? tmp6 : tmp9;
  assign out1 = tmp3 ? tmp4 : tmp0;
  assign out2 = tmp3 ? tmp5 : 3'h0;
  assign out3 = tmp3 ? tmp1 : tmp7;
  assign out4 = tmp3 ? 4'h0 : tmp8;
  assign tmp3 = a == 8'hff;
  assign tmp4 = a + 1'h1;
  assign tmp5 = a + 2'h2;
  assign tmp6 = a + 2'h3;
  assign tmp7 = a + 3'h4;
  assign tmp8 = a + 3'h5;
  assign tmp9 = a + 3'h6;
endmodule
