/* Generated by Yosys 0.9+1706 (git sha1 6edca057, clang 10.0.0 -fPIC -Os) */

module ssa_rhs(out);
  wire \0d1 ;
  wire [1:0] \0d2 ;
  wire [1:0] \0d3 ;
  wire [2:0] \0d4 ;
  wire [2:0] A_0;
  wire [3:0] A_1;
  wire [3:0] A_2;
  wire [4:0] A_3;
  wire [4:0] A_4;
  wire [4:0] A_5;
  wire ___b_0;
  output [4:0] out;
  assign A_1 = \0d4  + A_0;
  assign ___b_0 = A_0 == A_1;
  assign A_2 = \0d1  + A_1;
  assign A_3 = \0d2  + A_2;
  assign A_4 = \0d3  + A_1;
  assign A_5 = ___b_0 ? A_3 : A_4;
  assign A_0 = 3'h5;
  assign \0d4  = 3'h4;
  assign \0d1  = 1'h1;
  assign \0d2  = 2'h2;
  assign \0d3  = 2'h3;
  assign out = A_5;
endmodule
