
cc_library(
    name = "inou_abc",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    visibility = ["//visibility:public"],
    includes = ["."],
    deps = [
        "//meta:meta",
        "//pyth:py_base",
        "//inou/lef:inou_lef",
        "@abc//:abc",
    ],
)

