#!/usr/bin/env bash
set -euo pipefail

# Emit a per-module CORE-ET filelist for `lhd compile --set yosys.filelist_file=`.
#
# Source of truth, in order:
#   1. dv/rtlcosim/<module>/Makefile   -> NEW_RTL_FINAL   (per-module, minimal)
#   2. hw/ip/<ip>/dv/Makefile          -> RTL_SRCS        (whole-IP fallback)
# Both are expanded BY MAKE (never parsed as text): the lists are built from
# $(PRIM_*) variables that mk/prim.mk resolves per TECH, and mk/rtlcosim.mk
# back-fills package dependencies into NEW_RTL_AUTO.  TECH=generic is the
# behavioural/simulation tree and the one both the verilator head and
# mk/rtlcosim.mk default to.
#
# Usage: scripts/coreet_filelist.sh <module> [<out.f>]
#        COREET_ROOT=... COREET_SRCDIR=... scripts/coreet_filelist.sh ...

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COREET_ROOT="${COREET_ROOT:-/soe/czeng14/projects/core-et}"
PRINT_MK="$SCRIPT_DIR/coreet_print.mk"
TECH="${COREET_TECH:-generic}"

MODULE="${1:?usage: coreet_filelist.sh <module> [<out.f>]}"
OUT="${2:-}"

[[ -r "$PRINT_MK" ]] || { echo "FATAL: missing $PRINT_MK" >&2; exit 2; }

srcs=""
origin=""

cosim_dir="$COREET_ROOT/dv/rtlcosim/$MODULE"
if [[ -f "$cosim_dir/Makefile" ]]; then
  srcs="$(make -C "$cosim_dir" -f Makefile -f "$PRINT_MK" --no-print-directory \
            TECH="$TECH" print-NEW_RTL_FINAL 2>/dev/null || true)"
  origin="dv/rtlcosim/$MODULE/Makefile:NEW_RTL_FINAL"
fi

# Fallback: the owning IP's unit-test Makefile (RTL_SRCS).  Only reached when a
# module has no rtlcosim dir; the list is a superset (the whole IP), which the
# `--top` prune in read_slang narrows back down.
if [[ -z "${srcs// /}" ]]; then
  for dv in $(find "$COREET_ROOT/hw/ip" -maxdepth 4 -name Makefile -path '*/dv/*' 2>/dev/null | sort); do
    d="$(dirname "$dv")"
    got="$(make -C "$d" -f Makefile -f "$PRINT_MK" --no-print-directory \
             TECH="$TECH" print-RTL_SRCS 2>/dev/null || true)"
    case " $got " in
      *"/$MODULE.sv "*) srcs="$got"; origin="${dv#$COREET_ROOT/}:RTL_SRCS"; break ;;
    esac
  done
fi

if [[ -z "${srcs// /}" ]]; then
  echo "FATAL: no filelist found for '$MODULE'" >&2
  echo "       looked in $cosim_dir/Makefile (NEW_RTL_FINAL) and hw/ip/*/dv/Makefile (RTL_SRCS)" >&2
  exit 2
fi

# De-duplicate while PRESERVING ORDER: these lists are dependency-ordered
# (packages first) and slang needs them that way.  Verify every path exists --
# a silently-short filelist elaborates to a degenerate model that still
# "compiles", which is the failure mode run_cva6_alu_lean.sh guards against.
# Substitute the derived slang-clean copies of the two files that use an
# identifier before declaring it (scripts/coreet_patch_srcs.py).  Those are
# original-repo-class defects; the substitution is a pure declaration reorder and
# is recorded in the .f header so no result silently claims to be about the
# unpatched source.
PATCH_MAP="$(dirname "$SCRIPT_DIR")/generated/core-et/patched_src/map.tsv"
subst_of() {
  [[ -r "$PATCH_MAP" ]] || { printf '%s' "$1"; return; }
  local r; r="$(awk -F'\t' -v k="$1" '$1==k{print $2}' "$PATCH_MAP" | head -1)"
  printf '%s' "${r:-$1}"
}

tmp="$(mktemp)"
patched_note=""
trap 'rm -f "$tmp"' EXIT
n=0
for f0 in $srcs; do
  f="$(subst_of "$f0")"
  [[ "$f" != "$f0" ]] && patched_note+="// patched: $(basename "$f0") <- generated/core-et/patched_src/ (decl-before-use reorder)"$'\n'
  [[ -r "$f" ]] || { echo "FATAL: $MODULE filelist names a missing file: $f" >&2; exit 2; }
  grep -qxF "$f" "$tmp" 2>/dev/null && continue
  printf '%s\n' "$f" >> "$tmp"
  n=$((n + 1))
done

# The only `include`s in the minion tree are intpipe_csr_file.sv's eight .svh
# files, in its own rtl dir.  Add the incdir whenever that file is present.
inc=""
if grep -q '/intpipe/csr/rtl/' "$tmp"; then
  inc="+incdir+$COREET_ROOT/hw/ip/minion/intpipe/csr/rtl"
fi

emit() {
  echo "// generated by scripts/coreet_filelist.sh -- do not edit"
  echo "// module : $MODULE"
  echo "// origin : $origin"
  echo "// tech   : $TECH"
  [[ -n "$patched_note" ]] && printf '%s' "$patched_note"
  [[ -n "$inc" ]] && echo "$inc"
  cat "$tmp"
}

if [[ -n "$OUT" ]]; then
  mkdir -p "$(dirname "$OUT")"
  emit > "$OUT"
  echo "$MODULE: $n file(s) -> $OUT"
else
  emit
fi
