#!/usr/bin/env python3
"""Minimal Verilog `ifdef preprocessor for the autogenerated sky130 model file.

Handles `ifdef/`ifndef/`elsif/`else/`endif and object-like `define/`undef.
Expands known object macros; unknown macro uses expand to empty (the only one
hit in FUNCTIONAL mode is UNIT_DELAY). Directives like `timescale,
`celldefine, `default_nettype pass through.
"""
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
defines = {"FUNCTIONAL": ""}

cond_re = re.compile(r"^\s*`(ifdef|ifndef|elsif|else|endif)\b\s*(\w*)")
def_re = re.compile(r"^\s*`(define|undef)\s+(\w+)\s*(.*)$")
use_re = re.compile(r"`(\w+)")
passthrough = {
    "timescale", "celldefine", "endcelldefine", "default_nettype",
    "ifdef", "ifndef", "elsif", "else", "endif", "define", "undef",
}

# stack of [currently_active, any_branch_taken]
stack = []
out = []
for line in open(src, errors="replace"):
    m = cond_re.match(line)
    if m:
        kw, name = m.group(1), m.group(2)
        if kw == "ifdef" or kw == "ifndef":
            want = (name in defines) == (kw == "ifdef")
            active = all(s[0] for s in stack) and want
            stack.append([want, want])
        elif kw == "elsif":
            top = stack[-1]
            take = (name in defines) and not top[1]
            top[0], top[1] = take, top[1] or take
        elif kw == "else":
            top = stack[-1]
            top[0] = not top[1]
            top[1] = True
        elif kw == "endif":
            stack.pop()
        continue
    if not all(s[0] for s in stack):
        continue
    m = def_re.match(line)
    if m:
        if m.group(1) == "define":
            defines[m.group(2)] = m.group(3).strip()
        else:
            defines.pop(m.group(2), None)
        continue

    def expand(mm):
        name = mm.group(1)
        if name in passthrough:
            return mm.group(0)
        return defines.get(name, "")

    out.append(use_re.sub(expand, line))

open(dst, "w").writelines(out)
print(f"wrote {dst}: {len(out)} lines", file=sys.stderr)
