#!/bin/bash
# This file is distributed under the BSD 3-Clause License. See LICENSE for details.
#
# P3 invariant mining (2f-verify): a stuck run (hard multiplier obligation whose
# cone includes a wrap-at-5 counter) mines the counter's range invariant under
# the formal.minetimeout budget. Contract under test:
#   * the run reports "mined N inductive invariant(s)" with N >= 1;
#   * formal_mined.prp is a paste-ready formal block carrying the TIGHT bound
#     (assume(acc.count <= 5)) with provenance comments;
#   * formal_report.json mined[] carries the same facts as machine records
#     (status=inductive, pyrope text, the stuck obligation among targets);
#   * ROUND-TRIP: re-running with the mined block as a sidecar re-proves each
#     mined assume (P1 prove-then-use: "internal assume(s): ... proven (used)");
#   * STALENESS: after a design edit that falsifies the mined fact (wrap at 7),
#     the stale assume REFUTES the run loudly — it can never corrupt a proof;
#   * mine=speculative also reports base-proven candidates the step dropped.

set -u

LHD=lhd/lhd
W="${TEST_TMPDIR:-/tmp/lhd_formal_mine_$$}"
mkdir -p "$W"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

cat >"$W/miner.prp" <<'EOF'
mod miner(a:u32, b:u32, en:bool) -> (o:u8@[0]) {
  reg count:u8 = 0
  o = count
  assert((a * b) * (u32(count) + 1) == (a * b * u32(count)) + (a * b), "hard with count")
  if en {
    if count == 5 {
      count = 0
    } else {
      count += 1
    }
  }
}
EOF

WD="$W/wd"
mkdir -p "$WD"
OUT="$W/mine.out"
"$LHD" formal verify "$W/miner.prp" --top miner --set formal.bound=8 --set formal.timeout=3 \
  --set formal.minetimeout=25 --set formal.engine=bmc --workdir "$WD" >"$OUT" 2>&1
[ $? -eq 0 ] || fail "the stuck run itself must exit 0 (UNKNOWN is a warning): $(cat "$OUT")"
grep -qE 'mined [1-9][0-9]* inductive invariant' "$OUT" || fail "mining must report inductive survivors: $(cat "$OUT")"
[ -s "$WD/formal_mined.prp" ] || fail "formal_mined.prp must be written: $(cat "$OUT")"
grep -q 'AUTO-GENERATED by `lhd formal verify` (mined invariants)' "$WD/formal_mined.prp" || fail "mined block must carry provenance"
grep -q 'assume(acc.count <= 5)' "$WD/formal_mined.prp" || fail "the TIGHT wrap bound must be mined: $(cat "$WD/formal_mined.prp")"
grep -q 'template:range' "$WD/formal_mined.prp" || fail "each mined assume must carry its provenance comment"

python3 - "$WD" <<'PYEOF' || fail "formal_report.json mined[] contract check failed"
import json, sys
d = json.load(open(sys.argv[1] + "/formal_report.json"))
ind = [m for m in d["mined"] if m["status"] == "inductive"]
assert ind, d["mined"]
tight = [m for m in ind if m["pyrope"] == "acc.count <= 5"]
assert tight, ind
assert "count" in tight[0]["keys"]
assert any("hard with count" in json.dumps(o) or True for o in d["obligations"])  # obligations present
stuck = [o["id"] for o in d["obligations"] if o["verdict"] == "unknown"]
assert stuck and any(t in stuck for t in tight[0]["targets"]), (stuck, tight[0]["targets"])
PYEOF

# Round-trip: the mined block re-parses as a sidecar; its assumes are INTERNAL
# (over design state), get RE-PROVEN, and constrain the remaining obligations.
OUT="$W/roundtrip.out"
"$LHD" formal verify "$W/miner.prp" "$WD/formal_mined.prp" --top miner --set formal.bound=6 \
  --set formal.timeout=3 --set formal.engine=bmc >"$OUT" 2>&1
[ $? -eq 0 ] || fail "the round-trip run must not fail (got rc!=0): $(cat "$OUT")"
grep -q '\[miner.mined\].*PROVEN' "$OUT" || fail "the mined assume must re-prove on use: $(cat "$OUT")"
grep -qE 'internal assume\(s\): [1-9][0-9]* proven \(used\)' "$OUT" || fail "the ledger must show the mined assumes as used: $(cat "$OUT")"

# Staleness: edit the design so the mined fact is FALSE (wrap at 7): the stale
# assume REFUTES loudly instead of silently corrupting a proof (P1 discipline).
# The hard obligation is swapped for an easy one so the budget FREEZE cannot
# stop the assume's deepening before its refuting cycle (a frozen assume stays
# honestly disclosed as bounded — but this case pins the refutation itself).
sed -e 's/count == 5/count == 7/' \
    -e 's/assert(.*hard with count.*/assert(count != 200, "easy")/' "$W/miner.prp" >"$W/miner7.prp"
OUT="$W/stale.out"
"$LHD" formal verify "$W/miner7.prp" "$WD/formal_mined.prp" --top miner --set formal.bound=10 \
  --set formal.timeout=10 --set formal.engine=bmc >"$OUT" 2>&1
[ $? -ne 0 ] || fail "a stale mined assume must fail the run after the edit (got rc=0): $(cat "$OUT")"
grep -q '\[miner.mined\].*REFUTED' "$OUT" || fail "the stale mined assume must be REFUTED: $(cat "$OUT")"

# mine=speculative: base-proven candidates the step dropped are also reported.
WD2="$W/wd_spec"
mkdir -p "$WD2"
OUT="$W/spec.out"
"$LHD" formal verify "$W/miner.prp" --top miner --set formal.bound=3 --set formal.timeout=3 \
  --set formal.minetimeout=20 --set formal.engine=bmc --set formal.mine=speculative --workdir "$WD2" >"$OUT" 2>&1
python3 - "$WD2" <<'PYEOF' || fail "mine=speculative report check failed"
import json, sys
d = json.load(open(sys.argv[1] + "/formal_report.json"))
assert d["mined"], "speculative tier must report candidates"
assert all(m["status"] in ("inductive", "speculative") for m in d["mined"])
PYEOF

echo "PASS: P3 mining (tight inductive bound mined + emitted; report mined[]; round-trip re-proves; stale fact refutes; speculative tier)"
