#!/bin/bash
# This file is distributed under the BSD 3-Clause License. See LICENSE for details.
#
# sim.init_zero supplies a power-on zero only to state with neither an explicit
# initializer nor a reset. It must preserve declared initial/reset values, and
# the same setup-only output must support either policy under --run-only.

set -u

LHD="${LHD:-lhd/lhd}"
W="${TEST_TMPDIR:-/tmp/lhd_sim_init_zero_$$}"
mkdir -p "$W"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

cat > "$W/init_zero.prp" <<'EOF'
/*
:name: init_zero
:type: simulation
*/

mod initial_state(idx:u2, data:u9, we:bool, rst:bool)
    -> (plain_flop_o:u8@[0], init_flop_o:u8@[0], reset_flop_o:u8@[0],
        plain_mem_o:u8@[0], init_mem_o:u8@[0]) {
  reg plain_flop:u8
  reg init_flop:u8 = 9
  reg reset_flop:u8:[reset_pin=ref rst] = 7
  reg plain_mem:[4]u8:[ordering="old"]
  reg init_mem:[4]u8:[ordering="old"] = 3

  plain_flop_o = plain_flop
  init_flop_o = init_flop
  reset_flop_o = reset_flop
  plain_mem_o = plain_mem[idx]
  init_mem_o = init_mem[idx]
  if we {
    wrap plain_flop = data
    wrap init_flop = data
    wrap reset_flop = data
    plain_mem[idx] = data
    init_mem[idx] = data
  }
}

mod reset_only_state(rst:bool, data:u65, we:bool) -> (value:u64@[0]) {
  reg state:u64:[reset_pin=ref rst]
  value = state
  if we {
    wrap state = data
  }
}

test initial_state.values(check_plain:bool = false) {
  mut acc = initial_state
  mut plain_flop_v = nil
  mut init_flop_v = nil
  mut reset_flop_v = nil
  mut plain_mem_v = nil
  mut init_mem_v = nil
  tick 1 {
    acc.idx = 2
    acc.data = 99
    acc.we = false
    acc.rst = true
    step
    plain_flop_v = acc.plain_flop_o
    init_flop_v = acc.init_flop_o
    reset_flop_v = acc.reset_flop_o
    plain_mem_v = acc.plain_mem_o
    init_mem_v = acc.init_mem_o
  }
  if check_plain {
    assert(plain_flop_v == 0, "uninitialized, reset-free flop gets the opt-in zero")
    assert(plain_mem_v == 0, "uninitialized, reset-free memory gets the opt-in zero")
  }
  assert(init_flop_v == 9, "an explicit flop initializer is preserved")
  assert(init_mem_v == 3, "an explicit memory initializer is preserved")
  assert(reset_flop_v == 7, "the runtime reset value is preserved")
}

test reset_only_state.runtime_reset {
  mut acc = reset_only_state
  mut value = nil
  tick 1 {
    acc.rst = true
    acc.data = 99
    acc.we = false
    step
    value = acc.value
  }
  assert(value == 0, "a reset without an explicit value retains its zero reset value")
}

// This test is intentionally expected to fail under sim.init_zero: reset-only
// state remains unknown until reset is actually asserted.
test reset_only_state.power_on_not_forced {
  mut acc = reset_only_state
  mut value = nil
  tick 1 {
    acc.rst = false
    acc.data = 99
    acc.we = false
    step
    value = acc.value
  }
  assert(value == 0, "reset-only state stayed unknown before reset")
}
EOF

# Generate one driver containing all three tests; subsequent --run-only calls
# select the positive and negative contracts independently.
"$LHD" sim "$W/init_zero.prp" --setup-only --workdir "$W/run" -q \
  >/dev/null 2>&1 || fail "init-zero fixture did not set up"

# The default leaves plain state unconstrained while honoring explicit values.
"$LHD" sim "$W/init_zero.prp" initial_state.values --run-only --workdir "$W/run" --arg check_plain=0 -q \
  >/dev/null 2>&1 || fail "default initialization changed explicit initial/reset values"

# init_zero is runtime-selectable and only fills the otherwise-uninitialized
# state. Reuse the exact driver generated by the default run.
"$LHD" sim "$W/init_zero.prp" initial_state.values --run-only --workdir "$W/run" --set sim.init_zero=true \
  --arg check_plain=1 -q >/dev/null 2>&1 \
  || fail "sim.init_zero did not selectively initialize plain flop/memory state"

# A reset-only flop is not an init-zero candidate. It stays unknown before its
# reset is asserted, then takes the existing default reset value (zero).
"$LHD" sim "$W/init_zero.prp" reset_only_state.runtime_reset --run-only --workdir "$W/run" \
  --set sim.init_zero=true -q >/dev/null 2>&1 \
  || fail "sim.init_zero changed the runtime reset value"
"$LHD" sim "$W/init_zero.prp" reset_only_state.power_on_not_forced --run-only --workdir "$W/run" \
  --set sim.init_zero=true -q > "$W/reset-only.json" 2>&1 \
  && fail "sim.init_zero incorrectly initialized reset-only state"
grep -q 'reset-only state stayed unknown before reset' "$W/reset-only.json" \
  || fail "reset-only negative discriminator failed for an unexpected reason: $(cat "$W/reset-only.json")"

grep -q -- '--init-zero' "$W/run/sim/drv.cpp" \
  || fail "generated driver does not expose its init-zero runtime switch"

# The option participates in the canonical sim.* registry and boolean grammar.
"$LHD" list options sim | grep -q '"name":"sim.init_zero","method":"sim","default":"false"' \
  || fail "sim.init_zero is missing from the option registry"
"$LHD" describe sim.init_zero | grep -q '"name":"sim.init_zero","kind":"option","method":"sim"' \
  || fail "lhd describe does not resolve sim.init_zero"
"$LHD" sim "$W/init_zero.prp" --setup-only --workdir "$W/bad" --set sim.init_zero=maybe -q \
  > "$W/bad.json" 2>/dev/null && fail "sim.init_zero accepted a non-boolean value"
grep -q 'expects true|false' "$W/bad.json" \
  || fail "sim.init_zero invalid-value diagnostic is unclear: $(cat "$W/bad.json")"

echo "PASS: lhd sim selective init-zero policy"
