#!/bin/bash
# This file is distributed under the BSD 3-Clause License. See LICENSE for details.
#
# P3 invariant mining (2f-verify): a stuck run (hard multiplier obligation whose
# cone includes a wrap-at-5 counter) mines the counter's range invariant under
# the formal.spec_mining_timeout budget. Contract under test:
#   * the run reports "mined N inductive invariant(s)" with N >= 1;
#   * formal_mined.prp is a paste-ready formal block carrying the TIGHT bound
#     (assume(acc.count <= 5)) with provenance comments;
#   * formal_report.json mined[] carries the same facts as machine records
#     (status=inductive, pyrope text, the stuck obligation among targets);
#   * EXIT POLICY (formal.strict, default TRUE): an undecided run is a FAILURE,
#     not a pass — the stuck run exits 7 ("unsupported": the TOOL ran out, the
#     design is not disproved) and says so actionably, while STILL writing its
#     mining artifacts so an agent loop can read them off the failing run.
#     The `formal.strict=false` opt-out is pinned by lhd_formal_verify_test.
#   * ROUND-TRIP: re-running with the mined block as a sidecar re-proves each
#     mined assume (prove-then-use: "checked assume(s): ... proven (used)");
#   * STALENESS: after a design edit that falsifies the mined fact (wrap at 7),
#     the stale assume REFUTES the run loudly — it can never corrupt a proof;
#   * mine=speculative also reports base-proven candidates the step dropped.
#
# The stuck obligation is hard BY CONSTRUCTION, not budget-limited: over u32
# operands `(a*b)*(count+1) == a*b*count + a*b` bit-blasts to a 64x33 multiplier
# distributivity miter. The identical design with u4 operands is PROVEN
# inductively in ~2s; u8/u10/u12 are already UNKNOWN at 60s per query, and u32
# stays UNKNOWN at 120s per query. The permanent UNKNOWN is the whole point of
# the fixture (something must stay open for mining to have a target) — do NOT
# try to "fix" it by raising formal.timeout. The short budgets below are enough
# to establish UNKNOWN while leaving most of this test's time for mining.

set -u

LHD=lhd/lhd
W="${TEST_TMPDIR:-/tmp/lhd_formal_mine_$$}"
mkdir -p "$W"

# lhd::exit_code_for (lhd/lhd_meta.cpp): distinct class -> code, so a caller can
# tell a TOOL limitation from a DESIGN result. The two this test discriminates:
RC_INCONCLUSIVE=7   # class "unsupported" — solver gave up; nothing proved, nothing disproved
RC_REFUTED=10       # class "equiv_fail"  — a real counterexample exists

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

cat >"$W/miner.prp" <<'EOF'
mod miner(a:u32, b:u32, en:bool) -> (o:u8@[0]) {
  reg count:u8 = 0
  o = count
  assert((a * b) * (u32(count) + 1) == (a * b * u32(count)) + (a * b), "hard with count")
  if en {
    if count == 5 {
      count = 0
    } else {
      count += 1
    }
  }
}
EOF

WD="$W/wd"
mkdir -p "$WD"
OUT="$W/mine.out"
"$LHD" formal verify "$W/miner.prp" --top miner --set formal.bound=6 --set formal.timeout=1 \
  --set formal.min_timeout=1 --set formal.spec_mining_timeout=2 --set formal.engine=bmc \
  --set formal.mine=speculative --workdir "$WD" >"$OUT" 2>&1
RC=$?
# Default formal.strict=true: an inconclusive run must NOT exit 0 (a gate built on
# this run could not otherwise tell it from a proof), and must NOT be reported as a
# refutation either — the design is undecided, not disproved.
[ "$RC" -eq "$RC_INCONCLUSIVE" ] \
  || fail "the stuck run must exit $RC_INCONCLUSIVE (undecided, not a pass and not a refutation); got rc=$RC: $(cat "$OUT")"
grep -q "could not decide 'miner.miner'" "$OUT" || fail "the strict failure must name the undecided design: $(cat "$OUT")"
grep -q 'hard with count' "$OUT" || fail "the strict failure must name the stuck obligation: $(cat "$OUT")"
grep -q 'raise --set formal.timeout' "$OUT" || fail "the strict failure must say the budget ran out (actionable): $(cat "$OUT")"
# The mining artifacts are written BEFORE the strict exit: the agent loop that
# consumes them only ever runs on stuck designs, so a failing run must still emit.
grep -qE 'mined [1-9][0-9]* inductive invariant' "$OUT" || fail "mining must report inductive survivors: $(cat "$OUT")"
[ -s "$WD/formal_mined.prp" ] || fail "formal_mined.prp must be written: $(cat "$OUT")"
grep -q 'AUTO-GENERATED by `lhd formal verify` (mined invariants)' "$WD/formal_mined.prp" || fail "mined block must carry provenance"
grep -q 'assume(acc.count <= 5)' "$WD/formal_mined.prp" || fail "the TIGHT wrap bound must be mined: $(cat "$WD/formal_mined.prp")"
grep -q 'template:range' "$WD/formal_mined.prp" || fail "each mined assume must carry its provenance comment"

python3 - "$WD" <<'PYEOF' || fail "formal_report.json mined[] contract check failed"
import json, sys
d = json.load(open(sys.argv[1] + "/formal_report.json"))
ind = [m for m in d["mined"] if m["status"] == "inductive"]
assert ind, d["mined"]
tight = [m for m in ind if m["pyrope"] == "acc.count <= 5"]
assert tight, ind
assert "count" in tight[0]["keys"]
assert any("hard with count" in json.dumps(o) or True for o in d["obligations"])  # obligations present
stuck = [o["id"] for o in d["obligations"] if o["verdict"] == "unknown"]
assert stuck and any(t in stuck for t in tight[0]["targets"]), (stuck, tight[0]["targets"])
assert all(m["status"] in ("inductive", "speculative") for m in d["mined"])
PYEOF

# Round-trip: the mined block re-parses as a sidecar; its assumes are INTERNAL
# (over design state), get RE-PROVEN, and constrain the remaining obligations.
# The hard obligation is still stuck, so the run is inconclusive (rc=7) — what
# matters is that adding the mined block does NOT turn it into a refutation
# (rc=10) and that the assumes are proven and used.
OUT="$W/roundtrip.out"
"$LHD" formal verify "$W/miner.prp" "$WD/formal_mined.prp" --top miner --set formal.bound=3 \
  --set formal.timeout=1 --set formal.min_timeout=1 --set formal.engine=bmc >"$OUT" 2>&1
RC=$?
[ "$RC" -eq "$RC_INCONCLUSIVE" ] \
  || fail "the round-trip must stay merely inconclusive (rc=$RC_INCONCLUSIVE), not break the run; got rc=$RC: $(cat "$OUT")"
grep -q '\[miner.mined\].*PROVEN' "$OUT" || fail "the mined assume must re-prove on use: $(cat "$OUT")"
grep -qE 'checked assume\(s\): [1-9][0-9]* proven \(used\)' "$OUT" || fail "the ledger must show the mined assumes as used: $(cat "$OUT")"

# Staleness: edit the design so the mined fact is FALSE (wrap at 7): the stale
# assume REFUTES loudly instead of silently corrupting a proof (P1 discipline).
# The hard obligation is swapped for an easy one so the budget FREEZE cannot
# stop the assume's deepening before its refuting cycle (a frozen assume stays
# honestly disclosed as bounded — but this case pins the refutation itself).
# rc must be the REFUTED class, not merely non-zero: under formal.strict an
# inconclusive also exits non-zero, so only the exact code separates "the mined
# fact is disproved" from "the solver gave up".
sed -e 's/count == 5/count == 7/' \
    -e 's/assert(.*hard with count.*/assert(count != 200, "easy")/' "$W/miner.prp" >"$W/miner7.prp"
OUT="$W/stale.out"
"$LHD" formal verify "$W/miner7.prp" "$WD/formal_mined.prp" --top miner --set formal.bound=10 \
  --set formal.timeout=10 --set formal.engine=bmc >"$OUT" 2>&1
RC=$?
[ "$RC" -eq "$RC_REFUTED" ] \
  || fail "a stale mined assume must REFUTE the run after the edit (want rc=$RC_REFUTED, got rc=$RC): $(cat "$OUT")"
grep -q '\[miner.mined\].*REFUTED' "$OUT" || fail "the stale mined assume must be REFUTED: $(cat "$OUT")"

echo "PASS: P3 mining (tight inductive bound mined + emitted; strict fails the stuck run; report mined[] including speculative tier; round-trip re-proves; stale fact refutes)"
