#load("@rules_graal//graal:graal.bzl", "graal_binary")

#java_library(
#    name = "rw4lg",
#    #main_class = "Main",
#    srcs = glob(["Main_test.java"]),
#)

#graal_binary(
#    name = "main-native",
#    deps = [":rw4lg"],
#    main_class = "Main_test",
#)
#
#
#graal_binary(
#    name = "main-native-reflectioncfg",
#    deps = [":rw4lg"],
#    initialize_at_build_time=["Main_test"],
#    reflection_configuration = "reflection.cfg",
#    main_class = "Main_test",
#)

